// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (consolidated resource)
// Package: r5

package r5

import (
	"bytes"
	"encoding/json"
	"encoding/xml"
	"fmt"
)

// =============================================================================
// DeviceAssociation Resource
// =============================================================================

// DeviceAssociation represents FHIR DeviceAssociation.
type DeviceAssociation struct {
	// FHIR resource type
	ResourceType string `json:"resourceType"`
	// Logical id of this artifact
	Id *string `json:"id,omitempty"`
	// Metadata about the resource
	Meta *Meta `json:"meta,omitempty"`
	// A set of rules under which this content was created
	ImplicitRules *string `json:"implicitRules,omitempty"`
	// Extension for ImplicitRules
	ImplicitRulesExt *Element `json:"_implicitRules,omitempty"`
	// Language of the resource content
	Language *string `json:"language,omitempty"`
	// Extension for Language
	LanguageExt *Element `json:"_language,omitempty"`
	// Text summary of the resource, for human interpretation
	Text *Narrative `json:"text,omitempty"`
	// Contained, inline Resources
	Contained []Resource `json:"contained,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Instance identifier
	Identifier []Identifier `json:"identifier,omitempty"`
	// Reference to the devices associated with the patient or group
	Device Reference `json:"device"`
	// Describes the relationship between the device and subject
	Category []CodeableConcept `json:"category,omitempty"`
	// implanted | explanted | attached | entered-in-error | unknown
	Status CodeableConcept `json:"status"`
	// The reasons given for the current association status
	StatusReason []CodeableConcept `json:"statusReason,omitempty"`
	// The individual, group of individuals or device that the device is on or associated with
	Subject *Reference `json:"subject,omitempty"`
	// Current anatomical location of the device in/on subject
	BodyStructure *Reference `json:"bodyStructure,omitempty"`
	// Begin and end dates and times for the device association
	Period *Period `json:"period,omitempty"`
	// The details about the device when it is in use to describe its operation
	Operation []DeviceAssociationOperation `json:"operation,omitempty"`
}

// GetResourceType returns the FHIR resource type.
func (r *DeviceAssociation) GetResourceType() string {
	return "DeviceAssociation"
}

// GetId returns the resource's logical ID.
func (r *DeviceAssociation) GetId() *string {
	return r.Id
}

// SetId sets the resource's logical ID.
func (r *DeviceAssociation) SetId(id string) {
	r.Id = &id
}

// GetMeta returns the resource's Meta element.
func (r *DeviceAssociation) GetMeta() *Meta {
	return r.Meta
}

// SetMeta sets the resource's Meta element.
func (r *DeviceAssociation) SetMeta(m *Meta) {
	r.Meta = m
}

// GetText returns the resource's narrative text.
func (r *DeviceAssociation) GetText() *Narrative {
	return r.Text
}

// SetText sets the resource's narrative text.
func (r *DeviceAssociation) SetText(t *Narrative) {
	r.Text = t
}

// GetContained returns the resource's contained resources.
func (r *DeviceAssociation) GetContained() []Resource {
	return r.Contained
}

// GetExtension returns the resource's extensions.
func (r *DeviceAssociation) GetExtension() []Extension {
	return r.Extension
}

// GetModifierExtension returns the resource's modifier extensions.
func (r *DeviceAssociation) GetModifierExtension() []Extension {
	return r.ModifierExtension
}

// MarshalJSON ensures resourceType is always included in JSON output.
// HTML escaping is disabled to preserve FHIR narrative XHTML content.
//
// Note: Use the package-level Marshal function instead of json.Marshal
// to ensure HTML in narrative text.div fields is not escaped.
func (r DeviceAssociation) MarshalJSON() ([]byte, error) {
	r.ResourceType = "DeviceAssociation"
	type Alias DeviceAssociation
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	if err := enc.Encode((Alias)(r)); err != nil {
		return nil, err
	}
	b := buf.Bytes()
	if len(b) > 0 && b[len(b)-1] == '\n' {
		b = b[:len(b)-1]
	}
	return b, nil
}

// UnmarshalJSON handles deserialization of polymorphic contained resources.
func (r *DeviceAssociation) UnmarshalJSON(data []byte) error {
	// Use an alias to avoid infinite recursion
	type Alias DeviceAssociation
	aux := &struct {
		Contained []json.RawMessage `json:"contained,omitempty"`
		*Alias
	}{
		Alias: (*Alias)(r),
	}

	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}

	// Unmarshal each contained resource using the dispatcher
	if len(aux.Contained) > 0 {
		r.Contained = make([]Resource, len(aux.Contained))
		for i, raw := range aux.Contained {
			resource, err := UnmarshalResource(raw)
			if err != nil {
				return fmt.Errorf("failed to unmarshal contained[%d]: %w", i, err)
			}
			r.Contained[i] = resource
		}
	}

	return nil
}

// MarshalXML serializes DeviceAssociation to FHIR-conformant XML.
func (r DeviceAssociation) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if start.Name.Local == "" {
		start.Name.Local = "DeviceAssociation"
		start.Name.Space = fhirNamespace
	}
	if err := e.EncodeToken(start); err != nil {
		return err
	}

	if err := xmlEncodePrimitiveString(e, "id", r.Id, nil); err != nil {
		return err
	}
	if r.Meta != nil {
		if err := r.Meta.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "meta"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveString(e, "implicitRules", r.ImplicitRules, r.ImplicitRulesExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveString(e, "language", r.Language, r.LanguageExt); err != nil {
		return err
	}
	if r.Text != nil {
		if err := r.Text.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "text"}}); err != nil {
			return err
		}
	}
	for _, c := range r.Contained {
		if c != nil {
			if err := xmlEncodeContainedResource(e, c); err != nil {
				return err
			}
		}
	}
	for _, item := range r.Extension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "extension"}}); err != nil {
			return err
		}
	}
	for _, item := range r.ModifierExtension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "modifierExtension"}}); err != nil {
			return err
		}
	}
	for _, item := range r.Identifier {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "identifier"}}); err != nil {
			return err
		}
	}
	if err := r.Device.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "device"}}); err != nil {
		return err
	}
	for _, item := range r.Category {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "category"}}); err != nil {
			return err
		}
	}
	if err := r.Status.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "status"}}); err != nil {
		return err
	}
	for _, item := range r.StatusReason {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "statusReason"}}); err != nil {
			return err
		}
	}
	if r.Subject != nil {
		if err := r.Subject.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "subject"}}); err != nil {
			return err
		}
	}
	if r.BodyStructure != nil {
		if err := r.BodyStructure.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "bodyStructure"}}); err != nil {
			return err
		}
	}
	if r.Period != nil {
		if err := r.Period.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "period"}}); err != nil {
			return err
		}
	}
	for _, item := range r.Operation {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "operation"}}); err != nil {
			return err
		}
	}

	return e.EncodeToken(start.End())
}

// UnmarshalXML deserializes DeviceAssociation from FHIR-conformant XML.
func (r *DeviceAssociation) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	for {
		tok, err := d.Token()
		if err != nil {
			return err
		}
		switch t := tok.(type) {
		case xml.StartElement:
			switch t.Name.Local {
			case "id":
				v, _, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Id = v
			case "meta":
				var v Meta
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Meta = &v
			case "implicitRules":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.ImplicitRules = v
				r.ImplicitRulesExt = ext
			case "language":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Language = v
				r.LanguageExt = ext
			case "text":
				var v Narrative
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Text = &v
			case "contained":
				res, err := xmlDecodeContainedResource(d, t)
				if err != nil {
					return err
				}
				if res != nil {
					r.Contained = append(r.Contained, res)
				}
			case "extension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Extension = append(r.Extension, v)
			case "modifierExtension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.ModifierExtension = append(r.ModifierExtension, v)
			case "identifier":
				var v Identifier
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Identifier = append(r.Identifier, v)
			case "device":
				if err := r.Device.UnmarshalXML(d, t); err != nil {
					return err
				}
			case "category":
				var v CodeableConcept
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Category = append(r.Category, v)
			case "status":
				if err := r.Status.UnmarshalXML(d, t); err != nil {
					return err
				}
			case "statusReason":
				var v CodeableConcept
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.StatusReason = append(r.StatusReason, v)
			case "subject":
				var v Reference
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Subject = &v
			case "bodyStructure":
				var v Reference
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.BodyStructure = &v
			case "period":
				var v Period
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Period = &v
			case "operation":
				var v DeviceAssociationOperation
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Operation = append(r.Operation, v)
			default:
				if err := d.Skip(); err != nil {
					return err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// DeviceAssociationOperation represents the DeviceAssociation.operation backbone element.
// The details about the device when it is in use to describe its operation
type DeviceAssociationOperation struct {
	// Unique id for inter-element referencing
	Id *string `json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Device operational condition
	Status CodeableConcept `json:"status,omitempty"`
	// The individual performing the action enabled by the device
	Operator []Reference `json:"operator,omitempty"`
	// Begin and end dates and times for the device's operation
	Period *Period `json:"period,omitempty"`
}

// MarshalXML serializes DeviceAssociationOperation to FHIR-conformant XML.
func (b DeviceAssociationOperation) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if start.Name.Local == "" {
		start.Name.Local = "DeviceAssociation.operation"
	}
	if b.Id != nil {
		start.Attr = append(start.Attr, xml.Attr{Name: xml.Name{Local: "id"}, Value: *b.Id})
	}
	if err := e.EncodeToken(start); err != nil {
		return err
	}

	for _, item := range b.Extension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "extension"}}); err != nil {
			return err
		}
	}
	for _, item := range b.ModifierExtension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "modifierExtension"}}); err != nil {
			return err
		}
	}
	if err := b.Status.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "status"}}); err != nil {
		return err
	}
	for _, item := range b.Operator {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "operator"}}); err != nil {
			return err
		}
	}
	if b.Period != nil {
		if err := b.Period.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "period"}}); err != nil {
			return err
		}
	}

	return e.EncodeToken(start.End())
}

// UnmarshalXML deserializes DeviceAssociationOperation from FHIR-conformant XML.
func (r *DeviceAssociationOperation) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	for _, attr := range start.Attr {
		if attr.Name.Local == "id" {
			v := attr.Value
			r.Id = &v
		}
	}

	for {
		tok, err := d.Token()
		if err != nil {
			return err
		}
		switch t := tok.(type) {
		case xml.StartElement:
			switch t.Name.Local {
			case "extension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Extension = append(r.Extension, v)
			case "modifierExtension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.ModifierExtension = append(r.ModifierExtension, v)
			case "status":
				if err := r.Status.UnmarshalXML(d, t); err != nil {
					return err
				}
			case "operator":
				var v Reference
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Operator = append(r.Operator, v)
			case "period":
				var v Period
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Period = &v
			default:
				if err := d.Skip(); err != nil {
					return err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// =============================================================================
// DeviceAssociation - Fluent Builder
// =============================================================================

// DeviceAssociationBuilder provides a fluent API for constructing DeviceAssociation resources.
type DeviceAssociationBuilder struct {
	deviceAssociation *DeviceAssociation
}

// NewDeviceAssociationBuilder creates a new DeviceAssociationBuilder.
func NewDeviceAssociationBuilder() *DeviceAssociationBuilder {
	return &DeviceAssociationBuilder{
		deviceAssociation: &DeviceAssociation{},
	}
}

// Build returns the constructed DeviceAssociation resource.
func (b *DeviceAssociationBuilder) Build() *DeviceAssociation {
	return b.deviceAssociation
}

// SetId sets the Id field.
func (b *DeviceAssociationBuilder) SetId(v string) *DeviceAssociationBuilder {
	b.deviceAssociation.Id = &v
	return b
}

// SetMeta sets the Meta field.
func (b *DeviceAssociationBuilder) SetMeta(v Meta) *DeviceAssociationBuilder {
	b.deviceAssociation.Meta = &v
	return b
}

// SetImplicitRules sets the ImplicitRules field.
func (b *DeviceAssociationBuilder) SetImplicitRules(v string) *DeviceAssociationBuilder {
	b.deviceAssociation.ImplicitRules = &v
	return b
}

// SetLanguage sets the Language field.
func (b *DeviceAssociationBuilder) SetLanguage(v string) *DeviceAssociationBuilder {
	b.deviceAssociation.Language = &v
	return b
}

// SetText sets the Text field.
func (b *DeviceAssociationBuilder) SetText(v Narrative) *DeviceAssociationBuilder {
	b.deviceAssociation.Text = &v
	return b
}

// AddContained adds a Contained element.
func (b *DeviceAssociationBuilder) AddContained(v Resource) *DeviceAssociationBuilder {
	b.deviceAssociation.Contained = append(b.deviceAssociation.Contained, v)
	return b
}

// AddExtension adds a Extension element.
func (b *DeviceAssociationBuilder) AddExtension(v Extension) *DeviceAssociationBuilder {
	b.deviceAssociation.Extension = append(b.deviceAssociation.Extension, v)
	return b
}

// AddModifierExtension adds a ModifierExtension element.
func (b *DeviceAssociationBuilder) AddModifierExtension(v Extension) *DeviceAssociationBuilder {
	b.deviceAssociation.ModifierExtension = append(b.deviceAssociation.ModifierExtension, v)
	return b
}

// AddIdentifier adds a Identifier element.
func (b *DeviceAssociationBuilder) AddIdentifier(v Identifier) *DeviceAssociationBuilder {
	b.deviceAssociation.Identifier = append(b.deviceAssociation.Identifier, v)
	return b
}

// SetDevice sets the Device field.
func (b *DeviceAssociationBuilder) SetDevice(v Reference) *DeviceAssociationBuilder {
	b.deviceAssociation.Device = v
	return b
}

// AddCategory adds a Category element.
func (b *DeviceAssociationBuilder) AddCategory(v CodeableConcept) *DeviceAssociationBuilder {
	b.deviceAssociation.Category = append(b.deviceAssociation.Category, v)
	return b
}

// SetStatus sets the Status field.
func (b *DeviceAssociationBuilder) SetStatus(v CodeableConcept) *DeviceAssociationBuilder {
	b.deviceAssociation.Status = v
	return b
}

// AddStatusReason adds a StatusReason element.
func (b *DeviceAssociationBuilder) AddStatusReason(v CodeableConcept) *DeviceAssociationBuilder {
	b.deviceAssociation.StatusReason = append(b.deviceAssociation.StatusReason, v)
	return b
}

// SetSubject sets the Subject field.
func (b *DeviceAssociationBuilder) SetSubject(v Reference) *DeviceAssociationBuilder {
	b.deviceAssociation.Subject = &v
	return b
}

// SetBodyStructure sets the BodyStructure field.
func (b *DeviceAssociationBuilder) SetBodyStructure(v Reference) *DeviceAssociationBuilder {
	b.deviceAssociation.BodyStructure = &v
	return b
}

// SetPeriod sets the Period field.
func (b *DeviceAssociationBuilder) SetPeriod(v Period) *DeviceAssociationBuilder {
	b.deviceAssociation.Period = &v
	return b
}

// AddOperation adds a Operation element.
func (b *DeviceAssociationBuilder) AddOperation(v DeviceAssociationOperation) *DeviceAssociationBuilder {
	b.deviceAssociation.Operation = append(b.deviceAssociation.Operation, v)
	return b
}

// =============================================================================
// DeviceAssociation - Functional Options
// =============================================================================

// DeviceAssociationOption is a functional option for configuring a DeviceAssociation.
type DeviceAssociationOption func(*DeviceAssociation)

// NewDeviceAssociation creates a new DeviceAssociation with the given options.
func NewDeviceAssociation(opts ...DeviceAssociationOption) *DeviceAssociation {
	r := &DeviceAssociation{}
	for _, opt := range opts {
		opt(r)
	}
	return r
}

// WithDeviceAssociationId sets the Id field.
func WithDeviceAssociationId(v string) DeviceAssociationOption {
	return func(r *DeviceAssociation) {
		r.Id = &v
	}
}

// WithDeviceAssociationMeta sets the Meta field.
func WithDeviceAssociationMeta(v Meta) DeviceAssociationOption {
	return func(r *DeviceAssociation) {
		r.Meta = &v
	}
}

// WithDeviceAssociationImplicitRules sets the ImplicitRules field.
func WithDeviceAssociationImplicitRules(v string) DeviceAssociationOption {
	return func(r *DeviceAssociation) {
		r.ImplicitRules = &v
	}
}

// WithDeviceAssociationLanguage sets the Language field.
func WithDeviceAssociationLanguage(v string) DeviceAssociationOption {
	return func(r *DeviceAssociation) {
		r.Language = &v
	}
}

// WithDeviceAssociationText sets the Text field.
func WithDeviceAssociationText(v Narrative) DeviceAssociationOption {
	return func(r *DeviceAssociation) {
		r.Text = &v
	}
}

// WithDeviceAssociationContained adds a Contained to the DeviceAssociation.
func WithDeviceAssociationContained(v Resource) DeviceAssociationOption {
	return func(r *DeviceAssociation) {
		r.Contained = append(r.Contained, v)
	}
}

// WithDeviceAssociationExtension adds a Extension to the DeviceAssociation.
func WithDeviceAssociationExtension(v Extension) DeviceAssociationOption {
	return func(r *DeviceAssociation) {
		r.Extension = append(r.Extension, v)
	}
}

// WithDeviceAssociationModifierExtension adds a ModifierExtension to the DeviceAssociation.
func WithDeviceAssociationModifierExtension(v Extension) DeviceAssociationOption {
	return func(r *DeviceAssociation) {
		r.ModifierExtension = append(r.ModifierExtension, v)
	}
}

// WithDeviceAssociationIdentifier adds a Identifier to the DeviceAssociation.
func WithDeviceAssociationIdentifier(v Identifier) DeviceAssociationOption {
	return func(r *DeviceAssociation) {
		r.Identifier = append(r.Identifier, v)
	}
}

// WithDeviceAssociationDevice sets the Device field.
func WithDeviceAssociationDevice(v Reference) DeviceAssociationOption {
	return func(r *DeviceAssociation) {
		r.Device = v
	}
}

// WithDeviceAssociationCategory adds a Category to the DeviceAssociation.
func WithDeviceAssociationCategory(v CodeableConcept) DeviceAssociationOption {
	return func(r *DeviceAssociation) {
		r.Category = append(r.Category, v)
	}
}

// WithDeviceAssociationStatus sets the Status field.
func WithDeviceAssociationStatus(v CodeableConcept) DeviceAssociationOption {
	return func(r *DeviceAssociation) {
		r.Status = v
	}
}

// WithDeviceAssociationStatusReason adds a StatusReason to the DeviceAssociation.
func WithDeviceAssociationStatusReason(v CodeableConcept) DeviceAssociationOption {
	return func(r *DeviceAssociation) {
		r.StatusReason = append(r.StatusReason, v)
	}
}

// WithDeviceAssociationSubject sets the Subject field.
func WithDeviceAssociationSubject(v Reference) DeviceAssociationOption {
	return func(r *DeviceAssociation) {
		r.Subject = &v
	}
}

// WithDeviceAssociationBodyStructure sets the BodyStructure field.
func WithDeviceAssociationBodyStructure(v Reference) DeviceAssociationOption {
	return func(r *DeviceAssociation) {
		r.BodyStructure = &v
	}
}

// WithDeviceAssociationPeriod sets the Period field.
func WithDeviceAssociationPeriod(v Period) DeviceAssociationOption {
	return func(r *DeviceAssociation) {
		r.Period = &v
	}
}

// WithDeviceAssociationOperation adds a Operation to the DeviceAssociation.
func WithDeviceAssociationOperation(v DeviceAssociationOperation) DeviceAssociationOption {
	return func(r *DeviceAssociation) {
		r.Operation = append(r.Operation, v)
	}
}
