// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (consolidated resource)
// Package: r5

package r5

import (
	"encoding/xml"
)

// =============================================================================
// EnrollmentRequest Resource
// =============================================================================

// enrollmentRequestTypeMarker occupies no memory and serializes as the constant
// "EnrollmentRequest". It replaces a string field that a per-resource MarshalJSON had
// to overwrite on every call, which cost a second bytes.Buffer and json.Encoder
// per resource and, because a promoted MarshalJSON wins over the outer struct,
// silently dropped the fields of any type embedding this one.
//
// Nothing needs to set it: the zero value is correct, and GetResourceType()
// returns the same constant.
type enrollmentRequestTypeMarker struct{}

// MarshalJSON writes the resource type as a JSON string.
func (enrollmentRequestTypeMarker) MarshalJSON() ([]byte, error) {
	return []byte(`"EnrollmentRequest"`), nil
}

// UnmarshalJSON rejects a document whose resourceType names a different resource.
//
// This used to accept and discard whatever the document carried, on the grounds
// that UnmarshalResource validates the type during dispatch. It does — but only on
// that path. json.Unmarshal(data, &patient) does not go through the dispatcher, and
// it is the ordinary way to decode when the type is already known, so a
// Practitioner document decoded into a Patient was accepted in silence and written
// back out as a Patient.
//
// An absent or null resourceType is still accepted; see checkResourceType.
func (*enrollmentRequestTypeMarker) UnmarshalJSON(data []byte) error {
	return checkResourceType(data, "EnrollmentRequest")
}

// EnrollmentRequest represents FHIR EnrollmentRequest.
type EnrollmentRequest struct {
	// FHIR resource type. Emitted automatically; see enrollmentRequestTypeMarker.
	ResourceType enrollmentRequestTypeMarker `json:"resourceType"`
	// Logical id of this artifact
	Id *string `json:"id,omitempty"`
	// Metadata about the resource
	Meta *Meta `json:"meta,omitempty"`
	// A set of rules under which this content was created
	ImplicitRules *string `json:"implicitRules,omitempty"`
	// Extension for ImplicitRules
	ImplicitRulesExt *Element `json:"_implicitRules,omitempty"`
	// Language of the resource content
	Language *string `json:"language,omitempty"`
	// Extension for Language
	LanguageExt *Element `json:"_language,omitempty"`
	// Text summary of the resource, for human interpretation
	Text *Narrative `json:"text,omitempty"`
	// Contained, inline Resources
	Contained ContainedList `json:"contained,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Business Identifier
	Identifier []Identifier `json:"identifier,omitempty"`
	// active | cancelled | draft | entered-in-error
	Status *FinancialResourceStatusCodes `json:"status,omitempty"`
	// Extension for Status
	StatusExt *Element `json:"_status,omitempty"`
	// Creation date
	Created *string `json:"created,omitempty"`
	// Extension for Created
	CreatedExt *Element `json:"_created,omitempty"`
	// Target
	Insurer *Reference `json:"insurer,omitempty"`
	// Responsible practitioner
	Provider *Reference `json:"provider,omitempty"`
	// The subject to be enrolled
	Candidate *Reference `json:"candidate,omitempty"`
	// Insurance information
	Coverage *Reference `json:"coverage,omitempty"`
}

// GetResourceType returns the FHIR resource type.
func (r *EnrollmentRequest) GetResourceType() string {
	return "EnrollmentRequest"
}

// GetId returns the resource's logical ID.
func (r *EnrollmentRequest) GetId() *string {
	return r.Id
}

// SetId sets the resource's logical ID.
func (r *EnrollmentRequest) SetId(id string) {
	r.Id = &id
}

// GetMeta returns the resource's Meta element.
func (r *EnrollmentRequest) GetMeta() *Meta {
	return r.Meta
}

// SetMeta sets the resource's Meta element.
func (r *EnrollmentRequest) SetMeta(m *Meta) {
	r.Meta = m
}

// GetText returns the resource's narrative text.
func (r *EnrollmentRequest) GetText() *Narrative {
	return r.Text
}

// SetText sets the resource's narrative text.
func (r *EnrollmentRequest) SetText(t *Narrative) {
	r.Text = t
}

// GetContained returns the resource's contained resources.
func (r *EnrollmentRequest) GetContained() []Resource {
	return r.Contained
}

// GetExtension returns the resource's extensions.
func (r *EnrollmentRequest) GetExtension() []Extension {
	return r.Extension
}

// GetModifierExtension returns the resource's modifier extensions.
func (r *EnrollmentRequest) GetModifierExtension() []Extension {
	return r.ModifierExtension
}

// MarshalXML serializes EnrollmentRequest to FHIR-conformant XML.
func (r EnrollmentRequest) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if start.Name.Local == "" {
		start.Name.Local = "EnrollmentRequest"
		start.Name.Space = fhirNamespace
	}
	if err := e.EncodeToken(start); err != nil {
		return err
	}

	if err := xmlEncodePrimitiveString(e, "id", r.Id, nil); err != nil {
		return err
	}
	if r.Meta != nil {
		if err := r.Meta.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "meta"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveString(e, "implicitRules", r.ImplicitRules, r.ImplicitRulesExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveString(e, "language", r.Language, r.LanguageExt); err != nil {
		return err
	}
	if r.Text != nil {
		if err := r.Text.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "text"}}); err != nil {
			return err
		}
	}
	for _, c := range r.Contained {
		if c != nil {
			if err := xmlEncodeContainedResource(e, c); err != nil {
				return err
			}
		}
	}
	for _, item := range r.Extension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "extension"}}); err != nil {
			return err
		}
	}
	for _, item := range r.ModifierExtension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "modifierExtension"}}); err != nil {
			return err
		}
	}
	for _, item := range r.Identifier {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "identifier"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveCode(e, "status", r.Status, r.StatusExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveString(e, "created", r.Created, r.CreatedExt); err != nil {
		return err
	}
	if r.Insurer != nil {
		if err := r.Insurer.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "insurer"}}); err != nil {
			return err
		}
	}
	if r.Provider != nil {
		if err := r.Provider.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "provider"}}); err != nil {
			return err
		}
	}
	if r.Candidate != nil {
		if err := r.Candidate.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "candidate"}}); err != nil {
			return err
		}
	}
	if r.Coverage != nil {
		if err := r.Coverage.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "coverage"}}); err != nil {
			return err
		}
	}

	return e.EncodeToken(start.End())
}

// UnmarshalXML deserializes EnrollmentRequest from FHIR-conformant XML.
func (r *EnrollmentRequest) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	for {
		tok, err := d.Token()
		if err != nil {
			return err
		}
		switch t := tok.(type) {
		case xml.StartElement:
			switch t.Name.Local {
			case "id":
				v, _, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Id = v
			case "meta":
				var v Meta
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Meta = &v
			case "implicitRules":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.ImplicitRules = v
				r.ImplicitRulesExt = ext
			case "language":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Language = v
				r.LanguageExt = ext
			case "text":
				var v Narrative
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Text = &v
			case "contained":
				res, err := xmlDecodeContainedResource(d, t)
				if err != nil {
					return err
				}
				if res != nil {
					r.Contained = append(r.Contained, res)
				}
			case "extension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Extension = append(r.Extension, v)
			case "modifierExtension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.ModifierExtension = append(r.ModifierExtension, v)
			case "identifier":
				var v Identifier
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Identifier = append(r.Identifier, v)
			case "status":
				v, ext, err := xmlDecodePrimitiveCode[FinancialResourceStatusCodes](d, t)
				if err != nil {
					return err
				}
				r.Status = v
				r.StatusExt = ext
			case "created":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Created = v
				r.CreatedExt = ext
			case "insurer":
				var v Reference
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Insurer = &v
			case "provider":
				var v Reference
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Provider = &v
			case "candidate":
				var v Reference
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Candidate = &v
			case "coverage":
				var v Reference
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Coverage = &v
			default:
				if err := d.Skip(); err != nil {
					return err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// =============================================================================
// EnrollmentRequest - Fluent Builder
// =============================================================================

// EnrollmentRequestBuilder provides a fluent API for constructing EnrollmentRequest resources.
type EnrollmentRequestBuilder struct {
	enrollmentRequest *EnrollmentRequest
}

// NewEnrollmentRequestBuilder creates a new EnrollmentRequestBuilder.
func NewEnrollmentRequestBuilder() *EnrollmentRequestBuilder {
	return &EnrollmentRequestBuilder{
		// Nothing to set: the type marker carries the resource type, so the zero
		// value is already correct both in memory and on the wire.
		enrollmentRequest: &EnrollmentRequest{},
	}
}

// Build returns the constructed EnrollmentRequest resource.
func (b *EnrollmentRequestBuilder) Build() *EnrollmentRequest {
	return b.enrollmentRequest
}

// SetId sets the Id field.
func (b *EnrollmentRequestBuilder) SetId(v string) *EnrollmentRequestBuilder {
	b.enrollmentRequest.Id = &v
	return b
}

// SetMeta sets the Meta field.
func (b *EnrollmentRequestBuilder) SetMeta(v Meta) *EnrollmentRequestBuilder {
	b.enrollmentRequest.Meta = &v
	return b
}

// SetImplicitRules sets the ImplicitRules field.
func (b *EnrollmentRequestBuilder) SetImplicitRules(v string) *EnrollmentRequestBuilder {
	b.enrollmentRequest.ImplicitRules = &v
	return b
}

// SetLanguage sets the Language field.
func (b *EnrollmentRequestBuilder) SetLanguage(v string) *EnrollmentRequestBuilder {
	b.enrollmentRequest.Language = &v
	return b
}

// SetText sets the Text field.
func (b *EnrollmentRequestBuilder) SetText(v Narrative) *EnrollmentRequestBuilder {
	b.enrollmentRequest.Text = &v
	return b
}

// AddContained adds a Contained element.
func (b *EnrollmentRequestBuilder) AddContained(v Resource) *EnrollmentRequestBuilder {
	b.enrollmentRequest.Contained = append(b.enrollmentRequest.Contained, v)
	return b
}

// AddExtension adds a Extension element.
func (b *EnrollmentRequestBuilder) AddExtension(v Extension) *EnrollmentRequestBuilder {
	b.enrollmentRequest.Extension = append(b.enrollmentRequest.Extension, v)
	return b
}

// AddModifierExtension adds a ModifierExtension element.
func (b *EnrollmentRequestBuilder) AddModifierExtension(v Extension) *EnrollmentRequestBuilder {
	b.enrollmentRequest.ModifierExtension = append(b.enrollmentRequest.ModifierExtension, v)
	return b
}

// AddIdentifier adds a Identifier element.
func (b *EnrollmentRequestBuilder) AddIdentifier(v Identifier) *EnrollmentRequestBuilder {
	b.enrollmentRequest.Identifier = append(b.enrollmentRequest.Identifier, v)
	return b
}

// SetStatus sets the Status field.
func (b *EnrollmentRequestBuilder) SetStatus(v FinancialResourceStatusCodes) *EnrollmentRequestBuilder {
	b.enrollmentRequest.Status = &v
	return b
}

// SetCreated sets the Created field.
func (b *EnrollmentRequestBuilder) SetCreated(v string) *EnrollmentRequestBuilder {
	b.enrollmentRequest.Created = &v
	return b
}

// SetInsurer sets the Insurer field.
func (b *EnrollmentRequestBuilder) SetInsurer(v Reference) *EnrollmentRequestBuilder {
	b.enrollmentRequest.Insurer = &v
	return b
}

// SetProvider sets the Provider field.
func (b *EnrollmentRequestBuilder) SetProvider(v Reference) *EnrollmentRequestBuilder {
	b.enrollmentRequest.Provider = &v
	return b
}

// SetCandidate sets the Candidate field.
func (b *EnrollmentRequestBuilder) SetCandidate(v Reference) *EnrollmentRequestBuilder {
	b.enrollmentRequest.Candidate = &v
	return b
}

// SetCoverage sets the Coverage field.
func (b *EnrollmentRequestBuilder) SetCoverage(v Reference) *EnrollmentRequestBuilder {
	b.enrollmentRequest.Coverage = &v
	return b
}
