// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (consolidated resource)
// Package: r5

package r5

import (
	"bytes"
	"encoding/json"
	"encoding/xml"
	"fmt"
)

// =============================================================================
// NutritionOrder Resource
// =============================================================================

// NutritionOrder represents FHIR NutritionOrder.
type NutritionOrder struct {
	// FHIR resource type
	ResourceType string `json:"resourceType"`
	// Logical id of this artifact
	Id *string `json:"id,omitempty"`
	// Metadata about the resource
	Meta *Meta `json:"meta,omitempty"`
	// A set of rules under which this content was created
	ImplicitRules *string `json:"implicitRules,omitempty"`
	// Extension for ImplicitRules
	ImplicitRulesExt *Element `json:"_implicitRules,omitempty"`
	// Language of the resource content
	Language *string `json:"language,omitempty"`
	// Extension for Language
	LanguageExt *Element `json:"_language,omitempty"`
	// Text summary of the resource, for human interpretation
	Text *Narrative `json:"text,omitempty"`
	// Contained, inline Resources
	Contained []Resource `json:"contained,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Identifiers assigned to this order
	Identifier []Identifier `json:"identifier,omitempty"`
	// Instantiates FHIR protocol or definition
	InstantiatesCanonical []string `json:"instantiatesCanonical,omitempty"`
	// Extension for InstantiatesCanonical
	InstantiatesCanonicalExt []Element `json:"_instantiatesCanonical,omitempty"`
	// Instantiates external protocol or definition
	InstantiatesUri []string `json:"instantiatesUri,omitempty"`
	// Extension for InstantiatesUri
	InstantiatesUriExt []Element `json:"_instantiatesUri,omitempty"`
	// Instantiates protocol or definition
	Instantiates []string `json:"instantiates,omitempty"`
	// Extension for Instantiates
	InstantiatesExt []Element `json:"_instantiates,omitempty"`
	// What this order fulfills
	BasedOn []Reference `json:"basedOn,omitempty"`
	// Composite Request ID
	GroupIdentifier *Identifier `json:"groupIdentifier,omitempty"`
	// draft | active | on-hold | revoked | completed | entered-in-error | unknown
	Status *RequestStatus `json:"status,omitempty"`
	// Extension for Status
	StatusExt *Element `json:"_status,omitempty"`
	// proposal | plan | directive | order | original-order | reflex-order | filler-order | instance-order | option
	Intent *RequestIntent `json:"intent,omitempty"`
	// Extension for Intent
	IntentExt *Element `json:"_intent,omitempty"`
	// routine | urgent | asap | stat
	Priority *RequestPriority `json:"priority,omitempty"`
	// Extension for Priority
	PriorityExt *Element `json:"_priority,omitempty"`
	// Who requires the diet, formula or nutritional supplement
	Subject Reference `json:"subject"`
	// The encounter associated with this nutrition order
	Encounter *Reference `json:"encounter,omitempty"`
	// Information to support fulfilling of the nutrition order
	SupportingInformation []Reference `json:"supportingInformation,omitempty"`
	// Date and time the nutrition order was requested
	DateTime *string `json:"dateTime,omitempty"`
	// Extension for DateTime
	DateTimeExt *Element `json:"_dateTime,omitempty"`
	// Who ordered the diet, formula or nutritional supplement
	Orderer *Reference `json:"orderer,omitempty"`
	// Who is desired to perform the administration of what is being ordered
	Performer []CodeableReference `json:"performer,omitempty"`
	// List of the patient's food and nutrition-related allergies and intolerances
	AllergyIntolerance []Reference `json:"allergyIntolerance,omitempty"`
	// Order-specific modifier about the type of food that should be given
	FoodPreferenceModifier []CodeableConcept `json:"foodPreferenceModifier,omitempty"`
	// Order-specific modifier about the type of food that should not be given
	ExcludeFoodModifier []CodeableConcept `json:"excludeFoodModifier,omitempty"`
	// Capture when a food item is brought in by the patient and/or family
	OutsideFoodAllowed *bool `json:"outsideFoodAllowed,omitempty"`
	// Extension for OutsideFoodAllowed
	OutsideFoodAllowedExt *Element `json:"_outsideFoodAllowed,omitempty"`
	// Oral diet components
	OralDiet *NutritionOrderOralDiet `json:"oralDiet,omitempty"`
	// Supplement components
	Supplement []NutritionOrderSupplement `json:"supplement,omitempty"`
	// Enteral formula components
	EnteralFormula *NutritionOrderEnteralFormula `json:"enteralFormula,omitempty"`
	// Comments
	Note []Annotation `json:"note,omitempty"`
}

// GetResourceType returns the FHIR resource type.
func (r *NutritionOrder) GetResourceType() string {
	return "NutritionOrder"
}

// GetId returns the resource's logical ID.
func (r *NutritionOrder) GetId() *string {
	return r.Id
}

// SetId sets the resource's logical ID.
func (r *NutritionOrder) SetId(id string) {
	r.Id = &id
}

// GetMeta returns the resource's Meta element.
func (r *NutritionOrder) GetMeta() *Meta {
	return r.Meta
}

// SetMeta sets the resource's Meta element.
func (r *NutritionOrder) SetMeta(m *Meta) {
	r.Meta = m
}

// GetText returns the resource's narrative text.
func (r *NutritionOrder) GetText() *Narrative {
	return r.Text
}

// SetText sets the resource's narrative text.
func (r *NutritionOrder) SetText(t *Narrative) {
	r.Text = t
}

// GetContained returns the resource's contained resources.
func (r *NutritionOrder) GetContained() []Resource {
	return r.Contained
}

// GetExtension returns the resource's extensions.
func (r *NutritionOrder) GetExtension() []Extension {
	return r.Extension
}

// GetModifierExtension returns the resource's modifier extensions.
func (r *NutritionOrder) GetModifierExtension() []Extension {
	return r.ModifierExtension
}

// MarshalJSON ensures resourceType is always included in JSON output.
// HTML escaping is disabled to preserve FHIR narrative XHTML content.
//
// Note: Use the package-level Marshal function instead of json.Marshal
// to ensure HTML in narrative text.div fields is not escaped.
func (r NutritionOrder) MarshalJSON() ([]byte, error) {
	r.ResourceType = "NutritionOrder"
	type Alias NutritionOrder
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	if err := enc.Encode((Alias)(r)); err != nil {
		return nil, err
	}
	b := buf.Bytes()
	if len(b) > 0 && b[len(b)-1] == '\n' {
		b = b[:len(b)-1]
	}
	return b, nil
}

// UnmarshalJSON handles deserialization of polymorphic contained resources.
func (r *NutritionOrder) UnmarshalJSON(data []byte) error {
	// Use an alias to avoid infinite recursion
	type Alias NutritionOrder
	aux := &struct {
		Contained []json.RawMessage `json:"contained,omitempty"`
		*Alias
	}{
		Alias: (*Alias)(r),
	}

	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}

	// Unmarshal each contained resource using the dispatcher
	if len(aux.Contained) > 0 {
		r.Contained = make([]Resource, len(aux.Contained))
		for i, raw := range aux.Contained {
			resource, err := UnmarshalResource(raw)
			if err != nil {
				return fmt.Errorf("failed to unmarshal contained[%d]: %w", i, err)
			}
			r.Contained[i] = resource
		}
	}

	return nil
}

// MarshalXML serializes NutritionOrder to FHIR-conformant XML.
func (r NutritionOrder) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if start.Name.Local == "" {
		start.Name.Local = "NutritionOrder"
		start.Name.Space = fhirNamespace
	}
	if err := e.EncodeToken(start); err != nil {
		return err
	}

	if err := xmlEncodePrimitiveString(e, "id", r.Id, nil); err != nil {
		return err
	}
	if r.Meta != nil {
		if err := r.Meta.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "meta"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveString(e, "implicitRules", r.ImplicitRules, r.ImplicitRulesExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveString(e, "language", r.Language, r.LanguageExt); err != nil {
		return err
	}
	if r.Text != nil {
		if err := r.Text.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "text"}}); err != nil {
			return err
		}
	}
	for _, c := range r.Contained {
		if c != nil {
			if err := xmlEncodeContainedResource(e, c); err != nil {
				return err
			}
		}
	}
	for _, item := range r.Extension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "extension"}}); err != nil {
			return err
		}
	}
	for _, item := range r.ModifierExtension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "modifierExtension"}}); err != nil {
			return err
		}
	}
	for _, item := range r.Identifier {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "identifier"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveStringArray(e, "instantiatesCanonical", r.InstantiatesCanonical, r.InstantiatesCanonicalExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveStringArray(e, "instantiatesUri", r.InstantiatesUri, r.InstantiatesUriExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveStringArray(e, "instantiates", r.Instantiates, r.InstantiatesExt); err != nil {
		return err
	}
	for _, item := range r.BasedOn {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "basedOn"}}); err != nil {
			return err
		}
	}
	if r.GroupIdentifier != nil {
		if err := r.GroupIdentifier.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "groupIdentifier"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveCode(e, "status", r.Status, r.StatusExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveCode(e, "intent", r.Intent, r.IntentExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveCode(e, "priority", r.Priority, r.PriorityExt); err != nil {
		return err
	}
	if err := r.Subject.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "subject"}}); err != nil {
		return err
	}
	if r.Encounter != nil {
		if err := r.Encounter.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "encounter"}}); err != nil {
			return err
		}
	}
	for _, item := range r.SupportingInformation {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "supportingInformation"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveString(e, "dateTime", r.DateTime, r.DateTimeExt); err != nil {
		return err
	}
	if r.Orderer != nil {
		if err := r.Orderer.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "orderer"}}); err != nil {
			return err
		}
	}
	for _, item := range r.Performer {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "performer"}}); err != nil {
			return err
		}
	}
	for _, item := range r.AllergyIntolerance {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "allergyIntolerance"}}); err != nil {
			return err
		}
	}
	for _, item := range r.FoodPreferenceModifier {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "foodPreferenceModifier"}}); err != nil {
			return err
		}
	}
	for _, item := range r.ExcludeFoodModifier {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "excludeFoodModifier"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveBool(e, "outsideFoodAllowed", r.OutsideFoodAllowed, r.OutsideFoodAllowedExt); err != nil {
		return err
	}
	if r.OralDiet != nil {
		if err := r.OralDiet.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "oralDiet"}}); err != nil {
			return err
		}
	}
	for _, item := range r.Supplement {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "supplement"}}); err != nil {
			return err
		}
	}
	if r.EnteralFormula != nil {
		if err := r.EnteralFormula.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "enteralFormula"}}); err != nil {
			return err
		}
	}
	for _, item := range r.Note {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "note"}}); err != nil {
			return err
		}
	}

	return e.EncodeToken(start.End())
}

// UnmarshalXML deserializes NutritionOrder from FHIR-conformant XML.
func (r *NutritionOrder) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	for {
		tok, err := d.Token()
		if err != nil {
			return err
		}
		switch t := tok.(type) {
		case xml.StartElement:
			switch t.Name.Local {
			case "id":
				v, _, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Id = v
			case "meta":
				var v Meta
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Meta = &v
			case "implicitRules":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.ImplicitRules = v
				r.ImplicitRulesExt = ext
			case "language":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Language = v
				r.LanguageExt = ext
			case "text":
				var v Narrative
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Text = &v
			case "contained":
				res, err := xmlDecodeContainedResource(d, t)
				if err != nil {
					return err
				}
				if res != nil {
					r.Contained = append(r.Contained, res)
				}
			case "extension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Extension = append(r.Extension, v)
			case "modifierExtension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.ModifierExtension = append(r.ModifierExtension, v)
			case "identifier":
				var v Identifier
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Identifier = append(r.Identifier, v)
			case "instantiatesCanonical":
				v, _, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				if v != nil {
					r.InstantiatesCanonical = append(r.InstantiatesCanonical, *v)
				}
			case "instantiatesUri":
				v, _, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				if v != nil {
					r.InstantiatesUri = append(r.InstantiatesUri, *v)
				}
			case "instantiates":
				v, _, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				if v != nil {
					r.Instantiates = append(r.Instantiates, *v)
				}
			case "basedOn":
				var v Reference
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.BasedOn = append(r.BasedOn, v)
			case "groupIdentifier":
				var v Identifier
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.GroupIdentifier = &v
			case "status":
				v, ext, err := xmlDecodePrimitiveCode[RequestStatus](d, t)
				if err != nil {
					return err
				}
				r.Status = v
				r.StatusExt = ext
			case "intent":
				v, ext, err := xmlDecodePrimitiveCode[RequestIntent](d, t)
				if err != nil {
					return err
				}
				r.Intent = v
				r.IntentExt = ext
			case "priority":
				v, ext, err := xmlDecodePrimitiveCode[RequestPriority](d, t)
				if err != nil {
					return err
				}
				r.Priority = v
				r.PriorityExt = ext
			case "subject":
				if err := r.Subject.UnmarshalXML(d, t); err != nil {
					return err
				}
			case "encounter":
				var v Reference
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Encounter = &v
			case "supportingInformation":
				var v Reference
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.SupportingInformation = append(r.SupportingInformation, v)
			case "dateTime":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.DateTime = v
				r.DateTimeExt = ext
			case "orderer":
				var v Reference
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Orderer = &v
			case "performer":
				var v CodeableReference
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Performer = append(r.Performer, v)
			case "allergyIntolerance":
				var v Reference
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.AllergyIntolerance = append(r.AllergyIntolerance, v)
			case "foodPreferenceModifier":
				var v CodeableConcept
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.FoodPreferenceModifier = append(r.FoodPreferenceModifier, v)
			case "excludeFoodModifier":
				var v CodeableConcept
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.ExcludeFoodModifier = append(r.ExcludeFoodModifier, v)
			case "outsideFoodAllowed":
				v, ext, err := xmlDecodePrimitiveBool(d, t)
				if err != nil {
					return err
				}
				r.OutsideFoodAllowed = v
				r.OutsideFoodAllowedExt = ext
			case "oralDiet":
				var v NutritionOrderOralDiet
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.OralDiet = &v
			case "supplement":
				var v NutritionOrderSupplement
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Supplement = append(r.Supplement, v)
			case "enteralFormula":
				var v NutritionOrderEnteralFormula
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.EnteralFormula = &v
			case "note":
				var v Annotation
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Note = append(r.Note, v)
			default:
				if err := d.Skip(); err != nil {
					return err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// NutritionOrderEnteralFormula represents the NutritionOrder.enteralFormula backbone element.
// Enteral formula components
type NutritionOrderEnteralFormula struct {
	// Unique id for inter-element referencing
	Id *string `json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Type of enteral or infant formula
	BaseFormulaType *CodeableReference `json:"baseFormulaType,omitempty"`
	// Product or brand name of the enteral or infant formula
	BaseFormulaProductName *string `json:"baseFormulaProductName,omitempty"`
	// Intended type of device for the administration
	DeliveryDevice []CodeableReference `json:"deliveryDevice,omitempty"`
	// Components to add to the feeding
	Additive []NutritionOrderEnteralFormulaAdditive `json:"additive,omitempty"`
	// Amount of energy per specified volume that is required
	CaloricDensity *Quantity `json:"caloricDensity,omitempty"`
	// How the formula should enter the patient's gastrointestinal tract
	RouteOfAdministration *CodeableConcept `json:"routeOfAdministration,omitempty"`
	// Formula feeding instruction as structured data
	Administration []NutritionOrderEnteralFormulaAdministration `json:"administration,omitempty"`
	// Upper limit on formula volume per unit of time
	MaxVolumeToDeliver *Quantity `json:"maxVolumeToDeliver,omitempty"`
	// Formula feeding instructions expressed as text
	AdministrationInstruction *string `json:"administrationInstruction,omitempty"`
}

// MarshalXML serializes NutritionOrderEnteralFormula to FHIR-conformant XML.
func (b NutritionOrderEnteralFormula) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if start.Name.Local == "" {
		start.Name.Local = "NutritionOrder.enteralFormula"
	}
	if b.Id != nil {
		start.Attr = append(start.Attr, xml.Attr{Name: xml.Name{Local: "id"}, Value: *b.Id})
	}
	if err := e.EncodeToken(start); err != nil {
		return err
	}

	for _, item := range b.Extension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "extension"}}); err != nil {
			return err
		}
	}
	for _, item := range b.ModifierExtension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "modifierExtension"}}); err != nil {
			return err
		}
	}
	if b.BaseFormulaType != nil {
		if err := b.BaseFormulaType.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "baseFormulaType"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveString(e, "baseFormulaProductName", b.BaseFormulaProductName, nil); err != nil {
		return err
	}
	for _, item := range b.DeliveryDevice {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "deliveryDevice"}}); err != nil {
			return err
		}
	}
	for _, item := range b.Additive {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "additive"}}); err != nil {
			return err
		}
	}
	if b.CaloricDensity != nil {
		if err := b.CaloricDensity.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "caloricDensity"}}); err != nil {
			return err
		}
	}
	if b.RouteOfAdministration != nil {
		if err := b.RouteOfAdministration.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "routeOfAdministration"}}); err != nil {
			return err
		}
	}
	for _, item := range b.Administration {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "administration"}}); err != nil {
			return err
		}
	}
	if b.MaxVolumeToDeliver != nil {
		if err := b.MaxVolumeToDeliver.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "maxVolumeToDeliver"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveString(e, "administrationInstruction", b.AdministrationInstruction, nil); err != nil {
		return err
	}

	return e.EncodeToken(start.End())
}

// UnmarshalXML deserializes NutritionOrderEnteralFormula from FHIR-conformant XML.
func (r *NutritionOrderEnteralFormula) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	for _, attr := range start.Attr {
		if attr.Name.Local == "id" {
			v := attr.Value
			r.Id = &v
		}
	}

	for {
		tok, err := d.Token()
		if err != nil {
			return err
		}
		switch t := tok.(type) {
		case xml.StartElement:
			switch t.Name.Local {
			case "extension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Extension = append(r.Extension, v)
			case "modifierExtension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.ModifierExtension = append(r.ModifierExtension, v)
			case "baseFormulaType":
				var v CodeableReference
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.BaseFormulaType = &v
			case "baseFormulaProductName":
				v, _, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.BaseFormulaProductName = v
			case "deliveryDevice":
				var v CodeableReference
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.DeliveryDevice = append(r.DeliveryDevice, v)
			case "additive":
				var v NutritionOrderEnteralFormulaAdditive
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Additive = append(r.Additive, v)
			case "caloricDensity":
				var v Quantity
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.CaloricDensity = &v
			case "routeOfAdministration":
				var v CodeableConcept
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.RouteOfAdministration = &v
			case "administration":
				var v NutritionOrderEnteralFormulaAdministration
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Administration = append(r.Administration, v)
			case "maxVolumeToDeliver":
				var v Quantity
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.MaxVolumeToDeliver = &v
			case "administrationInstruction":
				v, _, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.AdministrationInstruction = v
			default:
				if err := d.Skip(); err != nil {
					return err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// NutritionOrderEnteralFormulaAdditive represents the NutritionOrder.enteralFormula.additive backbone element.
// Components to add to the feeding
type NutritionOrderEnteralFormulaAdditive struct {
	// Unique id for inter-element referencing
	Id *string `json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Type of modular component to add to the feeding
	Type *CodeableReference `json:"type,omitempty"`
	// Product or brand name of the modular additive
	ProductName *string `json:"productName,omitempty"`
	// Amount of additive to be given or mixed in
	Quantity *Quantity `json:"quantity,omitempty"`
}

// MarshalXML serializes NutritionOrderEnteralFormulaAdditive to FHIR-conformant XML.
func (b NutritionOrderEnteralFormulaAdditive) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if start.Name.Local == "" {
		start.Name.Local = "NutritionOrder.enteralFormula.additive"
	}
	if b.Id != nil {
		start.Attr = append(start.Attr, xml.Attr{Name: xml.Name{Local: "id"}, Value: *b.Id})
	}
	if err := e.EncodeToken(start); err != nil {
		return err
	}

	for _, item := range b.Extension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "extension"}}); err != nil {
			return err
		}
	}
	for _, item := range b.ModifierExtension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "modifierExtension"}}); err != nil {
			return err
		}
	}
	if b.Type != nil {
		if err := b.Type.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "type"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveString(e, "productName", b.ProductName, nil); err != nil {
		return err
	}
	if b.Quantity != nil {
		if err := b.Quantity.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "quantity"}}); err != nil {
			return err
		}
	}

	return e.EncodeToken(start.End())
}

// UnmarshalXML deserializes NutritionOrderEnteralFormulaAdditive from FHIR-conformant XML.
func (r *NutritionOrderEnteralFormulaAdditive) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	for _, attr := range start.Attr {
		if attr.Name.Local == "id" {
			v := attr.Value
			r.Id = &v
		}
	}

	for {
		tok, err := d.Token()
		if err != nil {
			return err
		}
		switch t := tok.(type) {
		case xml.StartElement:
			switch t.Name.Local {
			case "extension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Extension = append(r.Extension, v)
			case "modifierExtension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.ModifierExtension = append(r.ModifierExtension, v)
			case "type":
				var v CodeableReference
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Type = &v
			case "productName":
				v, _, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.ProductName = v
			case "quantity":
				var v Quantity
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Quantity = &v
			default:
				if err := d.Skip(); err != nil {
					return err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// NutritionOrderEnteralFormulaAdministration represents the NutritionOrder.enteralFormula.administration backbone element.
// Formula feeding instruction as structured data
type NutritionOrderEnteralFormulaAdministration struct {
	// Unique id for inter-element referencing
	Id *string `json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Scheduling information for enteral formula products
	Schedule *NutritionOrderEnteralFormulaAdministrationSchedule `json:"schedule,omitempty"`
	// The volume of formula to provide
	Quantity *Quantity `json:"quantity,omitempty"`
	// Speed with which the formula is provided per period of time
	RateQuantity *Quantity `json:"rateQuantity,omitempty"`
	// Speed with which the formula is provided per period of time
	RateRatio *Ratio `json:"rateRatio,omitempty"`
}

// MarshalXML serializes NutritionOrderEnteralFormulaAdministration to FHIR-conformant XML.
func (b NutritionOrderEnteralFormulaAdministration) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if start.Name.Local == "" {
		start.Name.Local = "NutritionOrder.enteralFormula.administration"
	}
	if b.Id != nil {
		start.Attr = append(start.Attr, xml.Attr{Name: xml.Name{Local: "id"}, Value: *b.Id})
	}
	if err := e.EncodeToken(start); err != nil {
		return err
	}

	for _, item := range b.Extension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "extension"}}); err != nil {
			return err
		}
	}
	for _, item := range b.ModifierExtension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "modifierExtension"}}); err != nil {
			return err
		}
	}
	if b.Schedule != nil {
		if err := b.Schedule.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "schedule"}}); err != nil {
			return err
		}
	}
	if b.Quantity != nil {
		if err := b.Quantity.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "quantity"}}); err != nil {
			return err
		}
	}
	if b.RateQuantity != nil {
		if err := b.RateQuantity.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "rateQuantity"}}); err != nil {
			return err
		}
	}
	if b.RateRatio != nil {
		if err := b.RateRatio.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "rateRatio"}}); err != nil {
			return err
		}
	}

	return e.EncodeToken(start.End())
}

// UnmarshalXML deserializes NutritionOrderEnteralFormulaAdministration from FHIR-conformant XML.
func (r *NutritionOrderEnteralFormulaAdministration) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	for _, attr := range start.Attr {
		if attr.Name.Local == "id" {
			v := attr.Value
			r.Id = &v
		}
	}

	for {
		tok, err := d.Token()
		if err != nil {
			return err
		}
		switch t := tok.(type) {
		case xml.StartElement:
			switch t.Name.Local {
			case "extension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Extension = append(r.Extension, v)
			case "modifierExtension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.ModifierExtension = append(r.ModifierExtension, v)
			case "schedule":
				var v NutritionOrderEnteralFormulaAdministrationSchedule
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Schedule = &v
			case "quantity":
				var v Quantity
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Quantity = &v
			case "rateQuantity":
				var v Quantity
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.RateQuantity = &v
			case "rateRatio":
				var v Ratio
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.RateRatio = &v
			default:
				if err := d.Skip(); err != nil {
					return err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// NutritionOrderEnteralFormulaAdministrationSchedule represents the NutritionOrder.enteralFormula.administration.schedule backbone element.
// Scheduling information for enteral formula products
type NutritionOrderEnteralFormulaAdministrationSchedule struct {
	// Unique id for inter-element referencing
	Id *string `json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Scheduled frequency of enteral formula
	Timing []Timing `json:"timing,omitempty"`
	// Take 'as needed'
	AsNeeded *bool `json:"asNeeded,omitempty"`
	// Take 'as needed' for x
	AsNeededFor *CodeableConcept `json:"asNeededFor,omitempty"`
}

// MarshalXML serializes NutritionOrderEnteralFormulaAdministrationSchedule to FHIR-conformant XML.
func (b NutritionOrderEnteralFormulaAdministrationSchedule) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if start.Name.Local == "" {
		start.Name.Local = "NutritionOrder.enteralFormula.administration.schedule"
	}
	if b.Id != nil {
		start.Attr = append(start.Attr, xml.Attr{Name: xml.Name{Local: "id"}, Value: *b.Id})
	}
	if err := e.EncodeToken(start); err != nil {
		return err
	}

	for _, item := range b.Extension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "extension"}}); err != nil {
			return err
		}
	}
	for _, item := range b.ModifierExtension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "modifierExtension"}}); err != nil {
			return err
		}
	}
	for _, item := range b.Timing {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "timing"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveBool(e, "asNeeded", b.AsNeeded, nil); err != nil {
		return err
	}
	if b.AsNeededFor != nil {
		if err := b.AsNeededFor.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "asNeededFor"}}); err != nil {
			return err
		}
	}

	return e.EncodeToken(start.End())
}

// UnmarshalXML deserializes NutritionOrderEnteralFormulaAdministrationSchedule from FHIR-conformant XML.
func (r *NutritionOrderEnteralFormulaAdministrationSchedule) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	for _, attr := range start.Attr {
		if attr.Name.Local == "id" {
			v := attr.Value
			r.Id = &v
		}
	}

	for {
		tok, err := d.Token()
		if err != nil {
			return err
		}
		switch t := tok.(type) {
		case xml.StartElement:
			switch t.Name.Local {
			case "extension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Extension = append(r.Extension, v)
			case "modifierExtension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.ModifierExtension = append(r.ModifierExtension, v)
			case "timing":
				var v Timing
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Timing = append(r.Timing, v)
			case "asNeeded":
				v, _, err := xmlDecodePrimitiveBool(d, t)
				if err != nil {
					return err
				}
				r.AsNeeded = v
			case "asNeededFor":
				var v CodeableConcept
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.AsNeededFor = &v
			default:
				if err := d.Skip(); err != nil {
					return err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// NutritionOrderOralDiet represents the NutritionOrder.oralDiet backbone element.
// Oral diet components
type NutritionOrderOralDiet struct {
	// Unique id for inter-element referencing
	Id *string `json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Type of oral diet or diet restrictions that describe what can be consumed orally
	Type []CodeableConcept `json:"type,omitempty"`
	// Scheduling information for oral diets
	Schedule *NutritionOrderOralDietSchedule `json:"schedule,omitempty"`
	// Required  nutrient modifications
	Nutrient []NutritionOrderOralDietNutrient `json:"nutrient,omitempty"`
	// Required  texture modifications
	Texture []NutritionOrderOralDietTexture `json:"texture,omitempty"`
	// The required consistency of fluids and liquids provided to the patient
	FluidConsistencyType []CodeableConcept `json:"fluidConsistencyType,omitempty"`
	// Instructions or additional information about the oral diet
	Instruction *string `json:"instruction,omitempty"`
}

// MarshalXML serializes NutritionOrderOralDiet to FHIR-conformant XML.
func (b NutritionOrderOralDiet) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if start.Name.Local == "" {
		start.Name.Local = "NutritionOrder.oralDiet"
	}
	if b.Id != nil {
		start.Attr = append(start.Attr, xml.Attr{Name: xml.Name{Local: "id"}, Value: *b.Id})
	}
	if err := e.EncodeToken(start); err != nil {
		return err
	}

	for _, item := range b.Extension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "extension"}}); err != nil {
			return err
		}
	}
	for _, item := range b.ModifierExtension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "modifierExtension"}}); err != nil {
			return err
		}
	}
	for _, item := range b.Type {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "type"}}); err != nil {
			return err
		}
	}
	if b.Schedule != nil {
		if err := b.Schedule.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "schedule"}}); err != nil {
			return err
		}
	}
	for _, item := range b.Nutrient {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "nutrient"}}); err != nil {
			return err
		}
	}
	for _, item := range b.Texture {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "texture"}}); err != nil {
			return err
		}
	}
	for _, item := range b.FluidConsistencyType {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "fluidConsistencyType"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveString(e, "instruction", b.Instruction, nil); err != nil {
		return err
	}

	return e.EncodeToken(start.End())
}

// UnmarshalXML deserializes NutritionOrderOralDiet from FHIR-conformant XML.
func (r *NutritionOrderOralDiet) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	for _, attr := range start.Attr {
		if attr.Name.Local == "id" {
			v := attr.Value
			r.Id = &v
		}
	}

	for {
		tok, err := d.Token()
		if err != nil {
			return err
		}
		switch t := tok.(type) {
		case xml.StartElement:
			switch t.Name.Local {
			case "extension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Extension = append(r.Extension, v)
			case "modifierExtension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.ModifierExtension = append(r.ModifierExtension, v)
			case "type":
				var v CodeableConcept
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Type = append(r.Type, v)
			case "schedule":
				var v NutritionOrderOralDietSchedule
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Schedule = &v
			case "nutrient":
				var v NutritionOrderOralDietNutrient
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Nutrient = append(r.Nutrient, v)
			case "texture":
				var v NutritionOrderOralDietTexture
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Texture = append(r.Texture, v)
			case "fluidConsistencyType":
				var v CodeableConcept
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.FluidConsistencyType = append(r.FluidConsistencyType, v)
			case "instruction":
				v, _, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Instruction = v
			default:
				if err := d.Skip(); err != nil {
					return err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// NutritionOrderOralDietNutrient represents the NutritionOrder.oralDiet.nutrient backbone element.
// Required  nutrient modifications
type NutritionOrderOralDietNutrient struct {
	// Unique id for inter-element referencing
	Id *string `json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Type of nutrient that is being modified
	Modifier *CodeableConcept `json:"modifier,omitempty"`
	// Quantity of the specified nutrient
	Amount *Quantity `json:"amount,omitempty"`
}

// MarshalXML serializes NutritionOrderOralDietNutrient to FHIR-conformant XML.
func (b NutritionOrderOralDietNutrient) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if start.Name.Local == "" {
		start.Name.Local = "NutritionOrder.oralDiet.nutrient"
	}
	if b.Id != nil {
		start.Attr = append(start.Attr, xml.Attr{Name: xml.Name{Local: "id"}, Value: *b.Id})
	}
	if err := e.EncodeToken(start); err != nil {
		return err
	}

	for _, item := range b.Extension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "extension"}}); err != nil {
			return err
		}
	}
	for _, item := range b.ModifierExtension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "modifierExtension"}}); err != nil {
			return err
		}
	}
	if b.Modifier != nil {
		if err := b.Modifier.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "modifier"}}); err != nil {
			return err
		}
	}
	if b.Amount != nil {
		if err := b.Amount.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "amount"}}); err != nil {
			return err
		}
	}

	return e.EncodeToken(start.End())
}

// UnmarshalXML deserializes NutritionOrderOralDietNutrient from FHIR-conformant XML.
func (r *NutritionOrderOralDietNutrient) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	for _, attr := range start.Attr {
		if attr.Name.Local == "id" {
			v := attr.Value
			r.Id = &v
		}
	}

	for {
		tok, err := d.Token()
		if err != nil {
			return err
		}
		switch t := tok.(type) {
		case xml.StartElement:
			switch t.Name.Local {
			case "extension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Extension = append(r.Extension, v)
			case "modifierExtension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.ModifierExtension = append(r.ModifierExtension, v)
			case "modifier":
				var v CodeableConcept
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Modifier = &v
			case "amount":
				var v Quantity
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Amount = &v
			default:
				if err := d.Skip(); err != nil {
					return err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// NutritionOrderOralDietSchedule represents the NutritionOrder.oralDiet.schedule backbone element.
// Scheduling information for oral diets
type NutritionOrderOralDietSchedule struct {
	// Unique id for inter-element referencing
	Id *string `json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Scheduled frequency of diet
	Timing []Timing `json:"timing,omitempty"`
	// Take 'as needed'
	AsNeeded *bool `json:"asNeeded,omitempty"`
	// Take 'as needed' for x
	AsNeededFor *CodeableConcept `json:"asNeededFor,omitempty"`
}

// MarshalXML serializes NutritionOrderOralDietSchedule to FHIR-conformant XML.
func (b NutritionOrderOralDietSchedule) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if start.Name.Local == "" {
		start.Name.Local = "NutritionOrder.oralDiet.schedule"
	}
	if b.Id != nil {
		start.Attr = append(start.Attr, xml.Attr{Name: xml.Name{Local: "id"}, Value: *b.Id})
	}
	if err := e.EncodeToken(start); err != nil {
		return err
	}

	for _, item := range b.Extension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "extension"}}); err != nil {
			return err
		}
	}
	for _, item := range b.ModifierExtension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "modifierExtension"}}); err != nil {
			return err
		}
	}
	for _, item := range b.Timing {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "timing"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveBool(e, "asNeeded", b.AsNeeded, nil); err != nil {
		return err
	}
	if b.AsNeededFor != nil {
		if err := b.AsNeededFor.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "asNeededFor"}}); err != nil {
			return err
		}
	}

	return e.EncodeToken(start.End())
}

// UnmarshalXML deserializes NutritionOrderOralDietSchedule from FHIR-conformant XML.
func (r *NutritionOrderOralDietSchedule) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	for _, attr := range start.Attr {
		if attr.Name.Local == "id" {
			v := attr.Value
			r.Id = &v
		}
	}

	for {
		tok, err := d.Token()
		if err != nil {
			return err
		}
		switch t := tok.(type) {
		case xml.StartElement:
			switch t.Name.Local {
			case "extension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Extension = append(r.Extension, v)
			case "modifierExtension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.ModifierExtension = append(r.ModifierExtension, v)
			case "timing":
				var v Timing
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Timing = append(r.Timing, v)
			case "asNeeded":
				v, _, err := xmlDecodePrimitiveBool(d, t)
				if err != nil {
					return err
				}
				r.AsNeeded = v
			case "asNeededFor":
				var v CodeableConcept
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.AsNeededFor = &v
			default:
				if err := d.Skip(); err != nil {
					return err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// NutritionOrderOralDietTexture represents the NutritionOrder.oralDiet.texture backbone element.
// Required  texture modifications
type NutritionOrderOralDietTexture struct {
	// Unique id for inter-element referencing
	Id *string `json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Code to indicate how to alter the texture of the foods, e.g. pureed
	Modifier *CodeableConcept `json:"modifier,omitempty"`
	// Concepts that are used to identify an entity that is ingested for nutritional purposes
	FoodType *CodeableConcept `json:"foodType,omitempty"`
}

// MarshalXML serializes NutritionOrderOralDietTexture to FHIR-conformant XML.
func (b NutritionOrderOralDietTexture) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if start.Name.Local == "" {
		start.Name.Local = "NutritionOrder.oralDiet.texture"
	}
	if b.Id != nil {
		start.Attr = append(start.Attr, xml.Attr{Name: xml.Name{Local: "id"}, Value: *b.Id})
	}
	if err := e.EncodeToken(start); err != nil {
		return err
	}

	for _, item := range b.Extension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "extension"}}); err != nil {
			return err
		}
	}
	for _, item := range b.ModifierExtension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "modifierExtension"}}); err != nil {
			return err
		}
	}
	if b.Modifier != nil {
		if err := b.Modifier.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "modifier"}}); err != nil {
			return err
		}
	}
	if b.FoodType != nil {
		if err := b.FoodType.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "foodType"}}); err != nil {
			return err
		}
	}

	return e.EncodeToken(start.End())
}

// UnmarshalXML deserializes NutritionOrderOralDietTexture from FHIR-conformant XML.
func (r *NutritionOrderOralDietTexture) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	for _, attr := range start.Attr {
		if attr.Name.Local == "id" {
			v := attr.Value
			r.Id = &v
		}
	}

	for {
		tok, err := d.Token()
		if err != nil {
			return err
		}
		switch t := tok.(type) {
		case xml.StartElement:
			switch t.Name.Local {
			case "extension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Extension = append(r.Extension, v)
			case "modifierExtension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.ModifierExtension = append(r.ModifierExtension, v)
			case "modifier":
				var v CodeableConcept
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Modifier = &v
			case "foodType":
				var v CodeableConcept
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.FoodType = &v
			default:
				if err := d.Skip(); err != nil {
					return err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// NutritionOrderSupplement represents the NutritionOrder.supplement backbone element.
// Supplement components
type NutritionOrderSupplement struct {
	// Unique id for inter-element referencing
	Id *string `json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Type of supplement product requested
	Type *CodeableReference `json:"type,omitempty"`
	// Product or brand name of the nutritional supplement
	ProductName *string `json:"productName,omitempty"`
	// Scheduling information for supplements
	Schedule *NutritionOrderSupplementSchedule `json:"schedule,omitempty"`
	// Amount of the nutritional supplement
	Quantity *Quantity `json:"quantity,omitempty"`
	// Instructions or additional information about the oral supplement
	Instruction *string `json:"instruction,omitempty"`
}

// MarshalXML serializes NutritionOrderSupplement to FHIR-conformant XML.
func (b NutritionOrderSupplement) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if start.Name.Local == "" {
		start.Name.Local = "NutritionOrder.supplement"
	}
	if b.Id != nil {
		start.Attr = append(start.Attr, xml.Attr{Name: xml.Name{Local: "id"}, Value: *b.Id})
	}
	if err := e.EncodeToken(start); err != nil {
		return err
	}

	for _, item := range b.Extension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "extension"}}); err != nil {
			return err
		}
	}
	for _, item := range b.ModifierExtension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "modifierExtension"}}); err != nil {
			return err
		}
	}
	if b.Type != nil {
		if err := b.Type.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "type"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveString(e, "productName", b.ProductName, nil); err != nil {
		return err
	}
	if b.Schedule != nil {
		if err := b.Schedule.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "schedule"}}); err != nil {
			return err
		}
	}
	if b.Quantity != nil {
		if err := b.Quantity.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "quantity"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveString(e, "instruction", b.Instruction, nil); err != nil {
		return err
	}

	return e.EncodeToken(start.End())
}

// UnmarshalXML deserializes NutritionOrderSupplement from FHIR-conformant XML.
func (r *NutritionOrderSupplement) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	for _, attr := range start.Attr {
		if attr.Name.Local == "id" {
			v := attr.Value
			r.Id = &v
		}
	}

	for {
		tok, err := d.Token()
		if err != nil {
			return err
		}
		switch t := tok.(type) {
		case xml.StartElement:
			switch t.Name.Local {
			case "extension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Extension = append(r.Extension, v)
			case "modifierExtension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.ModifierExtension = append(r.ModifierExtension, v)
			case "type":
				var v CodeableReference
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Type = &v
			case "productName":
				v, _, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.ProductName = v
			case "schedule":
				var v NutritionOrderSupplementSchedule
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Schedule = &v
			case "quantity":
				var v Quantity
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Quantity = &v
			case "instruction":
				v, _, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Instruction = v
			default:
				if err := d.Skip(); err != nil {
					return err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// NutritionOrderSupplementSchedule represents the NutritionOrder.supplement.schedule backbone element.
// Scheduling information for supplements
type NutritionOrderSupplementSchedule struct {
	// Unique id for inter-element referencing
	Id *string `json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Scheduled frequency of diet
	Timing []Timing `json:"timing,omitempty"`
	// Take 'as needed'
	AsNeeded *bool `json:"asNeeded,omitempty"`
	// Take 'as needed' for x
	AsNeededFor *CodeableConcept `json:"asNeededFor,omitempty"`
}

// MarshalXML serializes NutritionOrderSupplementSchedule to FHIR-conformant XML.
func (b NutritionOrderSupplementSchedule) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if start.Name.Local == "" {
		start.Name.Local = "NutritionOrder.supplement.schedule"
	}
	if b.Id != nil {
		start.Attr = append(start.Attr, xml.Attr{Name: xml.Name{Local: "id"}, Value: *b.Id})
	}
	if err := e.EncodeToken(start); err != nil {
		return err
	}

	for _, item := range b.Extension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "extension"}}); err != nil {
			return err
		}
	}
	for _, item := range b.ModifierExtension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "modifierExtension"}}); err != nil {
			return err
		}
	}
	for _, item := range b.Timing {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "timing"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveBool(e, "asNeeded", b.AsNeeded, nil); err != nil {
		return err
	}
	if b.AsNeededFor != nil {
		if err := b.AsNeededFor.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "asNeededFor"}}); err != nil {
			return err
		}
	}

	return e.EncodeToken(start.End())
}

// UnmarshalXML deserializes NutritionOrderSupplementSchedule from FHIR-conformant XML.
func (r *NutritionOrderSupplementSchedule) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	for _, attr := range start.Attr {
		if attr.Name.Local == "id" {
			v := attr.Value
			r.Id = &v
		}
	}

	for {
		tok, err := d.Token()
		if err != nil {
			return err
		}
		switch t := tok.(type) {
		case xml.StartElement:
			switch t.Name.Local {
			case "extension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Extension = append(r.Extension, v)
			case "modifierExtension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.ModifierExtension = append(r.ModifierExtension, v)
			case "timing":
				var v Timing
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Timing = append(r.Timing, v)
			case "asNeeded":
				v, _, err := xmlDecodePrimitiveBool(d, t)
				if err != nil {
					return err
				}
				r.AsNeeded = v
			case "asNeededFor":
				var v CodeableConcept
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.AsNeededFor = &v
			default:
				if err := d.Skip(); err != nil {
					return err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// =============================================================================
// NutritionOrder - Fluent Builder
// =============================================================================

// NutritionOrderBuilder provides a fluent API for constructing NutritionOrder resources.
type NutritionOrderBuilder struct {
	nutritionOrder *NutritionOrder
}

// NewNutritionOrderBuilder creates a new NutritionOrderBuilder.
func NewNutritionOrderBuilder() *NutritionOrderBuilder {
	return &NutritionOrderBuilder{
		nutritionOrder: &NutritionOrder{},
	}
}

// Build returns the constructed NutritionOrder resource.
func (b *NutritionOrderBuilder) Build() *NutritionOrder {
	return b.nutritionOrder
}

// SetId sets the Id field.
func (b *NutritionOrderBuilder) SetId(v string) *NutritionOrderBuilder {
	b.nutritionOrder.Id = &v
	return b
}

// SetMeta sets the Meta field.
func (b *NutritionOrderBuilder) SetMeta(v Meta) *NutritionOrderBuilder {
	b.nutritionOrder.Meta = &v
	return b
}

// SetImplicitRules sets the ImplicitRules field.
func (b *NutritionOrderBuilder) SetImplicitRules(v string) *NutritionOrderBuilder {
	b.nutritionOrder.ImplicitRules = &v
	return b
}

// SetLanguage sets the Language field.
func (b *NutritionOrderBuilder) SetLanguage(v string) *NutritionOrderBuilder {
	b.nutritionOrder.Language = &v
	return b
}

// SetText sets the Text field.
func (b *NutritionOrderBuilder) SetText(v Narrative) *NutritionOrderBuilder {
	b.nutritionOrder.Text = &v
	return b
}

// AddContained adds a Contained element.
func (b *NutritionOrderBuilder) AddContained(v Resource) *NutritionOrderBuilder {
	b.nutritionOrder.Contained = append(b.nutritionOrder.Contained, v)
	return b
}

// AddExtension adds a Extension element.
func (b *NutritionOrderBuilder) AddExtension(v Extension) *NutritionOrderBuilder {
	b.nutritionOrder.Extension = append(b.nutritionOrder.Extension, v)
	return b
}

// AddModifierExtension adds a ModifierExtension element.
func (b *NutritionOrderBuilder) AddModifierExtension(v Extension) *NutritionOrderBuilder {
	b.nutritionOrder.ModifierExtension = append(b.nutritionOrder.ModifierExtension, v)
	return b
}

// AddIdentifier adds a Identifier element.
func (b *NutritionOrderBuilder) AddIdentifier(v Identifier) *NutritionOrderBuilder {
	b.nutritionOrder.Identifier = append(b.nutritionOrder.Identifier, v)
	return b
}

// AddInstantiatesCanonical adds a InstantiatesCanonical element.
func (b *NutritionOrderBuilder) AddInstantiatesCanonical(v string) *NutritionOrderBuilder {
	b.nutritionOrder.InstantiatesCanonical = append(b.nutritionOrder.InstantiatesCanonical, v)
	return b
}

// AddInstantiatesUri adds a InstantiatesUri element.
func (b *NutritionOrderBuilder) AddInstantiatesUri(v string) *NutritionOrderBuilder {
	b.nutritionOrder.InstantiatesUri = append(b.nutritionOrder.InstantiatesUri, v)
	return b
}

// AddInstantiates adds a Instantiates element.
func (b *NutritionOrderBuilder) AddInstantiates(v string) *NutritionOrderBuilder {
	b.nutritionOrder.Instantiates = append(b.nutritionOrder.Instantiates, v)
	return b
}

// AddBasedOn adds a BasedOn element.
func (b *NutritionOrderBuilder) AddBasedOn(v Reference) *NutritionOrderBuilder {
	b.nutritionOrder.BasedOn = append(b.nutritionOrder.BasedOn, v)
	return b
}

// SetGroupIdentifier sets the GroupIdentifier field.
func (b *NutritionOrderBuilder) SetGroupIdentifier(v Identifier) *NutritionOrderBuilder {
	b.nutritionOrder.GroupIdentifier = &v
	return b
}

// SetStatus sets the Status field.
func (b *NutritionOrderBuilder) SetStatus(v RequestStatus) *NutritionOrderBuilder {
	b.nutritionOrder.Status = &v
	return b
}

// SetIntent sets the Intent field.
func (b *NutritionOrderBuilder) SetIntent(v RequestIntent) *NutritionOrderBuilder {
	b.nutritionOrder.Intent = &v
	return b
}

// SetPriority sets the Priority field.
func (b *NutritionOrderBuilder) SetPriority(v RequestPriority) *NutritionOrderBuilder {
	b.nutritionOrder.Priority = &v
	return b
}

// SetSubject sets the Subject field.
func (b *NutritionOrderBuilder) SetSubject(v Reference) *NutritionOrderBuilder {
	b.nutritionOrder.Subject = v
	return b
}

// SetEncounter sets the Encounter field.
func (b *NutritionOrderBuilder) SetEncounter(v Reference) *NutritionOrderBuilder {
	b.nutritionOrder.Encounter = &v
	return b
}

// AddSupportingInformation adds a SupportingInformation element.
func (b *NutritionOrderBuilder) AddSupportingInformation(v Reference) *NutritionOrderBuilder {
	b.nutritionOrder.SupportingInformation = append(b.nutritionOrder.SupportingInformation, v)
	return b
}

// SetDateTime sets the DateTime field.
func (b *NutritionOrderBuilder) SetDateTime(v string) *NutritionOrderBuilder {
	b.nutritionOrder.DateTime = &v
	return b
}

// SetOrderer sets the Orderer field.
func (b *NutritionOrderBuilder) SetOrderer(v Reference) *NutritionOrderBuilder {
	b.nutritionOrder.Orderer = &v
	return b
}

// AddPerformer adds a Performer element.
func (b *NutritionOrderBuilder) AddPerformer(v CodeableReference) *NutritionOrderBuilder {
	b.nutritionOrder.Performer = append(b.nutritionOrder.Performer, v)
	return b
}

// AddAllergyIntolerance adds a AllergyIntolerance element.
func (b *NutritionOrderBuilder) AddAllergyIntolerance(v Reference) *NutritionOrderBuilder {
	b.nutritionOrder.AllergyIntolerance = append(b.nutritionOrder.AllergyIntolerance, v)
	return b
}

// AddFoodPreferenceModifier adds a FoodPreferenceModifier element.
func (b *NutritionOrderBuilder) AddFoodPreferenceModifier(v CodeableConcept) *NutritionOrderBuilder {
	b.nutritionOrder.FoodPreferenceModifier = append(b.nutritionOrder.FoodPreferenceModifier, v)
	return b
}

// AddExcludeFoodModifier adds a ExcludeFoodModifier element.
func (b *NutritionOrderBuilder) AddExcludeFoodModifier(v CodeableConcept) *NutritionOrderBuilder {
	b.nutritionOrder.ExcludeFoodModifier = append(b.nutritionOrder.ExcludeFoodModifier, v)
	return b
}

// SetOutsideFoodAllowed sets the OutsideFoodAllowed field.
func (b *NutritionOrderBuilder) SetOutsideFoodAllowed(v bool) *NutritionOrderBuilder {
	b.nutritionOrder.OutsideFoodAllowed = &v
	return b
}

// SetOralDiet sets the OralDiet field.
func (b *NutritionOrderBuilder) SetOralDiet(v NutritionOrderOralDiet) *NutritionOrderBuilder {
	b.nutritionOrder.OralDiet = &v
	return b
}

// AddSupplement adds a Supplement element.
func (b *NutritionOrderBuilder) AddSupplement(v NutritionOrderSupplement) *NutritionOrderBuilder {
	b.nutritionOrder.Supplement = append(b.nutritionOrder.Supplement, v)
	return b
}

// SetEnteralFormula sets the EnteralFormula field.
func (b *NutritionOrderBuilder) SetEnteralFormula(v NutritionOrderEnteralFormula) *NutritionOrderBuilder {
	b.nutritionOrder.EnteralFormula = &v
	return b
}

// AddNote adds a Note element.
func (b *NutritionOrderBuilder) AddNote(v Annotation) *NutritionOrderBuilder {
	b.nutritionOrder.Note = append(b.nutritionOrder.Note, v)
	return b
}

// =============================================================================
// NutritionOrder - Functional Options
// =============================================================================

// NutritionOrderOption is a functional option for configuring a NutritionOrder.
type NutritionOrderOption func(*NutritionOrder)

// NewNutritionOrder creates a new NutritionOrder with the given options.
func NewNutritionOrder(opts ...NutritionOrderOption) *NutritionOrder {
	r := &NutritionOrder{}
	for _, opt := range opts {
		opt(r)
	}
	return r
}

// WithNutritionOrderId sets the Id field.
func WithNutritionOrderId(v string) NutritionOrderOption {
	return func(r *NutritionOrder) {
		r.Id = &v
	}
}

// WithNutritionOrderMeta sets the Meta field.
func WithNutritionOrderMeta(v Meta) NutritionOrderOption {
	return func(r *NutritionOrder) {
		r.Meta = &v
	}
}

// WithNutritionOrderImplicitRules sets the ImplicitRules field.
func WithNutritionOrderImplicitRules(v string) NutritionOrderOption {
	return func(r *NutritionOrder) {
		r.ImplicitRules = &v
	}
}

// WithNutritionOrderLanguage sets the Language field.
func WithNutritionOrderLanguage(v string) NutritionOrderOption {
	return func(r *NutritionOrder) {
		r.Language = &v
	}
}

// WithNutritionOrderText sets the Text field.
func WithNutritionOrderText(v Narrative) NutritionOrderOption {
	return func(r *NutritionOrder) {
		r.Text = &v
	}
}

// WithNutritionOrderContained adds a Contained to the NutritionOrder.
func WithNutritionOrderContained(v Resource) NutritionOrderOption {
	return func(r *NutritionOrder) {
		r.Contained = append(r.Contained, v)
	}
}

// WithNutritionOrderExtension adds a Extension to the NutritionOrder.
func WithNutritionOrderExtension(v Extension) NutritionOrderOption {
	return func(r *NutritionOrder) {
		r.Extension = append(r.Extension, v)
	}
}

// WithNutritionOrderModifierExtension adds a ModifierExtension to the NutritionOrder.
func WithNutritionOrderModifierExtension(v Extension) NutritionOrderOption {
	return func(r *NutritionOrder) {
		r.ModifierExtension = append(r.ModifierExtension, v)
	}
}

// WithNutritionOrderIdentifier adds a Identifier to the NutritionOrder.
func WithNutritionOrderIdentifier(v Identifier) NutritionOrderOption {
	return func(r *NutritionOrder) {
		r.Identifier = append(r.Identifier, v)
	}
}

// WithNutritionOrderInstantiatesCanonical adds a InstantiatesCanonical to the NutritionOrder.
func WithNutritionOrderInstantiatesCanonical(v string) NutritionOrderOption {
	return func(r *NutritionOrder) {
		r.InstantiatesCanonical = append(r.InstantiatesCanonical, v)
	}
}

// WithNutritionOrderInstantiatesUri adds a InstantiatesUri to the NutritionOrder.
func WithNutritionOrderInstantiatesUri(v string) NutritionOrderOption {
	return func(r *NutritionOrder) {
		r.InstantiatesUri = append(r.InstantiatesUri, v)
	}
}

// WithNutritionOrderInstantiates adds a Instantiates to the NutritionOrder.
func WithNutritionOrderInstantiates(v string) NutritionOrderOption {
	return func(r *NutritionOrder) {
		r.Instantiates = append(r.Instantiates, v)
	}
}

// WithNutritionOrderBasedOn adds a BasedOn to the NutritionOrder.
func WithNutritionOrderBasedOn(v Reference) NutritionOrderOption {
	return func(r *NutritionOrder) {
		r.BasedOn = append(r.BasedOn, v)
	}
}

// WithNutritionOrderGroupIdentifier sets the GroupIdentifier field.
func WithNutritionOrderGroupIdentifier(v Identifier) NutritionOrderOption {
	return func(r *NutritionOrder) {
		r.GroupIdentifier = &v
	}
}

// WithNutritionOrderStatus sets the Status field.
func WithNutritionOrderStatus(v RequestStatus) NutritionOrderOption {
	return func(r *NutritionOrder) {
		r.Status = &v
	}
}

// WithNutritionOrderIntent sets the Intent field.
func WithNutritionOrderIntent(v RequestIntent) NutritionOrderOption {
	return func(r *NutritionOrder) {
		r.Intent = &v
	}
}

// WithNutritionOrderPriority sets the Priority field.
func WithNutritionOrderPriority(v RequestPriority) NutritionOrderOption {
	return func(r *NutritionOrder) {
		r.Priority = &v
	}
}

// WithNutritionOrderSubject sets the Subject field.
func WithNutritionOrderSubject(v Reference) NutritionOrderOption {
	return func(r *NutritionOrder) {
		r.Subject = v
	}
}

// WithNutritionOrderEncounter sets the Encounter field.
func WithNutritionOrderEncounter(v Reference) NutritionOrderOption {
	return func(r *NutritionOrder) {
		r.Encounter = &v
	}
}

// WithNutritionOrderSupportingInformation adds a SupportingInformation to the NutritionOrder.
func WithNutritionOrderSupportingInformation(v Reference) NutritionOrderOption {
	return func(r *NutritionOrder) {
		r.SupportingInformation = append(r.SupportingInformation, v)
	}
}

// WithNutritionOrderDateTime sets the DateTime field.
func WithNutritionOrderDateTime(v string) NutritionOrderOption {
	return func(r *NutritionOrder) {
		r.DateTime = &v
	}
}

// WithNutritionOrderOrderer sets the Orderer field.
func WithNutritionOrderOrderer(v Reference) NutritionOrderOption {
	return func(r *NutritionOrder) {
		r.Orderer = &v
	}
}

// WithNutritionOrderPerformer adds a Performer to the NutritionOrder.
func WithNutritionOrderPerformer(v CodeableReference) NutritionOrderOption {
	return func(r *NutritionOrder) {
		r.Performer = append(r.Performer, v)
	}
}

// WithNutritionOrderAllergyIntolerance adds a AllergyIntolerance to the NutritionOrder.
func WithNutritionOrderAllergyIntolerance(v Reference) NutritionOrderOption {
	return func(r *NutritionOrder) {
		r.AllergyIntolerance = append(r.AllergyIntolerance, v)
	}
}

// WithNutritionOrderFoodPreferenceModifier adds a FoodPreferenceModifier to the NutritionOrder.
func WithNutritionOrderFoodPreferenceModifier(v CodeableConcept) NutritionOrderOption {
	return func(r *NutritionOrder) {
		r.FoodPreferenceModifier = append(r.FoodPreferenceModifier, v)
	}
}

// WithNutritionOrderExcludeFoodModifier adds a ExcludeFoodModifier to the NutritionOrder.
func WithNutritionOrderExcludeFoodModifier(v CodeableConcept) NutritionOrderOption {
	return func(r *NutritionOrder) {
		r.ExcludeFoodModifier = append(r.ExcludeFoodModifier, v)
	}
}

// WithNutritionOrderOutsideFoodAllowed sets the OutsideFoodAllowed field.
func WithNutritionOrderOutsideFoodAllowed(v bool) NutritionOrderOption {
	return func(r *NutritionOrder) {
		r.OutsideFoodAllowed = &v
	}
}

// WithNutritionOrderOralDiet sets the OralDiet field.
func WithNutritionOrderOralDiet(v NutritionOrderOralDiet) NutritionOrderOption {
	return func(r *NutritionOrder) {
		r.OralDiet = &v
	}
}

// WithNutritionOrderSupplement adds a Supplement to the NutritionOrder.
func WithNutritionOrderSupplement(v NutritionOrderSupplement) NutritionOrderOption {
	return func(r *NutritionOrder) {
		r.Supplement = append(r.Supplement, v)
	}
}

// WithNutritionOrderEnteralFormula sets the EnteralFormula field.
func WithNutritionOrderEnteralFormula(v NutritionOrderEnteralFormula) NutritionOrderOption {
	return func(r *NutritionOrder) {
		r.EnteralFormula = &v
	}
}

// WithNutritionOrderNote adds a Note to the NutritionOrder.
func WithNutritionOrderNote(v Annotation) NutritionOrderOption {
	return func(r *NutritionOrder) {
		r.Note = append(r.Note, v)
	}
}
