// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (consolidated resource)
// Package: r5

package r5

import (
	"encoding/xml"
)

// =============================================================================
// SubscriptionTopic Resource
// =============================================================================

// subscriptionTopicTypeMarker occupies no memory and serializes as the constant
// "SubscriptionTopic". It replaces a string field that a per-resource MarshalJSON had
// to overwrite on every call, which cost a second bytes.Buffer and json.Encoder
// per resource and, because a promoted MarshalJSON wins over the outer struct,
// silently dropped the fields of any type embedding this one.
//
// Nothing needs to set it: the zero value is correct, and GetResourceType()
// returns the same constant.
type subscriptionTopicTypeMarker struct{}

// MarshalJSON writes the resource type as a JSON string.
func (subscriptionTopicTypeMarker) MarshalJSON() ([]byte, error) {
	return []byte(`"SubscriptionTopic"`), nil
}

// UnmarshalJSON rejects a document whose resourceType names a different resource.
//
// This used to accept and discard whatever the document carried, on the grounds
// that UnmarshalResource validates the type during dispatch. It does — but only on
// that path. json.Unmarshal(data, &patient) does not go through the dispatcher, and
// it is the ordinary way to decode when the type is already known, so a
// Practitioner document decoded into a Patient was accepted in silence and written
// back out as a Patient.
//
// An absent or null resourceType is still accepted; see checkResourceType.
func (*subscriptionTopicTypeMarker) UnmarshalJSON(data []byte) error {
	return checkResourceType(data, "SubscriptionTopic")
}

// SubscriptionTopic represents FHIR SubscriptionTopic.
type SubscriptionTopic struct {
	// FHIR resource type. Emitted automatically; see subscriptionTopicTypeMarker.
	ResourceType subscriptionTopicTypeMarker `json:"resourceType"`
	// Logical id of this artifact
	Id *string `json:"id,omitempty"`
	// Metadata about the resource
	Meta *Meta `json:"meta,omitempty"`
	// A set of rules under which this content was created
	ImplicitRules *string `json:"implicitRules,omitempty"`
	// Extension for ImplicitRules
	ImplicitRulesExt *Element `json:"_implicitRules,omitempty"`
	// Language of the resource content
	Language *string `json:"language,omitempty"`
	// Extension for Language
	LanguageExt *Element `json:"_language,omitempty"`
	// Text summary of the resource, for human interpretation
	Text *Narrative `json:"text,omitempty"`
	// Contained, inline Resources
	Contained ContainedList `json:"contained,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Canonical identifier for this subscription topic, represented as an absolute URI (globally unique)
	Url *string `json:"url,omitempty"`
	// Extension for Url
	UrlExt *Element `json:"_url,omitempty"`
	// Business identifier for subscription topic
	Identifier []Identifier `json:"identifier,omitempty"`
	// Business version of the subscription topic
	Version *string `json:"version,omitempty"`
	// Extension for Version
	VersionExt *Element `json:"_version,omitempty"`
	// How to compare versions
	VersionAlgorithmString *string `json:"versionAlgorithmString,omitempty"`
	// Extension for VersionAlgorithmString
	VersionAlgorithmStringExt *Element `json:"_versionAlgorithmString,omitempty"`
	// How to compare versions
	VersionAlgorithmCoding *Coding `json:"versionAlgorithmCoding,omitempty"`
	// Name for this subscription topic (computer friendly)
	Name *string `json:"name,omitempty"`
	// Extension for Name
	NameExt *Element `json:"_name,omitempty"`
	// Name for this subscription topic (human friendly)
	Title *string `json:"title,omitempty"`
	// Extension for Title
	TitleExt *Element `json:"_title,omitempty"`
	// Based on FHIR protocol or definition
	DerivedFrom []*string `json:"derivedFrom,omitempty"`
	// Extension for DerivedFrom
	DerivedFromExt []*Element `json:"_derivedFrom,omitempty"`
	// draft | active | retired | unknown
	Status *PublicationStatus `json:"status,omitempty"`
	// Extension for Status
	StatusExt *Element `json:"_status,omitempty"`
	// If for testing purposes, not real usage
	Experimental *bool `json:"experimental,omitempty"`
	// Extension for Experimental
	ExperimentalExt *Element `json:"_experimental,omitempty"`
	// Date status first applied
	Date *string `json:"date,omitempty"`
	// Extension for Date
	DateExt *Element `json:"_date,omitempty"`
	// The name of the individual or organization that published the SubscriptionTopic
	Publisher *string `json:"publisher,omitempty"`
	// Extension for Publisher
	PublisherExt *Element `json:"_publisher,omitempty"`
	// Contact details for the publisher
	Contact []ContactDetail `json:"contact,omitempty"`
	// Natural language description of the SubscriptionTopic
	Description *string `json:"description,omitempty"`
	// Extension for Description
	DescriptionExt *Element `json:"_description,omitempty"`
	// Content intends to support these contexts
	UseContext []UsageContext `json:"useContext,omitempty"`
	// Intended jurisdiction of the SubscriptionTopic (if applicable)
	Jurisdiction []CodeableConcept `json:"jurisdiction,omitempty"`
	// Why this SubscriptionTopic is defined
	Purpose *string `json:"purpose,omitempty"`
	// Extension for Purpose
	PurposeExt *Element `json:"_purpose,omitempty"`
	// Use and/or publishing restrictions
	Copyright *string `json:"copyright,omitempty"`
	// Extension for Copyright
	CopyrightExt *Element `json:"_copyright,omitempty"`
	// Copyright holder and year(s)
	CopyrightLabel *string `json:"copyrightLabel,omitempty"`
	// Extension for CopyrightLabel
	CopyrightLabelExt *Element `json:"_copyrightLabel,omitempty"`
	// When SubscriptionTopic is/was approved by publisher
	ApprovalDate *string `json:"approvalDate,omitempty"`
	// Extension for ApprovalDate
	ApprovalDateExt *Element `json:"_approvalDate,omitempty"`
	// Date the Subscription Topic was last reviewed by the publisher
	LastReviewDate *string `json:"lastReviewDate,omitempty"`
	// Extension for LastReviewDate
	LastReviewDateExt *Element `json:"_lastReviewDate,omitempty"`
	// The effective date range for the SubscriptionTopic
	EffectivePeriod *Period `json:"effectivePeriod,omitempty"`
	// Definition of a resource-based trigger for the subscription topic
	ResourceTrigger []SubscriptionTopicResourceTrigger `json:"resourceTrigger,omitempty"`
	// Event definitions the SubscriptionTopic
	EventTrigger []SubscriptionTopicEventTrigger `json:"eventTrigger,omitempty"`
	// Properties by which a Subscription can filter notifications from the SubscriptionTopic
	CanFilterBy []SubscriptionTopicCanFilterBy `json:"canFilterBy,omitempty"`
	// Properties for describing the shape of notifications generated by this topic
	NotificationShape []SubscriptionTopicNotificationShape `json:"notificationShape,omitempty"`
}

// GetResourceType returns the FHIR resource type.
func (r *SubscriptionTopic) GetResourceType() string {
	return "SubscriptionTopic"
}

// GetId returns the resource's logical ID.
func (r *SubscriptionTopic) GetId() *string {
	return r.Id
}

// SetId sets the resource's logical ID.
func (r *SubscriptionTopic) SetId(id string) {
	r.Id = &id
}

// GetMeta returns the resource's Meta element.
func (r *SubscriptionTopic) GetMeta() *Meta {
	return r.Meta
}

// SetMeta sets the resource's Meta element.
func (r *SubscriptionTopic) SetMeta(m *Meta) {
	r.Meta = m
}

// GetText returns the resource's narrative text.
func (r *SubscriptionTopic) GetText() *Narrative {
	return r.Text
}

// SetText sets the resource's narrative text.
func (r *SubscriptionTopic) SetText(t *Narrative) {
	r.Text = t
}

// GetContained returns the resource's contained resources.
func (r *SubscriptionTopic) GetContained() []Resource {
	return r.Contained
}

// GetExtension returns the resource's extensions.
func (r *SubscriptionTopic) GetExtension() []Extension {
	return r.Extension
}

// GetExtensionByURL returns the first extension with the given URL, or nil.
//
// The result points into the slice, so writing through it edits the resource.
func (r *SubscriptionTopic) GetExtensionByURL(url string) *Extension {
	return ExtensionByURL(r.Extension, url)
}

// GetExtensionsByURL returns every extension with the given URL. A URL may repeat
// where the extension's cardinality allows it.
func (r *SubscriptionTopic) GetExtensionsByURL(url string) []*Extension {
	return ExtensionsByURL(r.Extension, url)
}

// HasExtensionByURL reports whether any extension carries the given URL, which
// is the whole meaning of the extensions that have no value.
func (r *SubscriptionTopic) HasExtensionByURL(url string) bool {
	return HasExtensionByURL(r.Extension, url)
}

// GetModifierExtension returns the resource's modifier extensions.
func (r *SubscriptionTopic) GetModifierExtension() []Extension {
	return r.ModifierExtension
}

// GetModifierExtensionByURL returns the first modifier extension with the given
// URL, or nil.
//
// Kept separate from GetExtensionByURL on purpose: a modifier extension changes the
// meaning of the element it is on, so a reader that cannot recognize one must not
// process the element at all. Folding the two searches together would hide that.
func (r *SubscriptionTopic) GetModifierExtensionByURL(url string) *Extension {
	return ExtensionByURL(r.ModifierExtension, url)
}

// MarshalXML serializes SubscriptionTopic to FHIR-conformant XML.
func (r SubscriptionTopic) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if start.Name.Local == "" {
		start.Name.Local = "SubscriptionTopic"
		start.Name.Space = fhirNamespace
	}
	if err := e.EncodeToken(start); err != nil {
		return err
	}

	if err := xmlEncodePrimitiveString(e, "id", r.Id, nil); err != nil {
		return err
	}
	if r.Meta != nil {
		if err := r.Meta.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "meta"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveString(e, "implicitRules", r.ImplicitRules, r.ImplicitRulesExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveString(e, "language", r.Language, r.LanguageExt); err != nil {
		return err
	}
	if r.Text != nil {
		if err := r.Text.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "text"}}); err != nil {
			return err
		}
	}
	for _, c := range r.Contained {
		if c != nil {
			if err := xmlEncodeContainedResource(e, c); err != nil {
				return err
			}
		}
	}
	for _, item := range r.Extension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "extension"}}); err != nil {
			return err
		}
	}
	for _, item := range r.ModifierExtension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "modifierExtension"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveString(e, "url", r.Url, r.UrlExt); err != nil {
		return err
	}
	for _, item := range r.Identifier {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "identifier"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveString(e, "version", r.Version, r.VersionExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveString(e, "versionAlgorithmString", r.VersionAlgorithmString, nil); err != nil {
		return err
	}
	if r.VersionAlgorithmCoding != nil {
		if err := r.VersionAlgorithmCoding.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "versionAlgorithmCoding"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveString(e, "name", r.Name, r.NameExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveString(e, "title", r.Title, r.TitleExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveStringArray(e, "derivedFrom", r.DerivedFrom, r.DerivedFromExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveCode(e, "status", r.Status, r.StatusExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveBool(e, "experimental", r.Experimental, r.ExperimentalExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveString(e, "date", r.Date, r.DateExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveString(e, "publisher", r.Publisher, r.PublisherExt); err != nil {
		return err
	}
	for _, item := range r.Contact {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "contact"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveString(e, "description", r.Description, r.DescriptionExt); err != nil {
		return err
	}
	for _, item := range r.UseContext {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "useContext"}}); err != nil {
			return err
		}
	}
	for _, item := range r.Jurisdiction {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "jurisdiction"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveString(e, "purpose", r.Purpose, r.PurposeExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveString(e, "copyright", r.Copyright, r.CopyrightExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveString(e, "copyrightLabel", r.CopyrightLabel, r.CopyrightLabelExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveString(e, "approvalDate", r.ApprovalDate, r.ApprovalDateExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveString(e, "lastReviewDate", r.LastReviewDate, r.LastReviewDateExt); err != nil {
		return err
	}
	if r.EffectivePeriod != nil {
		if err := r.EffectivePeriod.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "effectivePeriod"}}); err != nil {
			return err
		}
	}
	for _, item := range r.ResourceTrigger {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "resourceTrigger"}}); err != nil {
			return err
		}
	}
	for _, item := range r.EventTrigger {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "eventTrigger"}}); err != nil {
			return err
		}
	}
	for _, item := range r.CanFilterBy {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "canFilterBy"}}); err != nil {
			return err
		}
	}
	for _, item := range r.NotificationShape {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "notificationShape"}}); err != nil {
			return err
		}
	}

	return e.EncodeToken(start.End())
}

// UnmarshalXML deserializes SubscriptionTopic from FHIR-conformant XML.
func (r *SubscriptionTopic) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	for {
		tok, err := d.Token()
		if err != nil {
			return err
		}
		switch t := tok.(type) {
		case xml.StartElement:
			switch t.Name.Local {
			case "id":
				v, _, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Id = v
			case "meta":
				var v Meta
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Meta = &v
			case "implicitRules":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.ImplicitRules = v
				r.ImplicitRulesExt = ext
			case "language":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Language = v
				r.LanguageExt = ext
			case "text":
				var v Narrative
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Text = &v
			case "contained":
				res, err := xmlDecodeContainedResource(d, t)
				if err != nil {
					return err
				}
				if res != nil {
					r.Contained = append(r.Contained, res)
				}
			case "extension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Extension = append(r.Extension, v)
			case "modifierExtension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.ModifierExtension = append(r.ModifierExtension, v)
			case "url":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Url = v
				r.UrlExt = ext
			case "identifier":
				var v Identifier
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Identifier = append(r.Identifier, v)
			case "version":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Version = v
				r.VersionExt = ext
			case "versionAlgorithmString":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.VersionAlgorithmString = v
				_ = ext
			case "versionAlgorithmCoding":
				var v Coding
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.VersionAlgorithmCoding = &v
			case "name":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Name = v
				r.NameExt = ext
			case "title":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Title = v
				r.TitleExt = ext
			case "derivedFrom":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				// nil is meaningful here: it is a positional slot with no value.
				r.DerivedFrom = append(r.DerivedFrom, v)
				// The slots are parallel by position: fill the gap, then append.
				if ext != nil {
					for len(r.DerivedFromExt) < len(r.DerivedFrom)-1 {
						r.DerivedFromExt = append(r.DerivedFromExt, nil)
					}
					r.DerivedFromExt = append(r.DerivedFromExt, ext)
				}
			case "status":
				v, ext, err := xmlDecodePrimitiveCode[PublicationStatus](d, t)
				if err != nil {
					return err
				}
				r.Status = v
				r.StatusExt = ext
			case "experimental":
				v, ext, err := xmlDecodePrimitiveBool(d, t)
				if err != nil {
					return err
				}
				r.Experimental = v
				r.ExperimentalExt = ext
			case "date":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Date = v
				r.DateExt = ext
			case "publisher":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Publisher = v
				r.PublisherExt = ext
			case "contact":
				var v ContactDetail
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Contact = append(r.Contact, v)
			case "description":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Description = v
				r.DescriptionExt = ext
			case "useContext":
				var v UsageContext
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.UseContext = append(r.UseContext, v)
			case "jurisdiction":
				var v CodeableConcept
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Jurisdiction = append(r.Jurisdiction, v)
			case "purpose":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Purpose = v
				r.PurposeExt = ext
			case "copyright":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Copyright = v
				r.CopyrightExt = ext
			case "copyrightLabel":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.CopyrightLabel = v
				r.CopyrightLabelExt = ext
			case "approvalDate":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.ApprovalDate = v
				r.ApprovalDateExt = ext
			case "lastReviewDate":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.LastReviewDate = v
				r.LastReviewDateExt = ext
			case "effectivePeriod":
				var v Period
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.EffectivePeriod = &v
			case "resourceTrigger":
				var v SubscriptionTopicResourceTrigger
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.ResourceTrigger = append(r.ResourceTrigger, v)
			case "eventTrigger":
				var v SubscriptionTopicEventTrigger
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.EventTrigger = append(r.EventTrigger, v)
			case "canFilterBy":
				var v SubscriptionTopicCanFilterBy
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.CanFilterBy = append(r.CanFilterBy, v)
			case "notificationShape":
				var v SubscriptionTopicNotificationShape
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.NotificationShape = append(r.NotificationShape, v)
			default:
				if err := d.Skip(); err != nil {
					return err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// SubscriptionTopicCanFilterBy represents the SubscriptionTopic.canFilterBy backbone element.
// Properties by which a Subscription can filter notifications from the SubscriptionTopic
type SubscriptionTopicCanFilterBy struct {
	// Unique id for inter-element referencing
	Id *string `json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Description of this filter parameter
	Description *string `json:"description,omitempty"`
	// Extension for Description
	DescriptionExt *Element `json:"_description,omitempty"`
	// URL of the triggering Resource that this filter applies to
	Resource *string `json:"resource,omitempty"`
	// Extension for Resource
	ResourceExt *Element `json:"_resource,omitempty"`
	// Human-readable and computation-friendly name for a filter parameter usable by subscriptions on this topic, via Subscription.filterBy.filterParameter
	FilterParameter *string `json:"filterParameter,omitempty"`
	// Extension for FilterParameter
	FilterParameterExt *Element `json:"_filterParameter,omitempty"`
	// Canonical URL for a filterParameter definition
	FilterDefinition *string `json:"filterDefinition,omitempty"`
	// Extension for FilterDefinition
	FilterDefinitionExt *Element `json:"_filterDefinition,omitempty"`
	// eq | ne | gt | lt | ge | le | sa | eb | ap
	Comparator []*SearchComparator `json:"comparator,omitempty"`
	// Extension for Comparator
	ComparatorExt []*Element `json:"_comparator,omitempty"`
	// missing | exact | contains | not | text | in | not-in | below | above | type | identifier | of-type | code-text | text-advanced | iterate
	Modifier []*SearchModifierCode `json:"modifier,omitempty"`
	// Extension for Modifier
	ModifierExt []*Element `json:"_modifier,omitempty"`
}

// GetExtensionByURL returns the first extension with the given URL, or nil.
//
// The result points into the slice, so writing through it edits the value.
func (r *SubscriptionTopicCanFilterBy) GetExtensionByURL(url string) *Extension {
	return ExtensionByURL(r.Extension, url)
}

// GetExtensionsByURL returns every extension with the given URL. A URL may repeat
// where the extension's cardinality allows it.
func (r *SubscriptionTopicCanFilterBy) GetExtensionsByURL(url string) []*Extension {
	return ExtensionsByURL(r.Extension, url)
}

// HasExtensionByURL reports whether any extension carries the given URL, which
// is the whole meaning of the extensions that have no value.
func (r *SubscriptionTopicCanFilterBy) HasExtensionByURL(url string) bool {
	return HasExtensionByURL(r.Extension, url)
}

// GetModifierExtensionByURL returns the first modifier extension with the given
// URL, or nil. Kept separate from GetExtensionByURL because a modifier extension
// changes the meaning of the element it is on.
func (r *SubscriptionTopicCanFilterBy) GetModifierExtensionByURL(url string) *Extension {
	return ExtensionByURL(r.ModifierExtension, url)
}

// MarshalXML serializes SubscriptionTopicCanFilterBy to FHIR-conformant XML.
func (b SubscriptionTopicCanFilterBy) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if start.Name.Local == "" {
		start.Name.Local = "SubscriptionTopic.canFilterBy"
	}
	if b.Id != nil {
		start.Attr = append(start.Attr, xml.Attr{Name: xml.Name{Local: "id"}, Value: *b.Id})
	}
	if err := e.EncodeToken(start); err != nil {
		return err
	}

	for _, item := range b.Extension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "extension"}}); err != nil {
			return err
		}
	}
	for _, item := range b.ModifierExtension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "modifierExtension"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveString(e, "description", b.Description, b.DescriptionExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveString(e, "resource", b.Resource, b.ResourceExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveString(e, "filterParameter", b.FilterParameter, b.FilterParameterExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveString(e, "filterDefinition", b.FilterDefinition, b.FilterDefinitionExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveCodeArray(e, "comparator", b.Comparator, b.ComparatorExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveCodeArray(e, "modifier", b.Modifier, b.ModifierExt); err != nil {
		return err
	}

	return e.EncodeToken(start.End())
}

// UnmarshalXML deserializes SubscriptionTopicCanFilterBy from FHIR-conformant XML.
func (r *SubscriptionTopicCanFilterBy) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	for _, attr := range start.Attr {
		if attr.Name.Local == "id" {
			v := attr.Value
			r.Id = &v
		}
	}

	for {
		tok, err := d.Token()
		if err != nil {
			return err
		}
		switch t := tok.(type) {
		case xml.StartElement:
			switch t.Name.Local {
			case "extension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Extension = append(r.Extension, v)
			case "modifierExtension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.ModifierExtension = append(r.ModifierExtension, v)
			case "description":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Description = v
				r.DescriptionExt = ext
			case "resource":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Resource = v
				r.ResourceExt = ext
			case "filterParameter":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.FilterParameter = v
				r.FilterParameterExt = ext
			case "filterDefinition":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.FilterDefinition = v
				r.FilterDefinitionExt = ext
			case "comparator":
				v, ext, err := xmlDecodePrimitiveCode[SearchComparator](d, t)
				if err != nil {
					return err
				}
				// nil is meaningful here: it is a positional slot with no value.
				r.Comparator = append(r.Comparator, v)
				// The slots are parallel by position: fill the gap, then append.
				if ext != nil {
					for len(r.ComparatorExt) < len(r.Comparator)-1 {
						r.ComparatorExt = append(r.ComparatorExt, nil)
					}
					r.ComparatorExt = append(r.ComparatorExt, ext)
				}
			case "modifier":
				v, ext, err := xmlDecodePrimitiveCode[SearchModifierCode](d, t)
				if err != nil {
					return err
				}
				// nil is meaningful here: it is a positional slot with no value.
				r.Modifier = append(r.Modifier, v)
				// The slots are parallel by position: fill the gap, then append.
				if ext != nil {
					for len(r.ModifierExt) < len(r.Modifier)-1 {
						r.ModifierExt = append(r.ModifierExt, nil)
					}
					r.ModifierExt = append(r.ModifierExt, ext)
				}
			default:
				if err := d.Skip(); err != nil {
					return err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// SubscriptionTopicEventTrigger represents the SubscriptionTopic.eventTrigger backbone element.
// Event definitions the SubscriptionTopic
type SubscriptionTopicEventTrigger struct {
	// Unique id for inter-element referencing
	Id *string `json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Text representation of the event trigger
	Description *string `json:"description,omitempty"`
	// Extension for Description
	DescriptionExt *Element `json:"_description,omitempty"`
	// Event which can trigger a notification from the SubscriptionTopic
	Event *CodeableConcept `json:"event,omitempty"`
	// Data Type or Resource (reference to definition) for this trigger definition
	Resource *string `json:"resource,omitempty"`
	// Extension for Resource
	ResourceExt *Element `json:"_resource,omitempty"`
}

// GetExtensionByURL returns the first extension with the given URL, or nil.
//
// The result points into the slice, so writing through it edits the value.
func (r *SubscriptionTopicEventTrigger) GetExtensionByURL(url string) *Extension {
	return ExtensionByURL(r.Extension, url)
}

// GetExtensionsByURL returns every extension with the given URL. A URL may repeat
// where the extension's cardinality allows it.
func (r *SubscriptionTopicEventTrigger) GetExtensionsByURL(url string) []*Extension {
	return ExtensionsByURL(r.Extension, url)
}

// HasExtensionByURL reports whether any extension carries the given URL, which
// is the whole meaning of the extensions that have no value.
func (r *SubscriptionTopicEventTrigger) HasExtensionByURL(url string) bool {
	return HasExtensionByURL(r.Extension, url)
}

// GetModifierExtensionByURL returns the first modifier extension with the given
// URL, or nil. Kept separate from GetExtensionByURL because a modifier extension
// changes the meaning of the element it is on.
func (r *SubscriptionTopicEventTrigger) GetModifierExtensionByURL(url string) *Extension {
	return ExtensionByURL(r.ModifierExtension, url)
}

// MarshalXML serializes SubscriptionTopicEventTrigger to FHIR-conformant XML.
func (b SubscriptionTopicEventTrigger) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if start.Name.Local == "" {
		start.Name.Local = "SubscriptionTopic.eventTrigger"
	}
	if b.Id != nil {
		start.Attr = append(start.Attr, xml.Attr{Name: xml.Name{Local: "id"}, Value: *b.Id})
	}
	if err := e.EncodeToken(start); err != nil {
		return err
	}

	for _, item := range b.Extension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "extension"}}); err != nil {
			return err
		}
	}
	for _, item := range b.ModifierExtension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "modifierExtension"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveString(e, "description", b.Description, b.DescriptionExt); err != nil {
		return err
	}
	if b.Event != nil {
		if err := b.Event.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "event"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveString(e, "resource", b.Resource, b.ResourceExt); err != nil {
		return err
	}

	return e.EncodeToken(start.End())
}

// UnmarshalXML deserializes SubscriptionTopicEventTrigger from FHIR-conformant XML.
func (r *SubscriptionTopicEventTrigger) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	for _, attr := range start.Attr {
		if attr.Name.Local == "id" {
			v := attr.Value
			r.Id = &v
		}
	}

	for {
		tok, err := d.Token()
		if err != nil {
			return err
		}
		switch t := tok.(type) {
		case xml.StartElement:
			switch t.Name.Local {
			case "extension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Extension = append(r.Extension, v)
			case "modifierExtension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.ModifierExtension = append(r.ModifierExtension, v)
			case "description":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Description = v
				r.DescriptionExt = ext
			case "event":
				var v CodeableConcept
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Event = &v
			case "resource":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Resource = v
				r.ResourceExt = ext
			default:
				if err := d.Skip(); err != nil {
					return err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// SubscriptionTopicNotificationShape represents the SubscriptionTopic.notificationShape backbone element.
// Properties for describing the shape of notifications generated by this topic
type SubscriptionTopicNotificationShape struct {
	// Unique id for inter-element referencing
	Id *string `json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// URL of the Resource that is the focus (main) resource in a notification shape
	Resource *string `json:"resource,omitempty"`
	// Extension for Resource
	ResourceExt *Element `json:"_resource,omitempty"`
	// Include directives, rooted in the resource for this shape
	Include []*string `json:"include,omitempty"`
	// Extension for Include
	IncludeExt []*Element `json:"_include,omitempty"`
	// Reverse include directives, rooted in the resource for this shape
	RevInclude []*string `json:"revInclude,omitempty"`
	// Extension for RevInclude
	RevIncludeExt []*Element `json:"_revInclude,omitempty"`
}

// GetExtensionByURL returns the first extension with the given URL, or nil.
//
// The result points into the slice, so writing through it edits the value.
func (r *SubscriptionTopicNotificationShape) GetExtensionByURL(url string) *Extension {
	return ExtensionByURL(r.Extension, url)
}

// GetExtensionsByURL returns every extension with the given URL. A URL may repeat
// where the extension's cardinality allows it.
func (r *SubscriptionTopicNotificationShape) GetExtensionsByURL(url string) []*Extension {
	return ExtensionsByURL(r.Extension, url)
}

// HasExtensionByURL reports whether any extension carries the given URL, which
// is the whole meaning of the extensions that have no value.
func (r *SubscriptionTopicNotificationShape) HasExtensionByURL(url string) bool {
	return HasExtensionByURL(r.Extension, url)
}

// GetModifierExtensionByURL returns the first modifier extension with the given
// URL, or nil. Kept separate from GetExtensionByURL because a modifier extension
// changes the meaning of the element it is on.
func (r *SubscriptionTopicNotificationShape) GetModifierExtensionByURL(url string) *Extension {
	return ExtensionByURL(r.ModifierExtension, url)
}

// MarshalXML serializes SubscriptionTopicNotificationShape to FHIR-conformant XML.
func (b SubscriptionTopicNotificationShape) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if start.Name.Local == "" {
		start.Name.Local = "SubscriptionTopic.notificationShape"
	}
	if b.Id != nil {
		start.Attr = append(start.Attr, xml.Attr{Name: xml.Name{Local: "id"}, Value: *b.Id})
	}
	if err := e.EncodeToken(start); err != nil {
		return err
	}

	for _, item := range b.Extension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "extension"}}); err != nil {
			return err
		}
	}
	for _, item := range b.ModifierExtension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "modifierExtension"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveString(e, "resource", b.Resource, b.ResourceExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveStringArray(e, "include", b.Include, b.IncludeExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveStringArray(e, "revInclude", b.RevInclude, b.RevIncludeExt); err != nil {
		return err
	}

	return e.EncodeToken(start.End())
}

// UnmarshalXML deserializes SubscriptionTopicNotificationShape from FHIR-conformant XML.
func (r *SubscriptionTopicNotificationShape) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	for _, attr := range start.Attr {
		if attr.Name.Local == "id" {
			v := attr.Value
			r.Id = &v
		}
	}

	for {
		tok, err := d.Token()
		if err != nil {
			return err
		}
		switch t := tok.(type) {
		case xml.StartElement:
			switch t.Name.Local {
			case "extension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Extension = append(r.Extension, v)
			case "modifierExtension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.ModifierExtension = append(r.ModifierExtension, v)
			case "resource":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Resource = v
				r.ResourceExt = ext
			case "include":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				// nil is meaningful here: it is a positional slot with no value.
				r.Include = append(r.Include, v)
				// The slots are parallel by position: fill the gap, then append.
				if ext != nil {
					for len(r.IncludeExt) < len(r.Include)-1 {
						r.IncludeExt = append(r.IncludeExt, nil)
					}
					r.IncludeExt = append(r.IncludeExt, ext)
				}
			case "revInclude":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				// nil is meaningful here: it is a positional slot with no value.
				r.RevInclude = append(r.RevInclude, v)
				// The slots are parallel by position: fill the gap, then append.
				if ext != nil {
					for len(r.RevIncludeExt) < len(r.RevInclude)-1 {
						r.RevIncludeExt = append(r.RevIncludeExt, nil)
					}
					r.RevIncludeExt = append(r.RevIncludeExt, ext)
				}
			default:
				if err := d.Skip(); err != nil {
					return err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// SubscriptionTopicResourceTrigger represents the SubscriptionTopic.resourceTrigger backbone element.
// Definition of a resource-based trigger for the subscription topic
type SubscriptionTopicResourceTrigger struct {
	// Unique id for inter-element referencing
	Id *string `json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Text representation of the resource trigger
	Description *string `json:"description,omitempty"`
	// Extension for Description
	DescriptionExt *Element `json:"_description,omitempty"`
	// Data Type or Resource (reference to definition) for this trigger definition
	Resource *string `json:"resource,omitempty"`
	// Extension for Resource
	ResourceExt *Element `json:"_resource,omitempty"`
	// create | update | delete
	SupportedInteraction []*MethodCode `json:"supportedInteraction,omitempty"`
	// Extension for SupportedInteraction
	SupportedInteractionExt []*Element `json:"_supportedInteraction,omitempty"`
	// Query based trigger rule
	QueryCriteria *SubscriptionTopicResourceTriggerQueryCriteria `json:"queryCriteria,omitempty"`
	// FHIRPath based trigger rule
	FhirPathCriteria *string `json:"fhirPathCriteria,omitempty"`
	// Extension for FhirPathCriteria
	FhirPathCriteriaExt *Element `json:"_fhirPathCriteria,omitempty"`
}

// GetExtensionByURL returns the first extension with the given URL, or nil.
//
// The result points into the slice, so writing through it edits the value.
func (r *SubscriptionTopicResourceTrigger) GetExtensionByURL(url string) *Extension {
	return ExtensionByURL(r.Extension, url)
}

// GetExtensionsByURL returns every extension with the given URL. A URL may repeat
// where the extension's cardinality allows it.
func (r *SubscriptionTopicResourceTrigger) GetExtensionsByURL(url string) []*Extension {
	return ExtensionsByURL(r.Extension, url)
}

// HasExtensionByURL reports whether any extension carries the given URL, which
// is the whole meaning of the extensions that have no value.
func (r *SubscriptionTopicResourceTrigger) HasExtensionByURL(url string) bool {
	return HasExtensionByURL(r.Extension, url)
}

// GetModifierExtensionByURL returns the first modifier extension with the given
// URL, or nil. Kept separate from GetExtensionByURL because a modifier extension
// changes the meaning of the element it is on.
func (r *SubscriptionTopicResourceTrigger) GetModifierExtensionByURL(url string) *Extension {
	return ExtensionByURL(r.ModifierExtension, url)
}

// MarshalXML serializes SubscriptionTopicResourceTrigger to FHIR-conformant XML.
func (b SubscriptionTopicResourceTrigger) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if start.Name.Local == "" {
		start.Name.Local = "SubscriptionTopic.resourceTrigger"
	}
	if b.Id != nil {
		start.Attr = append(start.Attr, xml.Attr{Name: xml.Name{Local: "id"}, Value: *b.Id})
	}
	if err := e.EncodeToken(start); err != nil {
		return err
	}

	for _, item := range b.Extension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "extension"}}); err != nil {
			return err
		}
	}
	for _, item := range b.ModifierExtension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "modifierExtension"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveString(e, "description", b.Description, b.DescriptionExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveString(e, "resource", b.Resource, b.ResourceExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveCodeArray(e, "supportedInteraction", b.SupportedInteraction, b.SupportedInteractionExt); err != nil {
		return err
	}
	if b.QueryCriteria != nil {
		if err := b.QueryCriteria.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "queryCriteria"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveString(e, "fhirPathCriteria", b.FhirPathCriteria, b.FhirPathCriteriaExt); err != nil {
		return err
	}

	return e.EncodeToken(start.End())
}

// UnmarshalXML deserializes SubscriptionTopicResourceTrigger from FHIR-conformant XML.
func (r *SubscriptionTopicResourceTrigger) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	for _, attr := range start.Attr {
		if attr.Name.Local == "id" {
			v := attr.Value
			r.Id = &v
		}
	}

	for {
		tok, err := d.Token()
		if err != nil {
			return err
		}
		switch t := tok.(type) {
		case xml.StartElement:
			switch t.Name.Local {
			case "extension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Extension = append(r.Extension, v)
			case "modifierExtension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.ModifierExtension = append(r.ModifierExtension, v)
			case "description":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Description = v
				r.DescriptionExt = ext
			case "resource":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Resource = v
				r.ResourceExt = ext
			case "supportedInteraction":
				v, ext, err := xmlDecodePrimitiveCode[MethodCode](d, t)
				if err != nil {
					return err
				}
				// nil is meaningful here: it is a positional slot with no value.
				r.SupportedInteraction = append(r.SupportedInteraction, v)
				// The slots are parallel by position: fill the gap, then append.
				if ext != nil {
					for len(r.SupportedInteractionExt) < len(r.SupportedInteraction)-1 {
						r.SupportedInteractionExt = append(r.SupportedInteractionExt, nil)
					}
					r.SupportedInteractionExt = append(r.SupportedInteractionExt, ext)
				}
			case "queryCriteria":
				var v SubscriptionTopicResourceTriggerQueryCriteria
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.QueryCriteria = &v
			case "fhirPathCriteria":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.FhirPathCriteria = v
				r.FhirPathCriteriaExt = ext
			default:
				if err := d.Skip(); err != nil {
					return err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// SubscriptionTopicResourceTriggerQueryCriteria represents the SubscriptionTopic.resourceTrigger.queryCriteria backbone element.
// Query based trigger rule
type SubscriptionTopicResourceTriggerQueryCriteria struct {
	// Unique id for inter-element referencing
	Id *string `json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Rule applied to previous resource state
	Previous *string `json:"previous,omitempty"`
	// Extension for Previous
	PreviousExt *Element `json:"_previous,omitempty"`
	// test-passes | test-fails
	ResultForCreate *CriteriaNotExistsBehavior `json:"resultForCreate,omitempty"`
	// Extension for ResultForCreate
	ResultForCreateExt *Element `json:"_resultForCreate,omitempty"`
	// Rule applied to current resource state
	Current *string `json:"current,omitempty"`
	// Extension for Current
	CurrentExt *Element `json:"_current,omitempty"`
	// test-passes | test-fails
	ResultForDelete *CriteriaNotExistsBehavior `json:"resultForDelete,omitempty"`
	// Extension for ResultForDelete
	ResultForDeleteExt *Element `json:"_resultForDelete,omitempty"`
	// Both must be true flag
	RequireBoth *bool `json:"requireBoth,omitempty"`
	// Extension for RequireBoth
	RequireBothExt *Element `json:"_requireBoth,omitempty"`
}

// GetExtensionByURL returns the first extension with the given URL, or nil.
//
// The result points into the slice, so writing through it edits the value.
func (r *SubscriptionTopicResourceTriggerQueryCriteria) GetExtensionByURL(url string) *Extension {
	return ExtensionByURL(r.Extension, url)
}

// GetExtensionsByURL returns every extension with the given URL. A URL may repeat
// where the extension's cardinality allows it.
func (r *SubscriptionTopicResourceTriggerQueryCriteria) GetExtensionsByURL(url string) []*Extension {
	return ExtensionsByURL(r.Extension, url)
}

// HasExtensionByURL reports whether any extension carries the given URL, which
// is the whole meaning of the extensions that have no value.
func (r *SubscriptionTopicResourceTriggerQueryCriteria) HasExtensionByURL(url string) bool {
	return HasExtensionByURL(r.Extension, url)
}

// GetModifierExtensionByURL returns the first modifier extension with the given
// URL, or nil. Kept separate from GetExtensionByURL because a modifier extension
// changes the meaning of the element it is on.
func (r *SubscriptionTopicResourceTriggerQueryCriteria) GetModifierExtensionByURL(url string) *Extension {
	return ExtensionByURL(r.ModifierExtension, url)
}

// MarshalXML serializes SubscriptionTopicResourceTriggerQueryCriteria to FHIR-conformant XML.
func (b SubscriptionTopicResourceTriggerQueryCriteria) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if start.Name.Local == "" {
		start.Name.Local = "SubscriptionTopic.resourceTrigger.queryCriteria"
	}
	if b.Id != nil {
		start.Attr = append(start.Attr, xml.Attr{Name: xml.Name{Local: "id"}, Value: *b.Id})
	}
	if err := e.EncodeToken(start); err != nil {
		return err
	}

	for _, item := range b.Extension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "extension"}}); err != nil {
			return err
		}
	}
	for _, item := range b.ModifierExtension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "modifierExtension"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveString(e, "previous", b.Previous, b.PreviousExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveCode(e, "resultForCreate", b.ResultForCreate, b.ResultForCreateExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveString(e, "current", b.Current, b.CurrentExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveCode(e, "resultForDelete", b.ResultForDelete, b.ResultForDeleteExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveBool(e, "requireBoth", b.RequireBoth, b.RequireBothExt); err != nil {
		return err
	}

	return e.EncodeToken(start.End())
}

// UnmarshalXML deserializes SubscriptionTopicResourceTriggerQueryCriteria from FHIR-conformant XML.
func (r *SubscriptionTopicResourceTriggerQueryCriteria) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	for _, attr := range start.Attr {
		if attr.Name.Local == "id" {
			v := attr.Value
			r.Id = &v
		}
	}

	for {
		tok, err := d.Token()
		if err != nil {
			return err
		}
		switch t := tok.(type) {
		case xml.StartElement:
			switch t.Name.Local {
			case "extension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Extension = append(r.Extension, v)
			case "modifierExtension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.ModifierExtension = append(r.ModifierExtension, v)
			case "previous":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Previous = v
				r.PreviousExt = ext
			case "resultForCreate":
				v, ext, err := xmlDecodePrimitiveCode[CriteriaNotExistsBehavior](d, t)
				if err != nil {
					return err
				}
				r.ResultForCreate = v
				r.ResultForCreateExt = ext
			case "current":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Current = v
				r.CurrentExt = ext
			case "resultForDelete":
				v, ext, err := xmlDecodePrimitiveCode[CriteriaNotExistsBehavior](d, t)
				if err != nil {
					return err
				}
				r.ResultForDelete = v
				r.ResultForDeleteExt = ext
			case "requireBoth":
				v, ext, err := xmlDecodePrimitiveBool(d, t)
				if err != nil {
					return err
				}
				r.RequireBoth = v
				r.RequireBothExt = ext
			default:
				if err := d.Skip(); err != nil {
					return err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// =============================================================================
// SubscriptionTopic - Fluent Builder
// =============================================================================

// SubscriptionTopicBuilder provides a fluent API for constructing SubscriptionTopic resources.
type SubscriptionTopicBuilder struct {
	subscriptionTopic *SubscriptionTopic
}

// NewSubscriptionTopicBuilder creates a new SubscriptionTopicBuilder.
func NewSubscriptionTopicBuilder() *SubscriptionTopicBuilder {
	return &SubscriptionTopicBuilder{
		// Nothing to set: the type marker carries the resource type, so the zero
		// value is already correct both in memory and on the wire.
		subscriptionTopic: &SubscriptionTopic{},
	}
}

// Build returns the constructed SubscriptionTopic resource.
func (b *SubscriptionTopicBuilder) Build() *SubscriptionTopic {
	return b.subscriptionTopic
}

// SetId sets the Id field.
func (b *SubscriptionTopicBuilder) SetId(v string) *SubscriptionTopicBuilder {
	b.subscriptionTopic.Id = &v
	return b
}

// SetMeta sets the Meta field.
func (b *SubscriptionTopicBuilder) SetMeta(v Meta) *SubscriptionTopicBuilder {
	b.subscriptionTopic.Meta = &v
	return b
}

// SetImplicitRules sets the ImplicitRules field.
func (b *SubscriptionTopicBuilder) SetImplicitRules(v string) *SubscriptionTopicBuilder {
	b.subscriptionTopic.ImplicitRules = &v
	return b
}

// SetLanguage sets the Language field.
func (b *SubscriptionTopicBuilder) SetLanguage(v string) *SubscriptionTopicBuilder {
	b.subscriptionTopic.Language = &v
	return b
}

// SetText sets the Text field.
func (b *SubscriptionTopicBuilder) SetText(v Narrative) *SubscriptionTopicBuilder {
	b.subscriptionTopic.Text = &v
	return b
}

// AddContained adds a resource to Contained.
//
// A nil resource is ignored rather than appended. Contained holds an interface, so
// a nil entry marshals as JSON null — which FHIR does not allow there, and which
// this library then drops on the way back in, so a document written with one
// re-reads shorter than it was written.
//
// Filtering at serialization time would fix that everywhere, but giving
// ContainedList a MarshalJSON costs 2.9x on every marshal that has no nil in it
// (419 -> 1209 ns/op, 1 -> 3 allocs), because encoding/json re-compacts whatever a
// MarshalJSON returns. That is the cost task 6.2 removed by deleting 437 of them.
// Guarding the builder is free and covers the path the documentation recommends;
// a struct literal can still put a nil there.
func (b *SubscriptionTopicBuilder) AddContained(v Resource) *SubscriptionTopicBuilder {
	if v == nil {
		return b
	}
	b.subscriptionTopic.Contained = append(b.subscriptionTopic.Contained, v)
	return b
}

// AddExtension adds a Extension element.
func (b *SubscriptionTopicBuilder) AddExtension(v Extension) *SubscriptionTopicBuilder {
	b.subscriptionTopic.Extension = append(b.subscriptionTopic.Extension, v)
	return b
}

// AddModifierExtension adds a ModifierExtension element.
func (b *SubscriptionTopicBuilder) AddModifierExtension(v Extension) *SubscriptionTopicBuilder {
	b.subscriptionTopic.ModifierExtension = append(b.subscriptionTopic.ModifierExtension, v)
	return b
}

// SetUrl sets the Url field.
func (b *SubscriptionTopicBuilder) SetUrl(v string) *SubscriptionTopicBuilder {
	b.subscriptionTopic.Url = &v
	return b
}

// AddIdentifier adds a Identifier element.
func (b *SubscriptionTopicBuilder) AddIdentifier(v Identifier) *SubscriptionTopicBuilder {
	b.subscriptionTopic.Identifier = append(b.subscriptionTopic.Identifier, v)
	return b
}

// SetVersion sets the Version field.
func (b *SubscriptionTopicBuilder) SetVersion(v string) *SubscriptionTopicBuilder {
	b.subscriptionTopic.Version = &v
	return b
}

// SetVersionAlgorithmString sets VersionAlgorithm[x] to its VersionAlgorithmString variant.
//
// A choice element holds exactly one variant, so the others are cleared. Without
// that, a chain of setters produced a document with several of them present at
// once, which no FHIR server will accept and which nothing here reported.
func (b *SubscriptionTopicBuilder) SetVersionAlgorithmString(v string) *SubscriptionTopicBuilder {
	b.clearVersionAlgorithm()
	b.subscriptionTopic.VersionAlgorithmString = &v
	return b
}

// SetVersionAlgorithmStringExt sets the VersionAlgorithmStringExt field.
func (b *SubscriptionTopicBuilder) SetVersionAlgorithmStringExt(v Element) *SubscriptionTopicBuilder {
	b.subscriptionTopic.VersionAlgorithmStringExt = &v
	return b
}

// SetVersionAlgorithmCoding sets VersionAlgorithm[x] to its VersionAlgorithmCoding variant.
//
// A choice element holds exactly one variant, so the others are cleared. Without
// that, a chain of setters produced a document with several of them present at
// once, which no FHIR server will accept and which nothing here reported.
func (b *SubscriptionTopicBuilder) SetVersionAlgorithmCoding(v Coding) *SubscriptionTopicBuilder {
	b.clearVersionAlgorithm()
	b.subscriptionTopic.VersionAlgorithmCoding = &v
	return b
}

// SetName sets the Name field.
func (b *SubscriptionTopicBuilder) SetName(v string) *SubscriptionTopicBuilder {
	b.subscriptionTopic.Name = &v
	return b
}

// SetTitle sets the Title field.
func (b *SubscriptionTopicBuilder) SetTitle(v string) *SubscriptionTopicBuilder {
	b.subscriptionTopic.Title = &v
	return b
}

// AddDerivedFrom adds a DerivedFrom element.
//
// Takes a plain value: the field is a slice of pointers so that an absent slot
// can be expressed, but a builder call is always adding a value. For a slot that
// is deliberately absent, build the slice directly and leave that entry nil.
func (b *SubscriptionTopicBuilder) AddDerivedFrom(v string) *SubscriptionTopicBuilder {
	b.subscriptionTopic.DerivedFrom = append(b.subscriptionTopic.DerivedFrom, &v)
	return b
}

// SetStatus sets the Status field.
func (b *SubscriptionTopicBuilder) SetStatus(v PublicationStatus) *SubscriptionTopicBuilder {
	b.subscriptionTopic.Status = &v
	return b
}

// SetExperimental sets the Experimental field.
func (b *SubscriptionTopicBuilder) SetExperimental(v bool) *SubscriptionTopicBuilder {
	b.subscriptionTopic.Experimental = &v
	return b
}

// SetDate sets the Date field.
func (b *SubscriptionTopicBuilder) SetDate(v string) *SubscriptionTopicBuilder {
	b.subscriptionTopic.Date = &v
	return b
}

// SetPublisher sets the Publisher field.
func (b *SubscriptionTopicBuilder) SetPublisher(v string) *SubscriptionTopicBuilder {
	b.subscriptionTopic.Publisher = &v
	return b
}

// AddContact adds a Contact element.
func (b *SubscriptionTopicBuilder) AddContact(v ContactDetail) *SubscriptionTopicBuilder {
	b.subscriptionTopic.Contact = append(b.subscriptionTopic.Contact, v)
	return b
}

// SetDescription sets the Description field.
func (b *SubscriptionTopicBuilder) SetDescription(v string) *SubscriptionTopicBuilder {
	b.subscriptionTopic.Description = &v
	return b
}

// AddUseContext adds a UseContext element.
func (b *SubscriptionTopicBuilder) AddUseContext(v UsageContext) *SubscriptionTopicBuilder {
	b.subscriptionTopic.UseContext = append(b.subscriptionTopic.UseContext, v)
	return b
}

// AddJurisdiction adds a Jurisdiction element.
func (b *SubscriptionTopicBuilder) AddJurisdiction(v CodeableConcept) *SubscriptionTopicBuilder {
	b.subscriptionTopic.Jurisdiction = append(b.subscriptionTopic.Jurisdiction, v)
	return b
}

// SetPurpose sets the Purpose field.
func (b *SubscriptionTopicBuilder) SetPurpose(v string) *SubscriptionTopicBuilder {
	b.subscriptionTopic.Purpose = &v
	return b
}

// SetCopyright sets the Copyright field.
func (b *SubscriptionTopicBuilder) SetCopyright(v string) *SubscriptionTopicBuilder {
	b.subscriptionTopic.Copyright = &v
	return b
}

// SetCopyrightLabel sets the CopyrightLabel field.
func (b *SubscriptionTopicBuilder) SetCopyrightLabel(v string) *SubscriptionTopicBuilder {
	b.subscriptionTopic.CopyrightLabel = &v
	return b
}

// SetApprovalDate sets the ApprovalDate field.
func (b *SubscriptionTopicBuilder) SetApprovalDate(v string) *SubscriptionTopicBuilder {
	b.subscriptionTopic.ApprovalDate = &v
	return b
}

// SetLastReviewDate sets the LastReviewDate field.
func (b *SubscriptionTopicBuilder) SetLastReviewDate(v string) *SubscriptionTopicBuilder {
	b.subscriptionTopic.LastReviewDate = &v
	return b
}

// SetEffectivePeriod sets the EffectivePeriod field.
func (b *SubscriptionTopicBuilder) SetEffectivePeriod(v Period) *SubscriptionTopicBuilder {
	b.subscriptionTopic.EffectivePeriod = &v
	return b
}

// AddResourceTrigger adds a ResourceTrigger element.
func (b *SubscriptionTopicBuilder) AddResourceTrigger(v SubscriptionTopicResourceTrigger) *SubscriptionTopicBuilder {
	b.subscriptionTopic.ResourceTrigger = append(b.subscriptionTopic.ResourceTrigger, v)
	return b
}

// AddEventTrigger adds a EventTrigger element.
func (b *SubscriptionTopicBuilder) AddEventTrigger(v SubscriptionTopicEventTrigger) *SubscriptionTopicBuilder {
	b.subscriptionTopic.EventTrigger = append(b.subscriptionTopic.EventTrigger, v)
	return b
}

// AddCanFilterBy adds a CanFilterBy element.
func (b *SubscriptionTopicBuilder) AddCanFilterBy(v SubscriptionTopicCanFilterBy) *SubscriptionTopicBuilder {
	b.subscriptionTopic.CanFilterBy = append(b.subscriptionTopic.CanFilterBy, v)
	return b
}

// AddNotificationShape adds a NotificationShape element.
func (b *SubscriptionTopicBuilder) AddNotificationShape(v SubscriptionTopicNotificationShape) *SubscriptionTopicBuilder {
	b.subscriptionTopic.NotificationShape = append(b.subscriptionTopic.NotificationShape, v)
	return b
}

// SetImplicitRulesExt sets the extensions carried by ImplicitRules, serialized as
// "_implicitRules".
//
// This is how a primitive expresses an extension: a data-absent-reason on a
// birthDate lives here, not on the value.
func (b *SubscriptionTopicBuilder) SetImplicitRulesExt(v Element) *SubscriptionTopicBuilder {
	b.subscriptionTopic.ImplicitRulesExt = &v
	return b
}

// SetLanguageExt sets the extensions carried by Language, serialized as
// "_language".
//
// This is how a primitive expresses an extension: a data-absent-reason on a
// birthDate lives here, not on the value.
func (b *SubscriptionTopicBuilder) SetLanguageExt(v Element) *SubscriptionTopicBuilder {
	b.subscriptionTopic.LanguageExt = &v
	return b
}

// SetUrlExt sets the extensions carried by Url, serialized as
// "_url".
//
// This is how a primitive expresses an extension: a data-absent-reason on a
// birthDate lives here, not on the value.
func (b *SubscriptionTopicBuilder) SetUrlExt(v Element) *SubscriptionTopicBuilder {
	b.subscriptionTopic.UrlExt = &v
	return b
}

// SetVersionExt sets the extensions carried by Version, serialized as
// "_version".
//
// This is how a primitive expresses an extension: a data-absent-reason on a
// birthDate lives here, not on the value.
func (b *SubscriptionTopicBuilder) SetVersionExt(v Element) *SubscriptionTopicBuilder {
	b.subscriptionTopic.VersionExt = &v
	return b
}

// SetNameExt sets the extensions carried by Name, serialized as
// "_name".
//
// This is how a primitive expresses an extension: a data-absent-reason on a
// birthDate lives here, not on the value.
func (b *SubscriptionTopicBuilder) SetNameExt(v Element) *SubscriptionTopicBuilder {
	b.subscriptionTopic.NameExt = &v
	return b
}

// SetTitleExt sets the extensions carried by Title, serialized as
// "_title".
//
// This is how a primitive expresses an extension: a data-absent-reason on a
// birthDate lives here, not on the value.
func (b *SubscriptionTopicBuilder) SetTitleExt(v Element) *SubscriptionTopicBuilder {
	b.subscriptionTopic.TitleExt = &v
	return b
}

// AddDerivedFromExt attaches extensions to the DerivedFrom element added most
// recently.
//
// The two slices are parallel by position, so any earlier element that has no
// extension is filled in as nil first. Appending blindly instead would put the
// extension at the wrong index: after AddDerivedFrom twice, a bare append lands at
// position 0 and silently belongs to the first element rather than the second.
//
// A nil value is meaningful and can be passed deliberately: it is a position that
// has no extension.
func (b *SubscriptionTopicBuilder) AddDerivedFromExt(v *Element) *SubscriptionTopicBuilder {
	for len(b.subscriptionTopic.DerivedFromExt) < len(b.subscriptionTopic.DerivedFrom)-1 {
		b.subscriptionTopic.DerivedFromExt = append(b.subscriptionTopic.DerivedFromExt, nil)
	}
	b.subscriptionTopic.DerivedFromExt = append(b.subscriptionTopic.DerivedFromExt, v)
	return b
}

// SetStatusExt sets the extensions carried by Status, serialized as
// "_status".
//
// This is how a primitive expresses an extension: a data-absent-reason on a
// birthDate lives here, not on the value.
func (b *SubscriptionTopicBuilder) SetStatusExt(v Element) *SubscriptionTopicBuilder {
	b.subscriptionTopic.StatusExt = &v
	return b
}

// SetExperimentalExt sets the extensions carried by Experimental, serialized as
// "_experimental".
//
// This is how a primitive expresses an extension: a data-absent-reason on a
// birthDate lives here, not on the value.
func (b *SubscriptionTopicBuilder) SetExperimentalExt(v Element) *SubscriptionTopicBuilder {
	b.subscriptionTopic.ExperimentalExt = &v
	return b
}

// SetDateExt sets the extensions carried by Date, serialized as
// "_date".
//
// This is how a primitive expresses an extension: a data-absent-reason on a
// birthDate lives here, not on the value.
func (b *SubscriptionTopicBuilder) SetDateExt(v Element) *SubscriptionTopicBuilder {
	b.subscriptionTopic.DateExt = &v
	return b
}

// SetPublisherExt sets the extensions carried by Publisher, serialized as
// "_publisher".
//
// This is how a primitive expresses an extension: a data-absent-reason on a
// birthDate lives here, not on the value.
func (b *SubscriptionTopicBuilder) SetPublisherExt(v Element) *SubscriptionTopicBuilder {
	b.subscriptionTopic.PublisherExt = &v
	return b
}

// SetDescriptionExt sets the extensions carried by Description, serialized as
// "_description".
//
// This is how a primitive expresses an extension: a data-absent-reason on a
// birthDate lives here, not on the value.
func (b *SubscriptionTopicBuilder) SetDescriptionExt(v Element) *SubscriptionTopicBuilder {
	b.subscriptionTopic.DescriptionExt = &v
	return b
}

// SetPurposeExt sets the extensions carried by Purpose, serialized as
// "_purpose".
//
// This is how a primitive expresses an extension: a data-absent-reason on a
// birthDate lives here, not on the value.
func (b *SubscriptionTopicBuilder) SetPurposeExt(v Element) *SubscriptionTopicBuilder {
	b.subscriptionTopic.PurposeExt = &v
	return b
}

// SetCopyrightExt sets the extensions carried by Copyright, serialized as
// "_copyright".
//
// This is how a primitive expresses an extension: a data-absent-reason on a
// birthDate lives here, not on the value.
func (b *SubscriptionTopicBuilder) SetCopyrightExt(v Element) *SubscriptionTopicBuilder {
	b.subscriptionTopic.CopyrightExt = &v
	return b
}

// SetCopyrightLabelExt sets the extensions carried by CopyrightLabel, serialized as
// "_copyrightLabel".
//
// This is how a primitive expresses an extension: a data-absent-reason on a
// birthDate lives here, not on the value.
func (b *SubscriptionTopicBuilder) SetCopyrightLabelExt(v Element) *SubscriptionTopicBuilder {
	b.subscriptionTopic.CopyrightLabelExt = &v
	return b
}

// SetApprovalDateExt sets the extensions carried by ApprovalDate, serialized as
// "_approvalDate".
//
// This is how a primitive expresses an extension: a data-absent-reason on a
// birthDate lives here, not on the value.
func (b *SubscriptionTopicBuilder) SetApprovalDateExt(v Element) *SubscriptionTopicBuilder {
	b.subscriptionTopic.ApprovalDateExt = &v
	return b
}

// SetLastReviewDateExt sets the extensions carried by LastReviewDate, serialized as
// "_lastReviewDate".
//
// This is how a primitive expresses an extension: a data-absent-reason on a
// birthDate lives here, not on the value.
func (b *SubscriptionTopicBuilder) SetLastReviewDateExt(v Element) *SubscriptionTopicBuilder {
	b.subscriptionTopic.LastReviewDateExt = &v
	return b
}

// clearVersionAlgorithm unsets every variant of VersionAlgorithm[x], including the
// _field companions of the primitive ones.
func (b *SubscriptionTopicBuilder) clearVersionAlgorithm() {
	b.subscriptionTopic.VersionAlgorithmString = nil
	b.subscriptionTopic.VersionAlgorithmCoding = nil
}

// =============================================================================
// SubscriptionTopicCanFilterBy - Fluent Builder
// =============================================================================

// SubscriptionTopicCanFilterByBuilder provides a fluent API for constructing SubscriptionTopicCanFilterBy values.
type SubscriptionTopicCanFilterByBuilder struct {
	subscriptionTopicCanFilterBy *SubscriptionTopicCanFilterBy
}

// NewSubscriptionTopicCanFilterByBuilder creates a new SubscriptionTopicCanFilterByBuilder.
func NewSubscriptionTopicCanFilterByBuilder() *SubscriptionTopicCanFilterByBuilder {
	return &SubscriptionTopicCanFilterByBuilder{
		subscriptionTopicCanFilterBy: &SubscriptionTopicCanFilterBy{},
	}
}

// Build returns the constructed SubscriptionTopicCanFilterBy.
//
// A value, not a pointer: every consumer of a datatype takes one. Patient.Name is
// []HumanName so AddName wants a HumanName, and a pointer field like Range.Low is
// set through SetLow(Quantity), which takes the address itself. Returning *T meant
// writing AddName(*NewHumanNameBuilder()...Build()) — a dereference at every call
// site, to undo a pointer nobody asked for.
func (b *SubscriptionTopicCanFilterByBuilder) Build() SubscriptionTopicCanFilterBy {
	return *b.subscriptionTopicCanFilterBy
}

// SetId sets the Id field.
func (b *SubscriptionTopicCanFilterByBuilder) SetId(v string) *SubscriptionTopicCanFilterByBuilder {
	b.subscriptionTopicCanFilterBy.Id = &v
	return b
}

// AddExtension adds a Extension element.
func (b *SubscriptionTopicCanFilterByBuilder) AddExtension(v Extension) *SubscriptionTopicCanFilterByBuilder {
	b.subscriptionTopicCanFilterBy.Extension = append(b.subscriptionTopicCanFilterBy.Extension, v)
	return b
}

// AddModifierExtension adds a ModifierExtension element.
func (b *SubscriptionTopicCanFilterByBuilder) AddModifierExtension(v Extension) *SubscriptionTopicCanFilterByBuilder {
	b.subscriptionTopicCanFilterBy.ModifierExtension = append(b.subscriptionTopicCanFilterBy.ModifierExtension, v)
	return b
}

// SetDescription sets the Description field.
func (b *SubscriptionTopicCanFilterByBuilder) SetDescription(v string) *SubscriptionTopicCanFilterByBuilder {
	b.subscriptionTopicCanFilterBy.Description = &v
	return b
}

// SetResource sets the Resource field.
func (b *SubscriptionTopicCanFilterByBuilder) SetResource(v string) *SubscriptionTopicCanFilterByBuilder {
	b.subscriptionTopicCanFilterBy.Resource = &v
	return b
}

// SetFilterParameter sets the FilterParameter field.
func (b *SubscriptionTopicCanFilterByBuilder) SetFilterParameter(v string) *SubscriptionTopicCanFilterByBuilder {
	b.subscriptionTopicCanFilterBy.FilterParameter = &v
	return b
}

// SetFilterDefinition sets the FilterDefinition field.
func (b *SubscriptionTopicCanFilterByBuilder) SetFilterDefinition(v string) *SubscriptionTopicCanFilterByBuilder {
	b.subscriptionTopicCanFilterBy.FilterDefinition = &v
	return b
}

// AddComparator adds a Comparator element.
//
// Takes a plain value: the field is a slice of pointers so that an absent slot
// can be expressed, but a builder call is always adding a value. For a slot that
// is deliberately absent, build the slice directly and leave that entry nil.
func (b *SubscriptionTopicCanFilterByBuilder) AddComparator(v SearchComparator) *SubscriptionTopicCanFilterByBuilder {
	b.subscriptionTopicCanFilterBy.Comparator = append(b.subscriptionTopicCanFilterBy.Comparator, &v)
	return b
}

// AddModifier adds a Modifier element.
//
// Takes a plain value: the field is a slice of pointers so that an absent slot
// can be expressed, but a builder call is always adding a value. For a slot that
// is deliberately absent, build the slice directly and leave that entry nil.
func (b *SubscriptionTopicCanFilterByBuilder) AddModifier(v SearchModifierCode) *SubscriptionTopicCanFilterByBuilder {
	b.subscriptionTopicCanFilterBy.Modifier = append(b.subscriptionTopicCanFilterBy.Modifier, &v)
	return b
}

// SetDescriptionExt sets the extensions carried by Description, serialized as
// "_description".
//
// This is how a primitive expresses an extension: a data-absent-reason on a
// birthDate lives here, not on the value.
func (b *SubscriptionTopicCanFilterByBuilder) SetDescriptionExt(v Element) *SubscriptionTopicCanFilterByBuilder {
	b.subscriptionTopicCanFilterBy.DescriptionExt = &v
	return b
}

// SetResourceExt sets the extensions carried by Resource, serialized as
// "_resource".
//
// This is how a primitive expresses an extension: a data-absent-reason on a
// birthDate lives here, not on the value.
func (b *SubscriptionTopicCanFilterByBuilder) SetResourceExt(v Element) *SubscriptionTopicCanFilterByBuilder {
	b.subscriptionTopicCanFilterBy.ResourceExt = &v
	return b
}

// SetFilterParameterExt sets the extensions carried by FilterParameter, serialized as
// "_filterParameter".
//
// This is how a primitive expresses an extension: a data-absent-reason on a
// birthDate lives here, not on the value.
func (b *SubscriptionTopicCanFilterByBuilder) SetFilterParameterExt(v Element) *SubscriptionTopicCanFilterByBuilder {
	b.subscriptionTopicCanFilterBy.FilterParameterExt = &v
	return b
}

// SetFilterDefinitionExt sets the extensions carried by FilterDefinition, serialized as
// "_filterDefinition".
//
// This is how a primitive expresses an extension: a data-absent-reason on a
// birthDate lives here, not on the value.
func (b *SubscriptionTopicCanFilterByBuilder) SetFilterDefinitionExt(v Element) *SubscriptionTopicCanFilterByBuilder {
	b.subscriptionTopicCanFilterBy.FilterDefinitionExt = &v
	return b
}

// AddComparatorExt attaches extensions to the Comparator element added most
// recently.
//
// The two slices are parallel by position, so any earlier element that has no
// extension is filled in as nil first. Appending blindly instead would put the
// extension at the wrong index: after AddComparator twice, a bare append lands at
// position 0 and silently belongs to the first element rather than the second.
//
// A nil value is meaningful and can be passed deliberately: it is a position that
// has no extension.
func (b *SubscriptionTopicCanFilterByBuilder) AddComparatorExt(v *Element) *SubscriptionTopicCanFilterByBuilder {
	for len(b.subscriptionTopicCanFilterBy.ComparatorExt) < len(b.subscriptionTopicCanFilterBy.Comparator)-1 {
		b.subscriptionTopicCanFilterBy.ComparatorExt = append(b.subscriptionTopicCanFilterBy.ComparatorExt, nil)
	}
	b.subscriptionTopicCanFilterBy.ComparatorExt = append(b.subscriptionTopicCanFilterBy.ComparatorExt, v)
	return b
}

// AddModifierExt attaches extensions to the Modifier element added most
// recently.
//
// The two slices are parallel by position, so any earlier element that has no
// extension is filled in as nil first. Appending blindly instead would put the
// extension at the wrong index: after AddModifier twice, a bare append lands at
// position 0 and silently belongs to the first element rather than the second.
//
// A nil value is meaningful and can be passed deliberately: it is a position that
// has no extension.
func (b *SubscriptionTopicCanFilterByBuilder) AddModifierExt(v *Element) *SubscriptionTopicCanFilterByBuilder {
	for len(b.subscriptionTopicCanFilterBy.ModifierExt) < len(b.subscriptionTopicCanFilterBy.Modifier)-1 {
		b.subscriptionTopicCanFilterBy.ModifierExt = append(b.subscriptionTopicCanFilterBy.ModifierExt, nil)
	}
	b.subscriptionTopicCanFilterBy.ModifierExt = append(b.subscriptionTopicCanFilterBy.ModifierExt, v)
	return b
}

// =============================================================================
// SubscriptionTopicEventTrigger - Fluent Builder
// =============================================================================

// SubscriptionTopicEventTriggerBuilder provides a fluent API for constructing SubscriptionTopicEventTrigger values.
type SubscriptionTopicEventTriggerBuilder struct {
	subscriptionTopicEventTrigger *SubscriptionTopicEventTrigger
}

// NewSubscriptionTopicEventTriggerBuilder creates a new SubscriptionTopicEventTriggerBuilder.
func NewSubscriptionTopicEventTriggerBuilder() *SubscriptionTopicEventTriggerBuilder {
	return &SubscriptionTopicEventTriggerBuilder{
		subscriptionTopicEventTrigger: &SubscriptionTopicEventTrigger{},
	}
}

// Build returns the constructed SubscriptionTopicEventTrigger.
//
// A value, not a pointer: every consumer of a datatype takes one. Patient.Name is
// []HumanName so AddName wants a HumanName, and a pointer field like Range.Low is
// set through SetLow(Quantity), which takes the address itself. Returning *T meant
// writing AddName(*NewHumanNameBuilder()...Build()) — a dereference at every call
// site, to undo a pointer nobody asked for.
func (b *SubscriptionTopicEventTriggerBuilder) Build() SubscriptionTopicEventTrigger {
	return *b.subscriptionTopicEventTrigger
}

// SetId sets the Id field.
func (b *SubscriptionTopicEventTriggerBuilder) SetId(v string) *SubscriptionTopicEventTriggerBuilder {
	b.subscriptionTopicEventTrigger.Id = &v
	return b
}

// AddExtension adds a Extension element.
func (b *SubscriptionTopicEventTriggerBuilder) AddExtension(v Extension) *SubscriptionTopicEventTriggerBuilder {
	b.subscriptionTopicEventTrigger.Extension = append(b.subscriptionTopicEventTrigger.Extension, v)
	return b
}

// AddModifierExtension adds a ModifierExtension element.
func (b *SubscriptionTopicEventTriggerBuilder) AddModifierExtension(v Extension) *SubscriptionTopicEventTriggerBuilder {
	b.subscriptionTopicEventTrigger.ModifierExtension = append(b.subscriptionTopicEventTrigger.ModifierExtension, v)
	return b
}

// SetDescription sets the Description field.
func (b *SubscriptionTopicEventTriggerBuilder) SetDescription(v string) *SubscriptionTopicEventTriggerBuilder {
	b.subscriptionTopicEventTrigger.Description = &v
	return b
}

// SetEvent sets the Event field.
func (b *SubscriptionTopicEventTriggerBuilder) SetEvent(v CodeableConcept) *SubscriptionTopicEventTriggerBuilder {
	b.subscriptionTopicEventTrigger.Event = &v
	return b
}

// SetResource sets the Resource field.
func (b *SubscriptionTopicEventTriggerBuilder) SetResource(v string) *SubscriptionTopicEventTriggerBuilder {
	b.subscriptionTopicEventTrigger.Resource = &v
	return b
}

// SetDescriptionExt sets the extensions carried by Description, serialized as
// "_description".
//
// This is how a primitive expresses an extension: a data-absent-reason on a
// birthDate lives here, not on the value.
func (b *SubscriptionTopicEventTriggerBuilder) SetDescriptionExt(v Element) *SubscriptionTopicEventTriggerBuilder {
	b.subscriptionTopicEventTrigger.DescriptionExt = &v
	return b
}

// SetResourceExt sets the extensions carried by Resource, serialized as
// "_resource".
//
// This is how a primitive expresses an extension: a data-absent-reason on a
// birthDate lives here, not on the value.
func (b *SubscriptionTopicEventTriggerBuilder) SetResourceExt(v Element) *SubscriptionTopicEventTriggerBuilder {
	b.subscriptionTopicEventTrigger.ResourceExt = &v
	return b
}

// =============================================================================
// SubscriptionTopicNotificationShape - Fluent Builder
// =============================================================================

// SubscriptionTopicNotificationShapeBuilder provides a fluent API for constructing SubscriptionTopicNotificationShape values.
type SubscriptionTopicNotificationShapeBuilder struct {
	subscriptionTopicNotificationShape *SubscriptionTopicNotificationShape
}

// NewSubscriptionTopicNotificationShapeBuilder creates a new SubscriptionTopicNotificationShapeBuilder.
func NewSubscriptionTopicNotificationShapeBuilder() *SubscriptionTopicNotificationShapeBuilder {
	return &SubscriptionTopicNotificationShapeBuilder{
		subscriptionTopicNotificationShape: &SubscriptionTopicNotificationShape{},
	}
}

// Build returns the constructed SubscriptionTopicNotificationShape.
//
// A value, not a pointer: every consumer of a datatype takes one. Patient.Name is
// []HumanName so AddName wants a HumanName, and a pointer field like Range.Low is
// set through SetLow(Quantity), which takes the address itself. Returning *T meant
// writing AddName(*NewHumanNameBuilder()...Build()) — a dereference at every call
// site, to undo a pointer nobody asked for.
func (b *SubscriptionTopicNotificationShapeBuilder) Build() SubscriptionTopicNotificationShape {
	return *b.subscriptionTopicNotificationShape
}

// SetId sets the Id field.
func (b *SubscriptionTopicNotificationShapeBuilder) SetId(v string) *SubscriptionTopicNotificationShapeBuilder {
	b.subscriptionTopicNotificationShape.Id = &v
	return b
}

// AddExtension adds a Extension element.
func (b *SubscriptionTopicNotificationShapeBuilder) AddExtension(v Extension) *SubscriptionTopicNotificationShapeBuilder {
	b.subscriptionTopicNotificationShape.Extension = append(b.subscriptionTopicNotificationShape.Extension, v)
	return b
}

// AddModifierExtension adds a ModifierExtension element.
func (b *SubscriptionTopicNotificationShapeBuilder) AddModifierExtension(v Extension) *SubscriptionTopicNotificationShapeBuilder {
	b.subscriptionTopicNotificationShape.ModifierExtension = append(b.subscriptionTopicNotificationShape.ModifierExtension, v)
	return b
}

// SetResource sets the Resource field.
func (b *SubscriptionTopicNotificationShapeBuilder) SetResource(v string) *SubscriptionTopicNotificationShapeBuilder {
	b.subscriptionTopicNotificationShape.Resource = &v
	return b
}

// AddInclude adds a Include element.
//
// Takes a plain value: the field is a slice of pointers so that an absent slot
// can be expressed, but a builder call is always adding a value. For a slot that
// is deliberately absent, build the slice directly and leave that entry nil.
func (b *SubscriptionTopicNotificationShapeBuilder) AddInclude(v string) *SubscriptionTopicNotificationShapeBuilder {
	b.subscriptionTopicNotificationShape.Include = append(b.subscriptionTopicNotificationShape.Include, &v)
	return b
}

// AddRevInclude adds a RevInclude element.
//
// Takes a plain value: the field is a slice of pointers so that an absent slot
// can be expressed, but a builder call is always adding a value. For a slot that
// is deliberately absent, build the slice directly and leave that entry nil.
func (b *SubscriptionTopicNotificationShapeBuilder) AddRevInclude(v string) *SubscriptionTopicNotificationShapeBuilder {
	b.subscriptionTopicNotificationShape.RevInclude = append(b.subscriptionTopicNotificationShape.RevInclude, &v)
	return b
}

// SetResourceExt sets the extensions carried by Resource, serialized as
// "_resource".
//
// This is how a primitive expresses an extension: a data-absent-reason on a
// birthDate lives here, not on the value.
func (b *SubscriptionTopicNotificationShapeBuilder) SetResourceExt(v Element) *SubscriptionTopicNotificationShapeBuilder {
	b.subscriptionTopicNotificationShape.ResourceExt = &v
	return b
}

// AddIncludeExt attaches extensions to the Include element added most
// recently.
//
// The two slices are parallel by position, so any earlier element that has no
// extension is filled in as nil first. Appending blindly instead would put the
// extension at the wrong index: after AddInclude twice, a bare append lands at
// position 0 and silently belongs to the first element rather than the second.
//
// A nil value is meaningful and can be passed deliberately: it is a position that
// has no extension.
func (b *SubscriptionTopicNotificationShapeBuilder) AddIncludeExt(v *Element) *SubscriptionTopicNotificationShapeBuilder {
	for len(b.subscriptionTopicNotificationShape.IncludeExt) < len(b.subscriptionTopicNotificationShape.Include)-1 {
		b.subscriptionTopicNotificationShape.IncludeExt = append(b.subscriptionTopicNotificationShape.IncludeExt, nil)
	}
	b.subscriptionTopicNotificationShape.IncludeExt = append(b.subscriptionTopicNotificationShape.IncludeExt, v)
	return b
}

// AddRevIncludeExt attaches extensions to the RevInclude element added most
// recently.
//
// The two slices are parallel by position, so any earlier element that has no
// extension is filled in as nil first. Appending blindly instead would put the
// extension at the wrong index: after AddRevInclude twice, a bare append lands at
// position 0 and silently belongs to the first element rather than the second.
//
// A nil value is meaningful and can be passed deliberately: it is a position that
// has no extension.
func (b *SubscriptionTopicNotificationShapeBuilder) AddRevIncludeExt(v *Element) *SubscriptionTopicNotificationShapeBuilder {
	for len(b.subscriptionTopicNotificationShape.RevIncludeExt) < len(b.subscriptionTopicNotificationShape.RevInclude)-1 {
		b.subscriptionTopicNotificationShape.RevIncludeExt = append(b.subscriptionTopicNotificationShape.RevIncludeExt, nil)
	}
	b.subscriptionTopicNotificationShape.RevIncludeExt = append(b.subscriptionTopicNotificationShape.RevIncludeExt, v)
	return b
}

// =============================================================================
// SubscriptionTopicResourceTrigger - Fluent Builder
// =============================================================================

// SubscriptionTopicResourceTriggerBuilder provides a fluent API for constructing SubscriptionTopicResourceTrigger values.
type SubscriptionTopicResourceTriggerBuilder struct {
	subscriptionTopicResourceTrigger *SubscriptionTopicResourceTrigger
}

// NewSubscriptionTopicResourceTriggerBuilder creates a new SubscriptionTopicResourceTriggerBuilder.
func NewSubscriptionTopicResourceTriggerBuilder() *SubscriptionTopicResourceTriggerBuilder {
	return &SubscriptionTopicResourceTriggerBuilder{
		subscriptionTopicResourceTrigger: &SubscriptionTopicResourceTrigger{},
	}
}

// Build returns the constructed SubscriptionTopicResourceTrigger.
//
// A value, not a pointer: every consumer of a datatype takes one. Patient.Name is
// []HumanName so AddName wants a HumanName, and a pointer field like Range.Low is
// set through SetLow(Quantity), which takes the address itself. Returning *T meant
// writing AddName(*NewHumanNameBuilder()...Build()) — a dereference at every call
// site, to undo a pointer nobody asked for.
func (b *SubscriptionTopicResourceTriggerBuilder) Build() SubscriptionTopicResourceTrigger {
	return *b.subscriptionTopicResourceTrigger
}

// SetId sets the Id field.
func (b *SubscriptionTopicResourceTriggerBuilder) SetId(v string) *SubscriptionTopicResourceTriggerBuilder {
	b.subscriptionTopicResourceTrigger.Id = &v
	return b
}

// AddExtension adds a Extension element.
func (b *SubscriptionTopicResourceTriggerBuilder) AddExtension(v Extension) *SubscriptionTopicResourceTriggerBuilder {
	b.subscriptionTopicResourceTrigger.Extension = append(b.subscriptionTopicResourceTrigger.Extension, v)
	return b
}

// AddModifierExtension adds a ModifierExtension element.
func (b *SubscriptionTopicResourceTriggerBuilder) AddModifierExtension(v Extension) *SubscriptionTopicResourceTriggerBuilder {
	b.subscriptionTopicResourceTrigger.ModifierExtension = append(b.subscriptionTopicResourceTrigger.ModifierExtension, v)
	return b
}

// SetDescription sets the Description field.
func (b *SubscriptionTopicResourceTriggerBuilder) SetDescription(v string) *SubscriptionTopicResourceTriggerBuilder {
	b.subscriptionTopicResourceTrigger.Description = &v
	return b
}

// SetResource sets the Resource field.
func (b *SubscriptionTopicResourceTriggerBuilder) SetResource(v string) *SubscriptionTopicResourceTriggerBuilder {
	b.subscriptionTopicResourceTrigger.Resource = &v
	return b
}

// AddSupportedInteraction adds a SupportedInteraction element.
//
// Takes a plain value: the field is a slice of pointers so that an absent slot
// can be expressed, but a builder call is always adding a value. For a slot that
// is deliberately absent, build the slice directly and leave that entry nil.
func (b *SubscriptionTopicResourceTriggerBuilder) AddSupportedInteraction(v MethodCode) *SubscriptionTopicResourceTriggerBuilder {
	b.subscriptionTopicResourceTrigger.SupportedInteraction = append(b.subscriptionTopicResourceTrigger.SupportedInteraction, &v)
	return b
}

// SetQueryCriteria sets the QueryCriteria field.
func (b *SubscriptionTopicResourceTriggerBuilder) SetQueryCriteria(v SubscriptionTopicResourceTriggerQueryCriteria) *SubscriptionTopicResourceTriggerBuilder {
	b.subscriptionTopicResourceTrigger.QueryCriteria = &v
	return b
}

// SetFhirPathCriteria sets the FhirPathCriteria field.
func (b *SubscriptionTopicResourceTriggerBuilder) SetFhirPathCriteria(v string) *SubscriptionTopicResourceTriggerBuilder {
	b.subscriptionTopicResourceTrigger.FhirPathCriteria = &v
	return b
}

// SetDescriptionExt sets the extensions carried by Description, serialized as
// "_description".
//
// This is how a primitive expresses an extension: a data-absent-reason on a
// birthDate lives here, not on the value.
func (b *SubscriptionTopicResourceTriggerBuilder) SetDescriptionExt(v Element) *SubscriptionTopicResourceTriggerBuilder {
	b.subscriptionTopicResourceTrigger.DescriptionExt = &v
	return b
}

// SetResourceExt sets the extensions carried by Resource, serialized as
// "_resource".
//
// This is how a primitive expresses an extension: a data-absent-reason on a
// birthDate lives here, not on the value.
func (b *SubscriptionTopicResourceTriggerBuilder) SetResourceExt(v Element) *SubscriptionTopicResourceTriggerBuilder {
	b.subscriptionTopicResourceTrigger.ResourceExt = &v
	return b
}

// AddSupportedInteractionExt attaches extensions to the SupportedInteraction element added most
// recently.
//
// The two slices are parallel by position, so any earlier element that has no
// extension is filled in as nil first. Appending blindly instead would put the
// extension at the wrong index: after AddSupportedInteraction twice, a bare append lands at
// position 0 and silently belongs to the first element rather than the second.
//
// A nil value is meaningful and can be passed deliberately: it is a position that
// has no extension.
func (b *SubscriptionTopicResourceTriggerBuilder) AddSupportedInteractionExt(v *Element) *SubscriptionTopicResourceTriggerBuilder {
	for len(b.subscriptionTopicResourceTrigger.SupportedInteractionExt) < len(b.subscriptionTopicResourceTrigger.SupportedInteraction)-1 {
		b.subscriptionTopicResourceTrigger.SupportedInteractionExt = append(b.subscriptionTopicResourceTrigger.SupportedInteractionExt, nil)
	}
	b.subscriptionTopicResourceTrigger.SupportedInteractionExt = append(b.subscriptionTopicResourceTrigger.SupportedInteractionExt, v)
	return b
}

// SetFhirPathCriteriaExt sets the extensions carried by FhirPathCriteria, serialized as
// "_fhirPathCriteria".
//
// This is how a primitive expresses an extension: a data-absent-reason on a
// birthDate lives here, not on the value.
func (b *SubscriptionTopicResourceTriggerBuilder) SetFhirPathCriteriaExt(v Element) *SubscriptionTopicResourceTriggerBuilder {
	b.subscriptionTopicResourceTrigger.FhirPathCriteriaExt = &v
	return b
}

// =============================================================================
// SubscriptionTopicResourceTriggerQueryCriteria - Fluent Builder
// =============================================================================

// SubscriptionTopicResourceTriggerQueryCriteriaBuilder provides a fluent API for constructing SubscriptionTopicResourceTriggerQueryCriteria values.
type SubscriptionTopicResourceTriggerQueryCriteriaBuilder struct {
	subscriptionTopicResourceTriggerQueryCriteria *SubscriptionTopicResourceTriggerQueryCriteria
}

// NewSubscriptionTopicResourceTriggerQueryCriteriaBuilder creates a new SubscriptionTopicResourceTriggerQueryCriteriaBuilder.
func NewSubscriptionTopicResourceTriggerQueryCriteriaBuilder() *SubscriptionTopicResourceTriggerQueryCriteriaBuilder {
	return &SubscriptionTopicResourceTriggerQueryCriteriaBuilder{
		subscriptionTopicResourceTriggerQueryCriteria: &SubscriptionTopicResourceTriggerQueryCriteria{},
	}
}

// Build returns the constructed SubscriptionTopicResourceTriggerQueryCriteria.
//
// A value, not a pointer: every consumer of a datatype takes one. Patient.Name is
// []HumanName so AddName wants a HumanName, and a pointer field like Range.Low is
// set through SetLow(Quantity), which takes the address itself. Returning *T meant
// writing AddName(*NewHumanNameBuilder()...Build()) — a dereference at every call
// site, to undo a pointer nobody asked for.
func (b *SubscriptionTopicResourceTriggerQueryCriteriaBuilder) Build() SubscriptionTopicResourceTriggerQueryCriteria {
	return *b.subscriptionTopicResourceTriggerQueryCriteria
}

// SetId sets the Id field.
func (b *SubscriptionTopicResourceTriggerQueryCriteriaBuilder) SetId(v string) *SubscriptionTopicResourceTriggerQueryCriteriaBuilder {
	b.subscriptionTopicResourceTriggerQueryCriteria.Id = &v
	return b
}

// AddExtension adds a Extension element.
func (b *SubscriptionTopicResourceTriggerQueryCriteriaBuilder) AddExtension(v Extension) *SubscriptionTopicResourceTriggerQueryCriteriaBuilder {
	b.subscriptionTopicResourceTriggerQueryCriteria.Extension = append(b.subscriptionTopicResourceTriggerQueryCriteria.Extension, v)
	return b
}

// AddModifierExtension adds a ModifierExtension element.
func (b *SubscriptionTopicResourceTriggerQueryCriteriaBuilder) AddModifierExtension(v Extension) *SubscriptionTopicResourceTriggerQueryCriteriaBuilder {
	b.subscriptionTopicResourceTriggerQueryCriteria.ModifierExtension = append(b.subscriptionTopicResourceTriggerQueryCriteria.ModifierExtension, v)
	return b
}

// SetPrevious sets the Previous field.
func (b *SubscriptionTopicResourceTriggerQueryCriteriaBuilder) SetPrevious(v string) *SubscriptionTopicResourceTriggerQueryCriteriaBuilder {
	b.subscriptionTopicResourceTriggerQueryCriteria.Previous = &v
	return b
}

// SetResultForCreate sets the ResultForCreate field.
func (b *SubscriptionTopicResourceTriggerQueryCriteriaBuilder) SetResultForCreate(v CriteriaNotExistsBehavior) *SubscriptionTopicResourceTriggerQueryCriteriaBuilder {
	b.subscriptionTopicResourceTriggerQueryCriteria.ResultForCreate = &v
	return b
}

// SetCurrent sets the Current field.
func (b *SubscriptionTopicResourceTriggerQueryCriteriaBuilder) SetCurrent(v string) *SubscriptionTopicResourceTriggerQueryCriteriaBuilder {
	b.subscriptionTopicResourceTriggerQueryCriteria.Current = &v
	return b
}

// SetResultForDelete sets the ResultForDelete field.
func (b *SubscriptionTopicResourceTriggerQueryCriteriaBuilder) SetResultForDelete(v CriteriaNotExistsBehavior) *SubscriptionTopicResourceTriggerQueryCriteriaBuilder {
	b.subscriptionTopicResourceTriggerQueryCriteria.ResultForDelete = &v
	return b
}

// SetRequireBoth sets the RequireBoth field.
func (b *SubscriptionTopicResourceTriggerQueryCriteriaBuilder) SetRequireBoth(v bool) *SubscriptionTopicResourceTriggerQueryCriteriaBuilder {
	b.subscriptionTopicResourceTriggerQueryCriteria.RequireBoth = &v
	return b
}

// SetPreviousExt sets the extensions carried by Previous, serialized as
// "_previous".
//
// This is how a primitive expresses an extension: a data-absent-reason on a
// birthDate lives here, not on the value.
func (b *SubscriptionTopicResourceTriggerQueryCriteriaBuilder) SetPreviousExt(v Element) *SubscriptionTopicResourceTriggerQueryCriteriaBuilder {
	b.subscriptionTopicResourceTriggerQueryCriteria.PreviousExt = &v
	return b
}

// SetResultForCreateExt sets the extensions carried by ResultForCreate, serialized as
// "_resultForCreate".
//
// This is how a primitive expresses an extension: a data-absent-reason on a
// birthDate lives here, not on the value.
func (b *SubscriptionTopicResourceTriggerQueryCriteriaBuilder) SetResultForCreateExt(v Element) *SubscriptionTopicResourceTriggerQueryCriteriaBuilder {
	b.subscriptionTopicResourceTriggerQueryCriteria.ResultForCreateExt = &v
	return b
}

// SetCurrentExt sets the extensions carried by Current, serialized as
// "_current".
//
// This is how a primitive expresses an extension: a data-absent-reason on a
// birthDate lives here, not on the value.
func (b *SubscriptionTopicResourceTriggerQueryCriteriaBuilder) SetCurrentExt(v Element) *SubscriptionTopicResourceTriggerQueryCriteriaBuilder {
	b.subscriptionTopicResourceTriggerQueryCriteria.CurrentExt = &v
	return b
}

// SetResultForDeleteExt sets the extensions carried by ResultForDelete, serialized as
// "_resultForDelete".
//
// This is how a primitive expresses an extension: a data-absent-reason on a
// birthDate lives here, not on the value.
func (b *SubscriptionTopicResourceTriggerQueryCriteriaBuilder) SetResultForDeleteExt(v Element) *SubscriptionTopicResourceTriggerQueryCriteriaBuilder {
	b.subscriptionTopicResourceTriggerQueryCriteria.ResultForDeleteExt = &v
	return b
}

// SetRequireBothExt sets the extensions carried by RequireBoth, serialized as
// "_requireBoth".
//
// This is how a primitive expresses an extension: a data-absent-reason on a
// birthDate lives here, not on the value.
func (b *SubscriptionTopicResourceTriggerQueryCriteriaBuilder) SetRequireBothExt(v Element) *SubscriptionTopicResourceTriggerQueryCriteriaBuilder {
	b.subscriptionTopicResourceTriggerQueryCriteria.RequireBothExt = &v
	return b
}
