// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (consolidated resource)
// Package: r5

package r5

import (
	"bytes"
	"encoding/json"
	"encoding/xml"
	"fmt"
)

// =============================================================================
// ActorDefinition Resource
// =============================================================================

// ActorDefinition represents FHIR ActorDefinition.
type ActorDefinition struct {
	// FHIR resource type
	ResourceType string `json:"resourceType"`
	// Logical id of this artifact
	Id *string `json:"id,omitempty"`
	// Metadata about the resource
	Meta *Meta `json:"meta,omitempty"`
	// A set of rules under which this content was created
	ImplicitRules *string `json:"implicitRules,omitempty"`
	// Extension for ImplicitRules
	ImplicitRulesExt *Element `json:"_implicitRules,omitempty"`
	// Language of the resource content
	Language *string `json:"language,omitempty"`
	// Extension for Language
	LanguageExt *Element `json:"_language,omitempty"`
	// Text summary of the resource, for human interpretation
	Text *Narrative `json:"text,omitempty"`
	// Contained, inline Resources
	Contained []Resource `json:"contained,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Canonical identifier for this actor definition, represented as a URI (globally unique)
	Url *string `json:"url,omitempty"`
	// Extension for Url
	UrlExt *Element `json:"_url,omitempty"`
	// Additional identifier for the actor definition (business identifier)
	Identifier []Identifier `json:"identifier,omitempty"`
	// Business version of the actor definition
	Version *string `json:"version,omitempty"`
	// Extension for Version
	VersionExt *Element `json:"_version,omitempty"`
	// How to compare versions
	VersionAlgorithmString *string `json:"versionAlgorithmString,omitempty"`
	// Extension for VersionAlgorithmString
	VersionAlgorithmStringExt *Element `json:"_versionAlgorithmString,omitempty"`
	// How to compare versions
	VersionAlgorithmCoding *Coding `json:"versionAlgorithmCoding,omitempty"`
	// Name for this actor definition (computer friendly)
	Name *string `json:"name,omitempty"`
	// Extension for Name
	NameExt *Element `json:"_name,omitempty"`
	// Name for this actor definition (human friendly)
	Title *string `json:"title,omitempty"`
	// Extension for Title
	TitleExt *Element `json:"_title,omitempty"`
	// draft | active | retired | unknown
	Status *PublicationStatus `json:"status,omitempty"`
	// Extension for Status
	StatusExt *Element `json:"_status,omitempty"`
	// For testing purposes, not real usage
	Experimental *bool `json:"experimental,omitempty"`
	// Extension for Experimental
	ExperimentalExt *Element `json:"_experimental,omitempty"`
	// Date last changed
	Date *string `json:"date,omitempty"`
	// Extension for Date
	DateExt *Element `json:"_date,omitempty"`
	// Name of the publisher/steward (organization or individual)
	Publisher *string `json:"publisher,omitempty"`
	// Extension for Publisher
	PublisherExt *Element `json:"_publisher,omitempty"`
	// Contact details for the publisher
	Contact []ContactDetail `json:"contact,omitempty"`
	// Natural language description of the actor
	Description *string `json:"description,omitempty"`
	// Extension for Description
	DescriptionExt *Element `json:"_description,omitempty"`
	// The context that the content is intended to support
	UseContext []UsageContext `json:"useContext,omitempty"`
	// Intended jurisdiction for actor definition (if applicable)
	Jurisdiction []CodeableConcept `json:"jurisdiction,omitempty"`
	// Why this actor definition is defined
	Purpose *string `json:"purpose,omitempty"`
	// Extension for Purpose
	PurposeExt *Element `json:"_purpose,omitempty"`
	// Use and/or publishing restrictions
	Copyright *string `json:"copyright,omitempty"`
	// Extension for Copyright
	CopyrightExt *Element `json:"_copyright,omitempty"`
	// Copyright holder and year(s)
	CopyrightLabel *string `json:"copyrightLabel,omitempty"`
	// Extension for CopyrightLabel
	CopyrightLabelExt *Element `json:"_copyrightLabel,omitempty"`
	// person | system
	Type *ExampleScenarioActorType `json:"type,omitempty"`
	// Extension for Type
	TypeExt *Element `json:"_type,omitempty"`
	// Functionality associated with the actor
	Documentation *string `json:"documentation,omitempty"`
	// Extension for Documentation
	DocumentationExt *Element `json:"_documentation,omitempty"`
	// Reference to more information about the actor
	Reference []string `json:"reference,omitempty"`
	// Extension for Reference
	ReferenceExt []Element `json:"_reference,omitempty"`
	// CapabilityStatement for the actor (if applicable)
	Capabilities *string `json:"capabilities,omitempty"`
	// Extension for Capabilities
	CapabilitiesExt *Element `json:"_capabilities,omitempty"`
	// Definition of this actor in another context / IG
	DerivedFrom []string `json:"derivedFrom,omitempty"`
	// Extension for DerivedFrom
	DerivedFromExt []Element `json:"_derivedFrom,omitempty"`
}

// GetResourceType returns the FHIR resource type.
func (r *ActorDefinition) GetResourceType() string {
	return "ActorDefinition"
}

// GetId returns the resource's logical ID.
func (r *ActorDefinition) GetId() *string {
	return r.Id
}

// SetId sets the resource's logical ID.
func (r *ActorDefinition) SetId(id string) {
	r.Id = &id
}

// GetMeta returns the resource's Meta element.
func (r *ActorDefinition) GetMeta() *Meta {
	return r.Meta
}

// SetMeta sets the resource's Meta element.
func (r *ActorDefinition) SetMeta(m *Meta) {
	r.Meta = m
}

// GetText returns the resource's narrative text.
func (r *ActorDefinition) GetText() *Narrative {
	return r.Text
}

// SetText sets the resource's narrative text.
func (r *ActorDefinition) SetText(t *Narrative) {
	r.Text = t
}

// GetContained returns the resource's contained resources.
func (r *ActorDefinition) GetContained() []Resource {
	return r.Contained
}

// GetExtension returns the resource's extensions.
func (r *ActorDefinition) GetExtension() []Extension {
	return r.Extension
}

// GetModifierExtension returns the resource's modifier extensions.
func (r *ActorDefinition) GetModifierExtension() []Extension {
	return r.ModifierExtension
}

// MarshalJSON ensures resourceType is always included in JSON output.
// HTML escaping is disabled to preserve FHIR narrative XHTML content.
//
// Note: Use the package-level Marshal function instead of json.Marshal
// to ensure HTML in narrative text.div fields is not escaped.
func (r ActorDefinition) MarshalJSON() ([]byte, error) {
	r.ResourceType = "ActorDefinition"
	type Alias ActorDefinition
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	if err := enc.Encode((Alias)(r)); err != nil {
		return nil, err
	}
	b := buf.Bytes()
	if len(b) > 0 && b[len(b)-1] == '\n' {
		b = b[:len(b)-1]
	}
	return b, nil
}

// UnmarshalJSON handles deserialization of polymorphic contained resources.
func (r *ActorDefinition) UnmarshalJSON(data []byte) error {
	// Use an alias to avoid infinite recursion
	type Alias ActorDefinition
	aux := &struct {
		Contained []json.RawMessage `json:"contained,omitempty"`
		*Alias
	}{
		Alias: (*Alias)(r),
	}

	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}

	// Unmarshal each contained resource using the dispatcher
	if len(aux.Contained) > 0 {
		r.Contained = make([]Resource, len(aux.Contained))
		for i, raw := range aux.Contained {
			resource, err := UnmarshalResource(raw)
			if err != nil {
				return fmt.Errorf("failed to unmarshal contained[%d]: %w", i, err)
			}
			r.Contained[i] = resource
		}
	}

	return nil
}

// MarshalXML serializes ActorDefinition to FHIR-conformant XML.
func (r ActorDefinition) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if start.Name.Local == "" {
		start.Name.Local = "ActorDefinition"
		start.Name.Space = fhirNamespace
	}
	if err := e.EncodeToken(start); err != nil {
		return err
	}

	if err := xmlEncodePrimitiveString(e, "id", r.Id, nil); err != nil {
		return err
	}
	if r.Meta != nil {
		if err := r.Meta.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "meta"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveString(e, "implicitRules", r.ImplicitRules, r.ImplicitRulesExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveString(e, "language", r.Language, r.LanguageExt); err != nil {
		return err
	}
	if r.Text != nil {
		if err := r.Text.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "text"}}); err != nil {
			return err
		}
	}
	for _, c := range r.Contained {
		if c != nil {
			if err := xmlEncodeContainedResource(e, c); err != nil {
				return err
			}
		}
	}
	for _, item := range r.Extension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "extension"}}); err != nil {
			return err
		}
	}
	for _, item := range r.ModifierExtension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "modifierExtension"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveString(e, "url", r.Url, r.UrlExt); err != nil {
		return err
	}
	for _, item := range r.Identifier {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "identifier"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveString(e, "version", r.Version, r.VersionExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveString(e, "versionAlgorithmString", r.VersionAlgorithmString, nil); err != nil {
		return err
	}
	if r.VersionAlgorithmCoding != nil {
		if err := r.VersionAlgorithmCoding.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "versionAlgorithmCoding"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveString(e, "name", r.Name, r.NameExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveString(e, "title", r.Title, r.TitleExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveCode(e, "status", r.Status, r.StatusExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveBool(e, "experimental", r.Experimental, r.ExperimentalExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveString(e, "date", r.Date, r.DateExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveString(e, "publisher", r.Publisher, r.PublisherExt); err != nil {
		return err
	}
	for _, item := range r.Contact {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "contact"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveString(e, "description", r.Description, r.DescriptionExt); err != nil {
		return err
	}
	for _, item := range r.UseContext {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "useContext"}}); err != nil {
			return err
		}
	}
	for _, item := range r.Jurisdiction {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "jurisdiction"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveString(e, "purpose", r.Purpose, r.PurposeExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveString(e, "copyright", r.Copyright, r.CopyrightExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveString(e, "copyrightLabel", r.CopyrightLabel, r.CopyrightLabelExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveCode(e, "type", r.Type, r.TypeExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveString(e, "documentation", r.Documentation, r.DocumentationExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveStringArray(e, "reference", r.Reference, r.ReferenceExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveString(e, "capabilities", r.Capabilities, r.CapabilitiesExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveStringArray(e, "derivedFrom", r.DerivedFrom, r.DerivedFromExt); err != nil {
		return err
	}

	return e.EncodeToken(start.End())
}

// UnmarshalXML deserializes ActorDefinition from FHIR-conformant XML.
func (r *ActorDefinition) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	for {
		tok, err := d.Token()
		if err != nil {
			return err
		}
		switch t := tok.(type) {
		case xml.StartElement:
			switch t.Name.Local {
			case "id":
				v, _, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Id = v
			case "meta":
				var v Meta
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Meta = &v
			case "implicitRules":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.ImplicitRules = v
				r.ImplicitRulesExt = ext
			case "language":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Language = v
				r.LanguageExt = ext
			case "text":
				var v Narrative
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Text = &v
			case "contained":
				res, err := xmlDecodeContainedResource(d, t)
				if err != nil {
					return err
				}
				if res != nil {
					r.Contained = append(r.Contained, res)
				}
			case "extension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Extension = append(r.Extension, v)
			case "modifierExtension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.ModifierExtension = append(r.ModifierExtension, v)
			case "url":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Url = v
				r.UrlExt = ext
			case "identifier":
				var v Identifier
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Identifier = append(r.Identifier, v)
			case "version":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Version = v
				r.VersionExt = ext
			case "versionAlgorithmString":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.VersionAlgorithmString = v
				_ = ext
			case "versionAlgorithmCoding":
				var v Coding
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.VersionAlgorithmCoding = &v
			case "name":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Name = v
				r.NameExt = ext
			case "title":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Title = v
				r.TitleExt = ext
			case "status":
				v, ext, err := xmlDecodePrimitiveCode[PublicationStatus](d, t)
				if err != nil {
					return err
				}
				r.Status = v
				r.StatusExt = ext
			case "experimental":
				v, ext, err := xmlDecodePrimitiveBool(d, t)
				if err != nil {
					return err
				}
				r.Experimental = v
				r.ExperimentalExt = ext
			case "date":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Date = v
				r.DateExt = ext
			case "publisher":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Publisher = v
				r.PublisherExt = ext
			case "contact":
				var v ContactDetail
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Contact = append(r.Contact, v)
			case "description":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Description = v
				r.DescriptionExt = ext
			case "useContext":
				var v UsageContext
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.UseContext = append(r.UseContext, v)
			case "jurisdiction":
				var v CodeableConcept
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Jurisdiction = append(r.Jurisdiction, v)
			case "purpose":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Purpose = v
				r.PurposeExt = ext
			case "copyright":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Copyright = v
				r.CopyrightExt = ext
			case "copyrightLabel":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.CopyrightLabel = v
				r.CopyrightLabelExt = ext
			case "type":
				v, ext, err := xmlDecodePrimitiveCode[ExampleScenarioActorType](d, t)
				if err != nil {
					return err
				}
				r.Type = v
				r.TypeExt = ext
			case "documentation":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Documentation = v
				r.DocumentationExt = ext
			case "reference":
				v, _, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				if v != nil {
					r.Reference = append(r.Reference, *v)
				}
			case "capabilities":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Capabilities = v
				r.CapabilitiesExt = ext
			case "derivedFrom":
				v, _, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				if v != nil {
					r.DerivedFrom = append(r.DerivedFrom, *v)
				}
			default:
				if err := d.Skip(); err != nil {
					return err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// =============================================================================
// ActorDefinition - Fluent Builder
// =============================================================================

// ActorDefinitionBuilder provides a fluent API for constructing ActorDefinition resources.
type ActorDefinitionBuilder struct {
	actorDefinition *ActorDefinition
}

// NewActorDefinitionBuilder creates a new ActorDefinitionBuilder.
func NewActorDefinitionBuilder() *ActorDefinitionBuilder {
	return &ActorDefinitionBuilder{
		actorDefinition: &ActorDefinition{},
	}
}

// Build returns the constructed ActorDefinition resource.
func (b *ActorDefinitionBuilder) Build() *ActorDefinition {
	return b.actorDefinition
}

// SetId sets the Id field.
func (b *ActorDefinitionBuilder) SetId(v string) *ActorDefinitionBuilder {
	b.actorDefinition.Id = &v
	return b
}

// SetMeta sets the Meta field.
func (b *ActorDefinitionBuilder) SetMeta(v Meta) *ActorDefinitionBuilder {
	b.actorDefinition.Meta = &v
	return b
}

// SetImplicitRules sets the ImplicitRules field.
func (b *ActorDefinitionBuilder) SetImplicitRules(v string) *ActorDefinitionBuilder {
	b.actorDefinition.ImplicitRules = &v
	return b
}

// SetLanguage sets the Language field.
func (b *ActorDefinitionBuilder) SetLanguage(v string) *ActorDefinitionBuilder {
	b.actorDefinition.Language = &v
	return b
}

// SetText sets the Text field.
func (b *ActorDefinitionBuilder) SetText(v Narrative) *ActorDefinitionBuilder {
	b.actorDefinition.Text = &v
	return b
}

// AddContained adds a Contained element.
func (b *ActorDefinitionBuilder) AddContained(v Resource) *ActorDefinitionBuilder {
	b.actorDefinition.Contained = append(b.actorDefinition.Contained, v)
	return b
}

// AddExtension adds a Extension element.
func (b *ActorDefinitionBuilder) AddExtension(v Extension) *ActorDefinitionBuilder {
	b.actorDefinition.Extension = append(b.actorDefinition.Extension, v)
	return b
}

// AddModifierExtension adds a ModifierExtension element.
func (b *ActorDefinitionBuilder) AddModifierExtension(v Extension) *ActorDefinitionBuilder {
	b.actorDefinition.ModifierExtension = append(b.actorDefinition.ModifierExtension, v)
	return b
}

// SetUrl sets the Url field.
func (b *ActorDefinitionBuilder) SetUrl(v string) *ActorDefinitionBuilder {
	b.actorDefinition.Url = &v
	return b
}

// AddIdentifier adds a Identifier element.
func (b *ActorDefinitionBuilder) AddIdentifier(v Identifier) *ActorDefinitionBuilder {
	b.actorDefinition.Identifier = append(b.actorDefinition.Identifier, v)
	return b
}

// SetVersion sets the Version field.
func (b *ActorDefinitionBuilder) SetVersion(v string) *ActorDefinitionBuilder {
	b.actorDefinition.Version = &v
	return b
}

// SetVersionAlgorithmString sets the VersionAlgorithmString field.
func (b *ActorDefinitionBuilder) SetVersionAlgorithmString(v string) *ActorDefinitionBuilder {
	b.actorDefinition.VersionAlgorithmString = &v
	return b
}

// SetVersionAlgorithmStringExt sets the VersionAlgorithmStringExt field.
func (b *ActorDefinitionBuilder) SetVersionAlgorithmStringExt(v Element) *ActorDefinitionBuilder {
	b.actorDefinition.VersionAlgorithmStringExt = &v
	return b
}

// SetVersionAlgorithmCoding sets the VersionAlgorithmCoding field.
func (b *ActorDefinitionBuilder) SetVersionAlgorithmCoding(v Coding) *ActorDefinitionBuilder {
	b.actorDefinition.VersionAlgorithmCoding = &v
	return b
}

// SetName sets the Name field.
func (b *ActorDefinitionBuilder) SetName(v string) *ActorDefinitionBuilder {
	b.actorDefinition.Name = &v
	return b
}

// SetTitle sets the Title field.
func (b *ActorDefinitionBuilder) SetTitle(v string) *ActorDefinitionBuilder {
	b.actorDefinition.Title = &v
	return b
}

// SetStatus sets the Status field.
func (b *ActorDefinitionBuilder) SetStatus(v PublicationStatus) *ActorDefinitionBuilder {
	b.actorDefinition.Status = &v
	return b
}

// SetExperimental sets the Experimental field.
func (b *ActorDefinitionBuilder) SetExperimental(v bool) *ActorDefinitionBuilder {
	b.actorDefinition.Experimental = &v
	return b
}

// SetDate sets the Date field.
func (b *ActorDefinitionBuilder) SetDate(v string) *ActorDefinitionBuilder {
	b.actorDefinition.Date = &v
	return b
}

// SetPublisher sets the Publisher field.
func (b *ActorDefinitionBuilder) SetPublisher(v string) *ActorDefinitionBuilder {
	b.actorDefinition.Publisher = &v
	return b
}

// AddContact adds a Contact element.
func (b *ActorDefinitionBuilder) AddContact(v ContactDetail) *ActorDefinitionBuilder {
	b.actorDefinition.Contact = append(b.actorDefinition.Contact, v)
	return b
}

// SetDescription sets the Description field.
func (b *ActorDefinitionBuilder) SetDescription(v string) *ActorDefinitionBuilder {
	b.actorDefinition.Description = &v
	return b
}

// AddUseContext adds a UseContext element.
func (b *ActorDefinitionBuilder) AddUseContext(v UsageContext) *ActorDefinitionBuilder {
	b.actorDefinition.UseContext = append(b.actorDefinition.UseContext, v)
	return b
}

// AddJurisdiction adds a Jurisdiction element.
func (b *ActorDefinitionBuilder) AddJurisdiction(v CodeableConcept) *ActorDefinitionBuilder {
	b.actorDefinition.Jurisdiction = append(b.actorDefinition.Jurisdiction, v)
	return b
}

// SetPurpose sets the Purpose field.
func (b *ActorDefinitionBuilder) SetPurpose(v string) *ActorDefinitionBuilder {
	b.actorDefinition.Purpose = &v
	return b
}

// SetCopyright sets the Copyright field.
func (b *ActorDefinitionBuilder) SetCopyright(v string) *ActorDefinitionBuilder {
	b.actorDefinition.Copyright = &v
	return b
}

// SetCopyrightLabel sets the CopyrightLabel field.
func (b *ActorDefinitionBuilder) SetCopyrightLabel(v string) *ActorDefinitionBuilder {
	b.actorDefinition.CopyrightLabel = &v
	return b
}

// SetType sets the Type field.
func (b *ActorDefinitionBuilder) SetType(v ExampleScenarioActorType) *ActorDefinitionBuilder {
	b.actorDefinition.Type = &v
	return b
}

// SetDocumentation sets the Documentation field.
func (b *ActorDefinitionBuilder) SetDocumentation(v string) *ActorDefinitionBuilder {
	b.actorDefinition.Documentation = &v
	return b
}

// AddReference adds a Reference element.
func (b *ActorDefinitionBuilder) AddReference(v string) *ActorDefinitionBuilder {
	b.actorDefinition.Reference = append(b.actorDefinition.Reference, v)
	return b
}

// SetCapabilities sets the Capabilities field.
func (b *ActorDefinitionBuilder) SetCapabilities(v string) *ActorDefinitionBuilder {
	b.actorDefinition.Capabilities = &v
	return b
}

// AddDerivedFrom adds a DerivedFrom element.
func (b *ActorDefinitionBuilder) AddDerivedFrom(v string) *ActorDefinitionBuilder {
	b.actorDefinition.DerivedFrom = append(b.actorDefinition.DerivedFrom, v)
	return b
}

// =============================================================================
// ActorDefinition - Functional Options
// =============================================================================

// ActorDefinitionOption is a functional option for configuring a ActorDefinition.
type ActorDefinitionOption func(*ActorDefinition)

// NewActorDefinition creates a new ActorDefinition with the given options.
func NewActorDefinition(opts ...ActorDefinitionOption) *ActorDefinition {
	r := &ActorDefinition{}
	for _, opt := range opts {
		opt(r)
	}
	return r
}

// WithActorDefinitionId sets the Id field.
func WithActorDefinitionId(v string) ActorDefinitionOption {
	return func(r *ActorDefinition) {
		r.Id = &v
	}
}

// WithActorDefinitionMeta sets the Meta field.
func WithActorDefinitionMeta(v Meta) ActorDefinitionOption {
	return func(r *ActorDefinition) {
		r.Meta = &v
	}
}

// WithActorDefinitionImplicitRules sets the ImplicitRules field.
func WithActorDefinitionImplicitRules(v string) ActorDefinitionOption {
	return func(r *ActorDefinition) {
		r.ImplicitRules = &v
	}
}

// WithActorDefinitionLanguage sets the Language field.
func WithActorDefinitionLanguage(v string) ActorDefinitionOption {
	return func(r *ActorDefinition) {
		r.Language = &v
	}
}

// WithActorDefinitionText sets the Text field.
func WithActorDefinitionText(v Narrative) ActorDefinitionOption {
	return func(r *ActorDefinition) {
		r.Text = &v
	}
}

// WithActorDefinitionContained adds a Contained to the ActorDefinition.
func WithActorDefinitionContained(v Resource) ActorDefinitionOption {
	return func(r *ActorDefinition) {
		r.Contained = append(r.Contained, v)
	}
}

// WithActorDefinitionExtension adds a Extension to the ActorDefinition.
func WithActorDefinitionExtension(v Extension) ActorDefinitionOption {
	return func(r *ActorDefinition) {
		r.Extension = append(r.Extension, v)
	}
}

// WithActorDefinitionModifierExtension adds a ModifierExtension to the ActorDefinition.
func WithActorDefinitionModifierExtension(v Extension) ActorDefinitionOption {
	return func(r *ActorDefinition) {
		r.ModifierExtension = append(r.ModifierExtension, v)
	}
}

// WithActorDefinitionUrl sets the Url field.
func WithActorDefinitionUrl(v string) ActorDefinitionOption {
	return func(r *ActorDefinition) {
		r.Url = &v
	}
}

// WithActorDefinitionIdentifier adds a Identifier to the ActorDefinition.
func WithActorDefinitionIdentifier(v Identifier) ActorDefinitionOption {
	return func(r *ActorDefinition) {
		r.Identifier = append(r.Identifier, v)
	}
}

// WithActorDefinitionVersion sets the Version field.
func WithActorDefinitionVersion(v string) ActorDefinitionOption {
	return func(r *ActorDefinition) {
		r.Version = &v
	}
}

// WithActorDefinitionVersionAlgorithmString sets the VersionAlgorithmString field.
func WithActorDefinitionVersionAlgorithmString(v string) ActorDefinitionOption {
	return func(r *ActorDefinition) {
		r.VersionAlgorithmString = &v
	}
}

// WithActorDefinitionVersionAlgorithmStringExt sets the VersionAlgorithmStringExt field.
func WithActorDefinitionVersionAlgorithmStringExt(v Element) ActorDefinitionOption {
	return func(r *ActorDefinition) {
		r.VersionAlgorithmStringExt = &v
	}
}

// WithActorDefinitionVersionAlgorithmCoding sets the VersionAlgorithmCoding field.
func WithActorDefinitionVersionAlgorithmCoding(v Coding) ActorDefinitionOption {
	return func(r *ActorDefinition) {
		r.VersionAlgorithmCoding = &v
	}
}

// WithActorDefinitionName sets the Name field.
func WithActorDefinitionName(v string) ActorDefinitionOption {
	return func(r *ActorDefinition) {
		r.Name = &v
	}
}

// WithActorDefinitionTitle sets the Title field.
func WithActorDefinitionTitle(v string) ActorDefinitionOption {
	return func(r *ActorDefinition) {
		r.Title = &v
	}
}

// WithActorDefinitionStatus sets the Status field.
func WithActorDefinitionStatus(v PublicationStatus) ActorDefinitionOption {
	return func(r *ActorDefinition) {
		r.Status = &v
	}
}

// WithActorDefinitionExperimental sets the Experimental field.
func WithActorDefinitionExperimental(v bool) ActorDefinitionOption {
	return func(r *ActorDefinition) {
		r.Experimental = &v
	}
}

// WithActorDefinitionDate sets the Date field.
func WithActorDefinitionDate(v string) ActorDefinitionOption {
	return func(r *ActorDefinition) {
		r.Date = &v
	}
}

// WithActorDefinitionPublisher sets the Publisher field.
func WithActorDefinitionPublisher(v string) ActorDefinitionOption {
	return func(r *ActorDefinition) {
		r.Publisher = &v
	}
}

// WithActorDefinitionContact adds a Contact to the ActorDefinition.
func WithActorDefinitionContact(v ContactDetail) ActorDefinitionOption {
	return func(r *ActorDefinition) {
		r.Contact = append(r.Contact, v)
	}
}

// WithActorDefinitionDescription sets the Description field.
func WithActorDefinitionDescription(v string) ActorDefinitionOption {
	return func(r *ActorDefinition) {
		r.Description = &v
	}
}

// WithActorDefinitionUseContext adds a UseContext to the ActorDefinition.
func WithActorDefinitionUseContext(v UsageContext) ActorDefinitionOption {
	return func(r *ActorDefinition) {
		r.UseContext = append(r.UseContext, v)
	}
}

// WithActorDefinitionJurisdiction adds a Jurisdiction to the ActorDefinition.
func WithActorDefinitionJurisdiction(v CodeableConcept) ActorDefinitionOption {
	return func(r *ActorDefinition) {
		r.Jurisdiction = append(r.Jurisdiction, v)
	}
}

// WithActorDefinitionPurpose sets the Purpose field.
func WithActorDefinitionPurpose(v string) ActorDefinitionOption {
	return func(r *ActorDefinition) {
		r.Purpose = &v
	}
}

// WithActorDefinitionCopyright sets the Copyright field.
func WithActorDefinitionCopyright(v string) ActorDefinitionOption {
	return func(r *ActorDefinition) {
		r.Copyright = &v
	}
}

// WithActorDefinitionCopyrightLabel sets the CopyrightLabel field.
func WithActorDefinitionCopyrightLabel(v string) ActorDefinitionOption {
	return func(r *ActorDefinition) {
		r.CopyrightLabel = &v
	}
}

// WithActorDefinitionType sets the Type field.
func WithActorDefinitionType(v ExampleScenarioActorType) ActorDefinitionOption {
	return func(r *ActorDefinition) {
		r.Type = &v
	}
}

// WithActorDefinitionDocumentation sets the Documentation field.
func WithActorDefinitionDocumentation(v string) ActorDefinitionOption {
	return func(r *ActorDefinition) {
		r.Documentation = &v
	}
}

// WithActorDefinitionReference adds a Reference to the ActorDefinition.
func WithActorDefinitionReference(v string) ActorDefinitionOption {
	return func(r *ActorDefinition) {
		r.Reference = append(r.Reference, v)
	}
}

// WithActorDefinitionCapabilities sets the Capabilities field.
func WithActorDefinitionCapabilities(v string) ActorDefinitionOption {
	return func(r *ActorDefinition) {
		r.Capabilities = &v
	}
}

// WithActorDefinitionDerivedFrom adds a DerivedFrom to the ActorDefinition.
func WithActorDefinitionDerivedFrom(v string) ActorDefinitionOption {
	return func(r *ActorDefinition) {
		r.DerivedFrom = append(r.DerivedFrom, v)
	}
}
