// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (consolidated resource)
// Package: r4b

package r4b

import (
	"bytes"
	"encoding/json"
	"encoding/xml"
	"fmt"
)

// =============================================================================
// Media Resource
// =============================================================================

// Media represents FHIR Media.
type Media struct {
	// FHIR resource type
	ResourceType string `json:"resourceType"`
	// Logical id of this artifact
	Id *string `json:"id,omitempty"`
	// Metadata about the resource
	Meta *Meta `json:"meta,omitempty"`
	// A set of rules under which this content was created
	ImplicitRules *string `json:"implicitRules,omitempty"`
	// Extension for ImplicitRules
	ImplicitRulesExt *Element `json:"_implicitRules,omitempty"`
	// Language of the resource content
	Language *string `json:"language,omitempty"`
	// Extension for Language
	LanguageExt *Element `json:"_language,omitempty"`
	// Text summary of the resource, for human interpretation
	Text *Narrative `json:"text,omitempty"`
	// Contained, inline Resources
	Contained []Resource `json:"contained,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Identifier(s) for the image
	Identifier []Identifier `json:"identifier,omitempty"`
	// Procedure that caused this media to be created
	BasedOn []Reference `json:"basedOn,omitempty"`
	// Part of referenced event
	PartOf []Reference `json:"partOf,omitempty"`
	// preparation | in-progress | not-done | on-hold | stopped | completed | entered-in-error | unknown
	Status *EventStatus `json:"status,omitempty"`
	// Extension for Status
	StatusExt *Element `json:"_status,omitempty"`
	// Classification of media as image, video, or audio
	Type *CodeableConcept `json:"type,omitempty"`
	// The type of acquisition equipment/process
	Modality *CodeableConcept `json:"modality,omitempty"`
	// Imaging view, e.g. Lateral or Antero-posterior
	View *CodeableConcept `json:"view,omitempty"`
	// Who/What this Media is a record of
	Subject *Reference `json:"subject,omitempty"`
	// Encounter associated with media
	Encounter *Reference `json:"encounter,omitempty"`
	// When Media was collected
	CreatedDateTime *string `json:"createdDateTime,omitempty"`
	// Extension for CreatedDateTime
	CreatedDateTimeExt *Element `json:"_createdDateTime,omitempty"`
	// When Media was collected
	CreatedPeriod *Period `json:"createdPeriod,omitempty"`
	// Date/Time this version was made available
	Issued *string `json:"issued,omitempty"`
	// Extension for Issued
	IssuedExt *Element `json:"_issued,omitempty"`
	// The person who generated the image
	Operator *Reference `json:"operator,omitempty"`
	// Why was event performed?
	ReasonCode []CodeableConcept `json:"reasonCode,omitempty"`
	// Observed body part
	BodySite *CodeableConcept `json:"bodySite,omitempty"`
	// Name of the device/manufacturer
	DeviceName *string `json:"deviceName,omitempty"`
	// Extension for DeviceName
	DeviceNameExt *Element `json:"_deviceName,omitempty"`
	// Observing Device
	Device *Reference `json:"device,omitempty"`
	// Height of the image in pixels (photo/video)
	Height *uint32 `json:"height,omitempty"`
	// Extension for Height
	HeightExt *Element `json:"_height,omitempty"`
	// Width of the image in pixels (photo/video)
	Width *uint32 `json:"width,omitempty"`
	// Extension for Width
	WidthExt *Element `json:"_width,omitempty"`
	// Number of frames if > 1 (photo)
	Frames *uint32 `json:"frames,omitempty"`
	// Extension for Frames
	FramesExt *Element `json:"_frames,omitempty"`
	// Length in seconds (audio / video)
	Duration *Decimal `json:"duration,omitempty"`
	// Extension for Duration
	DurationExt *Element `json:"_duration,omitempty"`
	// Actual Media - reference or data
	Content Attachment `json:"content"`
	// Comments made about the media
	Note []Annotation `json:"note,omitempty"`
}

// GetResourceType returns the FHIR resource type.
func (r *Media) GetResourceType() string {
	return "Media"
}

// GetId returns the resource's logical ID.
func (r *Media) GetId() *string {
	return r.Id
}

// SetId sets the resource's logical ID.
func (r *Media) SetId(id string) {
	r.Id = &id
}

// GetMeta returns the resource's Meta element.
func (r *Media) GetMeta() *Meta {
	return r.Meta
}

// SetMeta sets the resource's Meta element.
func (r *Media) SetMeta(m *Meta) {
	r.Meta = m
}

// GetText returns the resource's narrative text.
func (r *Media) GetText() *Narrative {
	return r.Text
}

// SetText sets the resource's narrative text.
func (r *Media) SetText(t *Narrative) {
	r.Text = t
}

// GetContained returns the resource's contained resources.
func (r *Media) GetContained() []Resource {
	return r.Contained
}

// GetExtension returns the resource's extensions.
func (r *Media) GetExtension() []Extension {
	return r.Extension
}

// GetModifierExtension returns the resource's modifier extensions.
func (r *Media) GetModifierExtension() []Extension {
	return r.ModifierExtension
}

// MarshalJSON ensures resourceType is always included in JSON output.
// HTML escaping is disabled to preserve FHIR narrative XHTML content.
//
// Note: Use the package-level Marshal function instead of json.Marshal
// to ensure HTML in narrative text.div fields is not escaped.
func (r Media) MarshalJSON() ([]byte, error) {
	r.ResourceType = "Media"
	type Alias Media
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	if err := enc.Encode((Alias)(r)); err != nil {
		return nil, err
	}
	b := buf.Bytes()
	if len(b) > 0 && b[len(b)-1] == '\n' {
		b = b[:len(b)-1]
	}
	return b, nil
}

// UnmarshalJSON handles deserialization of polymorphic contained resources.
func (r *Media) UnmarshalJSON(data []byte) error {
	// Use an alias to avoid infinite recursion
	type Alias Media
	aux := &struct {
		Contained []json.RawMessage `json:"contained,omitempty"`
		*Alias
	}{
		Alias: (*Alias)(r),
	}

	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}

	// Unmarshal each contained resource using the dispatcher
	if len(aux.Contained) > 0 {
		r.Contained = make([]Resource, len(aux.Contained))
		for i, raw := range aux.Contained {
			resource, err := UnmarshalResource(raw)
			if err != nil {
				return fmt.Errorf("failed to unmarshal contained[%d]: %w", i, err)
			}
			r.Contained[i] = resource
		}
	}

	return nil
}

// MarshalXML serializes Media to FHIR-conformant XML.
func (r Media) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if start.Name.Local == "" {
		start.Name.Local = "Media"
		start.Name.Space = fhirNamespace
	}
	if err := e.EncodeToken(start); err != nil {
		return err
	}

	if err := xmlEncodePrimitiveString(e, "id", r.Id, nil); err != nil {
		return err
	}
	if r.Meta != nil {
		if err := r.Meta.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "meta"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveString(e, "implicitRules", r.ImplicitRules, r.ImplicitRulesExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveString(e, "language", r.Language, r.LanguageExt); err != nil {
		return err
	}
	if r.Text != nil {
		if err := r.Text.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "text"}}); err != nil {
			return err
		}
	}
	for _, c := range r.Contained {
		if c != nil {
			if err := xmlEncodeContainedResource(e, c); err != nil {
				return err
			}
		}
	}
	for _, item := range r.Extension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "extension"}}); err != nil {
			return err
		}
	}
	for _, item := range r.ModifierExtension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "modifierExtension"}}); err != nil {
			return err
		}
	}
	for _, item := range r.Identifier {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "identifier"}}); err != nil {
			return err
		}
	}
	for _, item := range r.BasedOn {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "basedOn"}}); err != nil {
			return err
		}
	}
	for _, item := range r.PartOf {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "partOf"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveCode(e, "status", r.Status, r.StatusExt); err != nil {
		return err
	}
	if r.Type != nil {
		if err := r.Type.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "type"}}); err != nil {
			return err
		}
	}
	if r.Modality != nil {
		if err := r.Modality.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "modality"}}); err != nil {
			return err
		}
	}
	if r.View != nil {
		if err := r.View.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "view"}}); err != nil {
			return err
		}
	}
	if r.Subject != nil {
		if err := r.Subject.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "subject"}}); err != nil {
			return err
		}
	}
	if r.Encounter != nil {
		if err := r.Encounter.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "encounter"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveString(e, "createdDateTime", r.CreatedDateTime, nil); err != nil {
		return err
	}
	if r.CreatedPeriod != nil {
		if err := r.CreatedPeriod.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "createdPeriod"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveString(e, "issued", r.Issued, r.IssuedExt); err != nil {
		return err
	}
	if r.Operator != nil {
		if err := r.Operator.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "operator"}}); err != nil {
			return err
		}
	}
	for _, item := range r.ReasonCode {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "reasonCode"}}); err != nil {
			return err
		}
	}
	if r.BodySite != nil {
		if err := r.BodySite.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "bodySite"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveString(e, "deviceName", r.DeviceName, r.DeviceNameExt); err != nil {
		return err
	}
	if r.Device != nil {
		if err := r.Device.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "device"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveUint32(e, "height", r.Height, r.HeightExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveUint32(e, "width", r.Width, r.WidthExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveUint32(e, "frames", r.Frames, r.FramesExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveDecimal(e, "duration", r.Duration, r.DurationExt); err != nil {
		return err
	}
	if err := r.Content.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "content"}}); err != nil {
		return err
	}
	for _, item := range r.Note {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "note"}}); err != nil {
			return err
		}
	}

	return e.EncodeToken(start.End())
}

// UnmarshalXML deserializes Media from FHIR-conformant XML.
func (r *Media) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	for {
		tok, err := d.Token()
		if err != nil {
			return err
		}
		switch t := tok.(type) {
		case xml.StartElement:
			switch t.Name.Local {
			case "id":
				v, _, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Id = v
			case "meta":
				var v Meta
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Meta = &v
			case "implicitRules":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.ImplicitRules = v
				r.ImplicitRulesExt = ext
			case "language":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Language = v
				r.LanguageExt = ext
			case "text":
				var v Narrative
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Text = &v
			case "contained":
				res, err := xmlDecodeContainedResource(d, t)
				if err != nil {
					return err
				}
				if res != nil {
					r.Contained = append(r.Contained, res)
				}
			case "extension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Extension = append(r.Extension, v)
			case "modifierExtension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.ModifierExtension = append(r.ModifierExtension, v)
			case "identifier":
				var v Identifier
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Identifier = append(r.Identifier, v)
			case "basedOn":
				var v Reference
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.BasedOn = append(r.BasedOn, v)
			case "partOf":
				var v Reference
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.PartOf = append(r.PartOf, v)
			case "status":
				v, ext, err := xmlDecodePrimitiveCode[EventStatus](d, t)
				if err != nil {
					return err
				}
				r.Status = v
				r.StatusExt = ext
			case "type":
				var v CodeableConcept
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Type = &v
			case "modality":
				var v CodeableConcept
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Modality = &v
			case "view":
				var v CodeableConcept
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.View = &v
			case "subject":
				var v Reference
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Subject = &v
			case "encounter":
				var v Reference
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Encounter = &v
			case "createdDateTime":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.CreatedDateTime = v
				_ = ext
			case "createdPeriod":
				var v Period
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.CreatedPeriod = &v
			case "issued":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Issued = v
				r.IssuedExt = ext
			case "operator":
				var v Reference
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Operator = &v
			case "reasonCode":
				var v CodeableConcept
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.ReasonCode = append(r.ReasonCode, v)
			case "bodySite":
				var v CodeableConcept
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.BodySite = &v
			case "deviceName":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.DeviceName = v
				r.DeviceNameExt = ext
			case "device":
				var v Reference
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Device = &v
			case "height":
				v, ext, err := xmlDecodePrimitiveUint32(d, t)
				if err != nil {
					return err
				}
				r.Height = v
				r.HeightExt = ext
			case "width":
				v, ext, err := xmlDecodePrimitiveUint32(d, t)
				if err != nil {
					return err
				}
				r.Width = v
				r.WidthExt = ext
			case "frames":
				v, ext, err := xmlDecodePrimitiveUint32(d, t)
				if err != nil {
					return err
				}
				r.Frames = v
				r.FramesExt = ext
			case "duration":
				v, ext, err := xmlDecodePrimitiveDecimal(d, t)
				if err != nil {
					return err
				}
				r.Duration = v
				r.DurationExt = ext
			case "content":
				if err := r.Content.UnmarshalXML(d, t); err != nil {
					return err
				}
			case "note":
				var v Annotation
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Note = append(r.Note, v)
			default:
				if err := d.Skip(); err != nil {
					return err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// =============================================================================
// Media - Fluent Builder
// =============================================================================

// MediaBuilder provides a fluent API for constructing Media resources.
type MediaBuilder struct {
	media *Media
}

// NewMediaBuilder creates a new MediaBuilder.
func NewMediaBuilder() *MediaBuilder {
	return &MediaBuilder{
		media: &Media{},
	}
}

// Build returns the constructed Media resource.
func (b *MediaBuilder) Build() *Media {
	return b.media
}

// SetId sets the Id field.
func (b *MediaBuilder) SetId(v string) *MediaBuilder {
	b.media.Id = &v
	return b
}

// SetMeta sets the Meta field.
func (b *MediaBuilder) SetMeta(v Meta) *MediaBuilder {
	b.media.Meta = &v
	return b
}

// SetImplicitRules sets the ImplicitRules field.
func (b *MediaBuilder) SetImplicitRules(v string) *MediaBuilder {
	b.media.ImplicitRules = &v
	return b
}

// SetLanguage sets the Language field.
func (b *MediaBuilder) SetLanguage(v string) *MediaBuilder {
	b.media.Language = &v
	return b
}

// SetText sets the Text field.
func (b *MediaBuilder) SetText(v Narrative) *MediaBuilder {
	b.media.Text = &v
	return b
}

// AddContained adds a Contained element.
func (b *MediaBuilder) AddContained(v Resource) *MediaBuilder {
	b.media.Contained = append(b.media.Contained, v)
	return b
}

// AddExtension adds a Extension element.
func (b *MediaBuilder) AddExtension(v Extension) *MediaBuilder {
	b.media.Extension = append(b.media.Extension, v)
	return b
}

// AddModifierExtension adds a ModifierExtension element.
func (b *MediaBuilder) AddModifierExtension(v Extension) *MediaBuilder {
	b.media.ModifierExtension = append(b.media.ModifierExtension, v)
	return b
}

// AddIdentifier adds a Identifier element.
func (b *MediaBuilder) AddIdentifier(v Identifier) *MediaBuilder {
	b.media.Identifier = append(b.media.Identifier, v)
	return b
}

// AddBasedOn adds a BasedOn element.
func (b *MediaBuilder) AddBasedOn(v Reference) *MediaBuilder {
	b.media.BasedOn = append(b.media.BasedOn, v)
	return b
}

// AddPartOf adds a PartOf element.
func (b *MediaBuilder) AddPartOf(v Reference) *MediaBuilder {
	b.media.PartOf = append(b.media.PartOf, v)
	return b
}

// SetStatus sets the Status field.
func (b *MediaBuilder) SetStatus(v EventStatus) *MediaBuilder {
	b.media.Status = &v
	return b
}

// SetType sets the Type field.
func (b *MediaBuilder) SetType(v CodeableConcept) *MediaBuilder {
	b.media.Type = &v
	return b
}

// SetModality sets the Modality field.
func (b *MediaBuilder) SetModality(v CodeableConcept) *MediaBuilder {
	b.media.Modality = &v
	return b
}

// SetView sets the View field.
func (b *MediaBuilder) SetView(v CodeableConcept) *MediaBuilder {
	b.media.View = &v
	return b
}

// SetSubject sets the Subject field.
func (b *MediaBuilder) SetSubject(v Reference) *MediaBuilder {
	b.media.Subject = &v
	return b
}

// SetEncounter sets the Encounter field.
func (b *MediaBuilder) SetEncounter(v Reference) *MediaBuilder {
	b.media.Encounter = &v
	return b
}

// SetCreatedDateTime sets the CreatedDateTime field.
func (b *MediaBuilder) SetCreatedDateTime(v string) *MediaBuilder {
	b.media.CreatedDateTime = &v
	return b
}

// SetCreatedDateTimeExt sets the CreatedDateTimeExt field.
func (b *MediaBuilder) SetCreatedDateTimeExt(v Element) *MediaBuilder {
	b.media.CreatedDateTimeExt = &v
	return b
}

// SetCreatedPeriod sets the CreatedPeriod field.
func (b *MediaBuilder) SetCreatedPeriod(v Period) *MediaBuilder {
	b.media.CreatedPeriod = &v
	return b
}

// SetIssued sets the Issued field.
func (b *MediaBuilder) SetIssued(v string) *MediaBuilder {
	b.media.Issued = &v
	return b
}

// SetOperator sets the Operator field.
func (b *MediaBuilder) SetOperator(v Reference) *MediaBuilder {
	b.media.Operator = &v
	return b
}

// AddReasonCode adds a ReasonCode element.
func (b *MediaBuilder) AddReasonCode(v CodeableConcept) *MediaBuilder {
	b.media.ReasonCode = append(b.media.ReasonCode, v)
	return b
}

// SetBodySite sets the BodySite field.
func (b *MediaBuilder) SetBodySite(v CodeableConcept) *MediaBuilder {
	b.media.BodySite = &v
	return b
}

// SetDeviceName sets the DeviceName field.
func (b *MediaBuilder) SetDeviceName(v string) *MediaBuilder {
	b.media.DeviceName = &v
	return b
}

// SetDevice sets the Device field.
func (b *MediaBuilder) SetDevice(v Reference) *MediaBuilder {
	b.media.Device = &v
	return b
}

// SetHeight sets the Height field.
func (b *MediaBuilder) SetHeight(v uint32) *MediaBuilder {
	b.media.Height = &v
	return b
}

// SetWidth sets the Width field.
func (b *MediaBuilder) SetWidth(v uint32) *MediaBuilder {
	b.media.Width = &v
	return b
}

// SetFrames sets the Frames field.
func (b *MediaBuilder) SetFrames(v uint32) *MediaBuilder {
	b.media.Frames = &v
	return b
}

// SetDuration sets the Duration field.
func (b *MediaBuilder) SetDuration(v Decimal) *MediaBuilder {
	b.media.Duration = &v
	return b
}

// SetContent sets the Content field.
func (b *MediaBuilder) SetContent(v Attachment) *MediaBuilder {
	b.media.Content = v
	return b
}

// AddNote adds a Note element.
func (b *MediaBuilder) AddNote(v Annotation) *MediaBuilder {
	b.media.Note = append(b.media.Note, v)
	return b
}

// =============================================================================
// Media - Functional Options
// =============================================================================

// MediaOption is a functional option for configuring a Media.
type MediaOption func(*Media)

// NewMedia creates a new Media with the given options.
func NewMedia(opts ...MediaOption) *Media {
	r := &Media{}
	for _, opt := range opts {
		opt(r)
	}
	return r
}

// WithMediaId sets the Id field.
func WithMediaId(v string) MediaOption {
	return func(r *Media) {
		r.Id = &v
	}
}

// WithMediaMeta sets the Meta field.
func WithMediaMeta(v Meta) MediaOption {
	return func(r *Media) {
		r.Meta = &v
	}
}

// WithMediaImplicitRules sets the ImplicitRules field.
func WithMediaImplicitRules(v string) MediaOption {
	return func(r *Media) {
		r.ImplicitRules = &v
	}
}

// WithMediaLanguage sets the Language field.
func WithMediaLanguage(v string) MediaOption {
	return func(r *Media) {
		r.Language = &v
	}
}

// WithMediaText sets the Text field.
func WithMediaText(v Narrative) MediaOption {
	return func(r *Media) {
		r.Text = &v
	}
}

// WithMediaContained adds a Contained to the Media.
func WithMediaContained(v Resource) MediaOption {
	return func(r *Media) {
		r.Contained = append(r.Contained, v)
	}
}

// WithMediaExtension adds a Extension to the Media.
func WithMediaExtension(v Extension) MediaOption {
	return func(r *Media) {
		r.Extension = append(r.Extension, v)
	}
}

// WithMediaModifierExtension adds a ModifierExtension to the Media.
func WithMediaModifierExtension(v Extension) MediaOption {
	return func(r *Media) {
		r.ModifierExtension = append(r.ModifierExtension, v)
	}
}

// WithMediaIdentifier adds a Identifier to the Media.
func WithMediaIdentifier(v Identifier) MediaOption {
	return func(r *Media) {
		r.Identifier = append(r.Identifier, v)
	}
}

// WithMediaBasedOn adds a BasedOn to the Media.
func WithMediaBasedOn(v Reference) MediaOption {
	return func(r *Media) {
		r.BasedOn = append(r.BasedOn, v)
	}
}

// WithMediaPartOf adds a PartOf to the Media.
func WithMediaPartOf(v Reference) MediaOption {
	return func(r *Media) {
		r.PartOf = append(r.PartOf, v)
	}
}

// WithMediaStatus sets the Status field.
func WithMediaStatus(v EventStatus) MediaOption {
	return func(r *Media) {
		r.Status = &v
	}
}

// WithMediaType sets the Type field.
func WithMediaType(v CodeableConcept) MediaOption {
	return func(r *Media) {
		r.Type = &v
	}
}

// WithMediaModality sets the Modality field.
func WithMediaModality(v CodeableConcept) MediaOption {
	return func(r *Media) {
		r.Modality = &v
	}
}

// WithMediaView sets the View field.
func WithMediaView(v CodeableConcept) MediaOption {
	return func(r *Media) {
		r.View = &v
	}
}

// WithMediaSubject sets the Subject field.
func WithMediaSubject(v Reference) MediaOption {
	return func(r *Media) {
		r.Subject = &v
	}
}

// WithMediaEncounter sets the Encounter field.
func WithMediaEncounter(v Reference) MediaOption {
	return func(r *Media) {
		r.Encounter = &v
	}
}

// WithMediaCreatedDateTime sets the CreatedDateTime field.
func WithMediaCreatedDateTime(v string) MediaOption {
	return func(r *Media) {
		r.CreatedDateTime = &v
	}
}

// WithMediaCreatedDateTimeExt sets the CreatedDateTimeExt field.
func WithMediaCreatedDateTimeExt(v Element) MediaOption {
	return func(r *Media) {
		r.CreatedDateTimeExt = &v
	}
}

// WithMediaCreatedPeriod sets the CreatedPeriod field.
func WithMediaCreatedPeriod(v Period) MediaOption {
	return func(r *Media) {
		r.CreatedPeriod = &v
	}
}

// WithMediaIssued sets the Issued field.
func WithMediaIssued(v string) MediaOption {
	return func(r *Media) {
		r.Issued = &v
	}
}

// WithMediaOperator sets the Operator field.
func WithMediaOperator(v Reference) MediaOption {
	return func(r *Media) {
		r.Operator = &v
	}
}

// WithMediaReasonCode adds a ReasonCode to the Media.
func WithMediaReasonCode(v CodeableConcept) MediaOption {
	return func(r *Media) {
		r.ReasonCode = append(r.ReasonCode, v)
	}
}

// WithMediaBodySite sets the BodySite field.
func WithMediaBodySite(v CodeableConcept) MediaOption {
	return func(r *Media) {
		r.BodySite = &v
	}
}

// WithMediaDeviceName sets the DeviceName field.
func WithMediaDeviceName(v string) MediaOption {
	return func(r *Media) {
		r.DeviceName = &v
	}
}

// WithMediaDevice sets the Device field.
func WithMediaDevice(v Reference) MediaOption {
	return func(r *Media) {
		r.Device = &v
	}
}

// WithMediaHeight sets the Height field.
func WithMediaHeight(v uint32) MediaOption {
	return func(r *Media) {
		r.Height = &v
	}
}

// WithMediaWidth sets the Width field.
func WithMediaWidth(v uint32) MediaOption {
	return func(r *Media) {
		r.Width = &v
	}
}

// WithMediaFrames sets the Frames field.
func WithMediaFrames(v uint32) MediaOption {
	return func(r *Media) {
		r.Frames = &v
	}
}

// WithMediaDuration sets the Duration field.
func WithMediaDuration(v Decimal) MediaOption {
	return func(r *Media) {
		r.Duration = &v
	}
}

// WithMediaContent sets the Content field.
func WithMediaContent(v Attachment) MediaOption {
	return func(r *Media) {
		r.Content = v
	}
}

// WithMediaNote adds a Note to the Media.
func WithMediaNote(v Annotation) MediaOption {
	return func(r *Media) {
		r.Note = append(r.Note, v)
	}
}
