// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (consolidated resource)
// Package: r4b

package r4b

import (
	"encoding/xml"
)

// =============================================================================
// StructureDefinition Resource
// =============================================================================

// structureDefinitionTypeMarker occupies no memory and serializes as the constant
// "StructureDefinition". It replaces a string field that a per-resource MarshalJSON had
// to overwrite on every call, which cost a second bytes.Buffer and json.Encoder
// per resource and, because a promoted MarshalJSON wins over the outer struct,
// silently dropped the fields of any type embedding this one.
//
// Nothing needs to set it: the zero value is correct, and GetResourceType()
// returns the same constant.
type structureDefinitionTypeMarker struct{}

// MarshalJSON writes the resource type as a JSON string.
func (structureDefinitionTypeMarker) MarshalJSON() ([]byte, error) {
	return []byte(`"StructureDefinition"`), nil
}

// UnmarshalJSON accepts and discards whatever the document carried. The type is
// fixed by the Go type itself, so a mismatched or absent value is not an error
// here — UnmarshalResource is what validates it during dispatch.
func (*structureDefinitionTypeMarker) UnmarshalJSON([]byte) error { return nil }

// StructureDefinition represents FHIR StructureDefinition.
type StructureDefinition struct {
	// FHIR resource type. Emitted automatically; see structureDefinitionTypeMarker.
	ResourceType structureDefinitionTypeMarker `json:"resourceType"`
	// Logical id of this artifact
	Id *string `json:"id,omitempty"`
	// Metadata about the resource
	Meta *Meta `json:"meta,omitempty"`
	// A set of rules under which this content was created
	ImplicitRules *string `json:"implicitRules,omitempty"`
	// Extension for ImplicitRules
	ImplicitRulesExt *Element `json:"_implicitRules,omitempty"`
	// Language of the resource content
	Language *string `json:"language,omitempty"`
	// Extension for Language
	LanguageExt *Element `json:"_language,omitempty"`
	// Text summary of the resource, for human interpretation
	Text *Narrative `json:"text,omitempty"`
	// Contained, inline Resources
	Contained ContainedList `json:"contained,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Canonical identifier for this structure definition, represented as a URI (globally unique)
	Url *string `json:"url,omitempty"`
	// Extension for Url
	UrlExt *Element `json:"_url,omitempty"`
	// Additional identifier for the structure definition
	Identifier []Identifier `json:"identifier,omitempty"`
	// Business version of the structure definition
	Version *string `json:"version,omitempty"`
	// Extension for Version
	VersionExt *Element `json:"_version,omitempty"`
	// Name for this structure definition (computer friendly)
	Name *string `json:"name,omitempty"`
	// Extension for Name
	NameExt *Element `json:"_name,omitempty"`
	// Name for this structure definition (human friendly)
	Title *string `json:"title,omitempty"`
	// Extension for Title
	TitleExt *Element `json:"_title,omitempty"`
	// draft | active | retired | unknown
	Status *PublicationStatus `json:"status,omitempty"`
	// Extension for Status
	StatusExt *Element `json:"_status,omitempty"`
	// For testing purposes, not real usage
	Experimental *bool `json:"experimental,omitempty"`
	// Extension for Experimental
	ExperimentalExt *Element `json:"_experimental,omitempty"`
	// Date last changed
	Date *string `json:"date,omitempty"`
	// Extension for Date
	DateExt *Element `json:"_date,omitempty"`
	// Name of the publisher (organization or individual)
	Publisher *string `json:"publisher,omitempty"`
	// Extension for Publisher
	PublisherExt *Element `json:"_publisher,omitempty"`
	// Contact details for the publisher
	Contact []ContactDetail `json:"contact,omitempty"`
	// Natural language description of the structure definition
	Description *string `json:"description,omitempty"`
	// Extension for Description
	DescriptionExt *Element `json:"_description,omitempty"`
	// The context that the content is intended to support
	UseContext []UsageContext `json:"useContext,omitempty"`
	// Intended jurisdiction for structure definition (if applicable)
	Jurisdiction []CodeableConcept `json:"jurisdiction,omitempty"`
	// Why this structure definition is defined
	Purpose *string `json:"purpose,omitempty"`
	// Extension for Purpose
	PurposeExt *Element `json:"_purpose,omitempty"`
	// Use and/or publishing restrictions
	Copyright *string `json:"copyright,omitempty"`
	// Extension for Copyright
	CopyrightExt *Element `json:"_copyright,omitempty"`
	// Assist with indexing and finding
	Keyword []Coding `json:"keyword,omitempty"`
	// FHIR Version this StructureDefinition targets
	FhirVersion *FHIRVersion `json:"fhirVersion,omitempty"`
	// Extension for FhirVersion
	FhirVersionExt *Element `json:"_fhirVersion,omitempty"`
	// External specification that the content is mapped to
	Mapping []StructureDefinitionMapping `json:"mapping,omitempty"`
	// primitive-type | complex-type | resource | logical
	Kind *StructureDefinitionKind `json:"kind,omitempty"`
	// Extension for Kind
	KindExt *Element `json:"_kind,omitempty"`
	// Whether the structure is abstract
	Abstract *bool `json:"abstract,omitempty"`
	// Extension for Abstract
	AbstractExt *Element `json:"_abstract,omitempty"`
	// If an extension, where it can be used in instances
	Context []StructureDefinitionContext `json:"context,omitempty"`
	// FHIRPath invariants - when the extension can be used
	ContextInvariant []*string `json:"contextInvariant,omitempty"`
	// Extension for ContextInvariant
	ContextInvariantExt []*Element `json:"_contextInvariant,omitempty"`
	// Type defined or constrained by this structure
	Type *string `json:"type,omitempty"`
	// Extension for Type
	TypeExt *Element `json:"_type,omitempty"`
	// Definition that this type is constrained/specialized from
	BaseDefinition *string `json:"baseDefinition,omitempty"`
	// Extension for BaseDefinition
	BaseDefinitionExt *Element `json:"_baseDefinition,omitempty"`
	// specialization | constraint - How relates to base definition
	Derivation *TypeDerivationRule `json:"derivation,omitempty"`
	// Extension for Derivation
	DerivationExt *Element `json:"_derivation,omitempty"`
	// Snapshot view of the structure
	Snapshot *StructureDefinitionSnapshot `json:"snapshot,omitempty"`
	// Differential view of the structure
	Differential *StructureDefinitionDifferential `json:"differential,omitempty"`
}

// GetResourceType returns the FHIR resource type.
func (r *StructureDefinition) GetResourceType() string {
	return "StructureDefinition"
}

// GetId returns the resource's logical ID.
func (r *StructureDefinition) GetId() *string {
	return r.Id
}

// SetId sets the resource's logical ID.
func (r *StructureDefinition) SetId(id string) {
	r.Id = &id
}

// GetMeta returns the resource's Meta element.
func (r *StructureDefinition) GetMeta() *Meta {
	return r.Meta
}

// SetMeta sets the resource's Meta element.
func (r *StructureDefinition) SetMeta(m *Meta) {
	r.Meta = m
}

// GetText returns the resource's narrative text.
func (r *StructureDefinition) GetText() *Narrative {
	return r.Text
}

// SetText sets the resource's narrative text.
func (r *StructureDefinition) SetText(t *Narrative) {
	r.Text = t
}

// GetContained returns the resource's contained resources.
func (r *StructureDefinition) GetContained() []Resource {
	return r.Contained
}

// GetExtension returns the resource's extensions.
func (r *StructureDefinition) GetExtension() []Extension {
	return r.Extension
}

// GetModifierExtension returns the resource's modifier extensions.
func (r *StructureDefinition) GetModifierExtension() []Extension {
	return r.ModifierExtension
}

// MarshalXML serializes StructureDefinition to FHIR-conformant XML.
func (r StructureDefinition) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if start.Name.Local == "" {
		start.Name.Local = "StructureDefinition"
		start.Name.Space = fhirNamespace
	}
	if err := e.EncodeToken(start); err != nil {
		return err
	}

	if err := xmlEncodePrimitiveString(e, "id", r.Id, nil); err != nil {
		return err
	}
	if r.Meta != nil {
		if err := r.Meta.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "meta"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveString(e, "implicitRules", r.ImplicitRules, r.ImplicitRulesExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveString(e, "language", r.Language, r.LanguageExt); err != nil {
		return err
	}
	if r.Text != nil {
		if err := r.Text.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "text"}}); err != nil {
			return err
		}
	}
	for _, c := range r.Contained {
		if c != nil {
			if err := xmlEncodeContainedResource(e, c); err != nil {
				return err
			}
		}
	}
	for _, item := range r.Extension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "extension"}}); err != nil {
			return err
		}
	}
	for _, item := range r.ModifierExtension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "modifierExtension"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveString(e, "url", r.Url, r.UrlExt); err != nil {
		return err
	}
	for _, item := range r.Identifier {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "identifier"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveString(e, "version", r.Version, r.VersionExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveString(e, "name", r.Name, r.NameExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveString(e, "title", r.Title, r.TitleExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveCode(e, "status", r.Status, r.StatusExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveBool(e, "experimental", r.Experimental, r.ExperimentalExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveString(e, "date", r.Date, r.DateExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveString(e, "publisher", r.Publisher, r.PublisherExt); err != nil {
		return err
	}
	for _, item := range r.Contact {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "contact"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveString(e, "description", r.Description, r.DescriptionExt); err != nil {
		return err
	}
	for _, item := range r.UseContext {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "useContext"}}); err != nil {
			return err
		}
	}
	for _, item := range r.Jurisdiction {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "jurisdiction"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveString(e, "purpose", r.Purpose, r.PurposeExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveString(e, "copyright", r.Copyright, r.CopyrightExt); err != nil {
		return err
	}
	for _, item := range r.Keyword {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "keyword"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveCode(e, "fhirVersion", r.FhirVersion, r.FhirVersionExt); err != nil {
		return err
	}
	for _, item := range r.Mapping {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "mapping"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveCode(e, "kind", r.Kind, r.KindExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveBool(e, "abstract", r.Abstract, r.AbstractExt); err != nil {
		return err
	}
	for _, item := range r.Context {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "context"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveStringArray(e, "contextInvariant", r.ContextInvariant, r.ContextInvariantExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveString(e, "type", r.Type, r.TypeExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveString(e, "baseDefinition", r.BaseDefinition, r.BaseDefinitionExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveCode(e, "derivation", r.Derivation, r.DerivationExt); err != nil {
		return err
	}
	if r.Snapshot != nil {
		if err := r.Snapshot.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "snapshot"}}); err != nil {
			return err
		}
	}
	if r.Differential != nil {
		if err := r.Differential.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "differential"}}); err != nil {
			return err
		}
	}

	return e.EncodeToken(start.End())
}

// UnmarshalXML deserializes StructureDefinition from FHIR-conformant XML.
func (r *StructureDefinition) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	for {
		tok, err := d.Token()
		if err != nil {
			return err
		}
		switch t := tok.(type) {
		case xml.StartElement:
			switch t.Name.Local {
			case "id":
				v, _, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Id = v
			case "meta":
				var v Meta
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Meta = &v
			case "implicitRules":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.ImplicitRules = v
				r.ImplicitRulesExt = ext
			case "language":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Language = v
				r.LanguageExt = ext
			case "text":
				var v Narrative
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Text = &v
			case "contained":
				res, err := xmlDecodeContainedResource(d, t)
				if err != nil {
					return err
				}
				if res != nil {
					r.Contained = append(r.Contained, res)
				}
			case "extension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Extension = append(r.Extension, v)
			case "modifierExtension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.ModifierExtension = append(r.ModifierExtension, v)
			case "url":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Url = v
				r.UrlExt = ext
			case "identifier":
				var v Identifier
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Identifier = append(r.Identifier, v)
			case "version":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Version = v
				r.VersionExt = ext
			case "name":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Name = v
				r.NameExt = ext
			case "title":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Title = v
				r.TitleExt = ext
			case "status":
				v, ext, err := xmlDecodePrimitiveCode[PublicationStatus](d, t)
				if err != nil {
					return err
				}
				r.Status = v
				r.StatusExt = ext
			case "experimental":
				v, ext, err := xmlDecodePrimitiveBool(d, t)
				if err != nil {
					return err
				}
				r.Experimental = v
				r.ExperimentalExt = ext
			case "date":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Date = v
				r.DateExt = ext
			case "publisher":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Publisher = v
				r.PublisherExt = ext
			case "contact":
				var v ContactDetail
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Contact = append(r.Contact, v)
			case "description":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Description = v
				r.DescriptionExt = ext
			case "useContext":
				var v UsageContext
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.UseContext = append(r.UseContext, v)
			case "jurisdiction":
				var v CodeableConcept
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Jurisdiction = append(r.Jurisdiction, v)
			case "purpose":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Purpose = v
				r.PurposeExt = ext
			case "copyright":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Copyright = v
				r.CopyrightExt = ext
			case "keyword":
				var v Coding
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Keyword = append(r.Keyword, v)
			case "fhirVersion":
				v, ext, err := xmlDecodePrimitiveCode[FHIRVersion](d, t)
				if err != nil {
					return err
				}
				r.FhirVersion = v
				r.FhirVersionExt = ext
			case "mapping":
				var v StructureDefinitionMapping
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Mapping = append(r.Mapping, v)
			case "kind":
				v, ext, err := xmlDecodePrimitiveCode[StructureDefinitionKind](d, t)
				if err != nil {
					return err
				}
				r.Kind = v
				r.KindExt = ext
			case "abstract":
				v, ext, err := xmlDecodePrimitiveBool(d, t)
				if err != nil {
					return err
				}
				r.Abstract = v
				r.AbstractExt = ext
			case "context":
				var v StructureDefinitionContext
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Context = append(r.Context, v)
			case "contextInvariant":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				// nil is meaningful here: it is a positional slot with no value.
				r.ContextInvariant = append(r.ContextInvariant, v)
				r.ContextInvariantExt = append(r.ContextInvariantExt, ext)
			case "type":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Type = v
				r.TypeExt = ext
			case "baseDefinition":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.BaseDefinition = v
				r.BaseDefinitionExt = ext
			case "derivation":
				v, ext, err := xmlDecodePrimitiveCode[TypeDerivationRule](d, t)
				if err != nil {
					return err
				}
				r.Derivation = v
				r.DerivationExt = ext
			case "snapshot":
				var v StructureDefinitionSnapshot
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Snapshot = &v
			case "differential":
				var v StructureDefinitionDifferential
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Differential = &v
			default:
				if err := d.Skip(); err != nil {
					return err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// StructureDefinitionContext represents the StructureDefinition.context backbone element.
// If an extension, where it can be used in instances
type StructureDefinitionContext struct {
	// Unique id for inter-element referencing
	Id *string `json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// fhirpath | element | extension
	Type *ExtensionContextType `json:"type,omitempty"`
	// Extension for Type
	TypeExt *Element `json:"_type,omitempty"`
	// Where the extension can be used in instances
	Expression *string `json:"expression,omitempty"`
	// Extension for Expression
	ExpressionExt *Element `json:"_expression,omitempty"`
}

// MarshalXML serializes StructureDefinitionContext to FHIR-conformant XML.
func (b StructureDefinitionContext) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if start.Name.Local == "" {
		start.Name.Local = "StructureDefinition.context"
	}
	if b.Id != nil {
		start.Attr = append(start.Attr, xml.Attr{Name: xml.Name{Local: "id"}, Value: *b.Id})
	}
	if err := e.EncodeToken(start); err != nil {
		return err
	}

	for _, item := range b.Extension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "extension"}}); err != nil {
			return err
		}
	}
	for _, item := range b.ModifierExtension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "modifierExtension"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveCode(e, "type", b.Type, b.TypeExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveString(e, "expression", b.Expression, b.ExpressionExt); err != nil {
		return err
	}

	return e.EncodeToken(start.End())
}

// UnmarshalXML deserializes StructureDefinitionContext from FHIR-conformant XML.
func (r *StructureDefinitionContext) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	for _, attr := range start.Attr {
		if attr.Name.Local == "id" {
			v := attr.Value
			r.Id = &v
		}
	}

	for {
		tok, err := d.Token()
		if err != nil {
			return err
		}
		switch t := tok.(type) {
		case xml.StartElement:
			switch t.Name.Local {
			case "extension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Extension = append(r.Extension, v)
			case "modifierExtension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.ModifierExtension = append(r.ModifierExtension, v)
			case "type":
				v, ext, err := xmlDecodePrimitiveCode[ExtensionContextType](d, t)
				if err != nil {
					return err
				}
				r.Type = v
				r.TypeExt = ext
			case "expression":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Expression = v
				r.ExpressionExt = ext
			default:
				if err := d.Skip(); err != nil {
					return err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// StructureDefinitionDifferential represents the StructureDefinition.differential backbone element.
// Differential view of the structure
type StructureDefinitionDifferential struct {
	// Unique id for inter-element referencing
	Id *string `json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Definition of elements in the resource (if no StructureDefinition)
	Element []ElementDefinition `json:"element,omitempty"`
}

// MarshalXML serializes StructureDefinitionDifferential to FHIR-conformant XML.
func (b StructureDefinitionDifferential) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if start.Name.Local == "" {
		start.Name.Local = "StructureDefinition.differential"
	}
	if b.Id != nil {
		start.Attr = append(start.Attr, xml.Attr{Name: xml.Name{Local: "id"}, Value: *b.Id})
	}
	if err := e.EncodeToken(start); err != nil {
		return err
	}

	for _, item := range b.Extension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "extension"}}); err != nil {
			return err
		}
	}
	for _, item := range b.ModifierExtension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "modifierExtension"}}); err != nil {
			return err
		}
	}
	for _, item := range b.Element {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "element"}}); err != nil {
			return err
		}
	}

	return e.EncodeToken(start.End())
}

// UnmarshalXML deserializes StructureDefinitionDifferential from FHIR-conformant XML.
func (r *StructureDefinitionDifferential) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	for _, attr := range start.Attr {
		if attr.Name.Local == "id" {
			v := attr.Value
			r.Id = &v
		}
	}

	for {
		tok, err := d.Token()
		if err != nil {
			return err
		}
		switch t := tok.(type) {
		case xml.StartElement:
			switch t.Name.Local {
			case "extension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Extension = append(r.Extension, v)
			case "modifierExtension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.ModifierExtension = append(r.ModifierExtension, v)
			case "element":
				var v ElementDefinition
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Element = append(r.Element, v)
			default:
				if err := d.Skip(); err != nil {
					return err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// StructureDefinitionMapping represents the StructureDefinition.mapping backbone element.
// External specification that the content is mapped to
type StructureDefinitionMapping struct {
	// Unique id for inter-element referencing
	Id *string `json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Internal id when this mapping is used
	Identity *string `json:"identity,omitempty"`
	// Extension for Identity
	IdentityExt *Element `json:"_identity,omitempty"`
	// Identifies what this mapping refers to
	Uri *string `json:"uri,omitempty"`
	// Extension for Uri
	UriExt *Element `json:"_uri,omitempty"`
	// Names what this mapping refers to
	Name *string `json:"name,omitempty"`
	// Extension for Name
	NameExt *Element `json:"_name,omitempty"`
	// Versions, Issues, Scope limitations etc.
	Comment *string `json:"comment,omitempty"`
	// Extension for Comment
	CommentExt *Element `json:"_comment,omitempty"`
}

// MarshalXML serializes StructureDefinitionMapping to FHIR-conformant XML.
func (b StructureDefinitionMapping) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if start.Name.Local == "" {
		start.Name.Local = "StructureDefinition.mapping"
	}
	if b.Id != nil {
		start.Attr = append(start.Attr, xml.Attr{Name: xml.Name{Local: "id"}, Value: *b.Id})
	}
	if err := e.EncodeToken(start); err != nil {
		return err
	}

	for _, item := range b.Extension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "extension"}}); err != nil {
			return err
		}
	}
	for _, item := range b.ModifierExtension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "modifierExtension"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveString(e, "identity", b.Identity, b.IdentityExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveString(e, "uri", b.Uri, b.UriExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveString(e, "name", b.Name, b.NameExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveString(e, "comment", b.Comment, b.CommentExt); err != nil {
		return err
	}

	return e.EncodeToken(start.End())
}

// UnmarshalXML deserializes StructureDefinitionMapping from FHIR-conformant XML.
func (r *StructureDefinitionMapping) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	for _, attr := range start.Attr {
		if attr.Name.Local == "id" {
			v := attr.Value
			r.Id = &v
		}
	}

	for {
		tok, err := d.Token()
		if err != nil {
			return err
		}
		switch t := tok.(type) {
		case xml.StartElement:
			switch t.Name.Local {
			case "extension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Extension = append(r.Extension, v)
			case "modifierExtension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.ModifierExtension = append(r.ModifierExtension, v)
			case "identity":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Identity = v
				r.IdentityExt = ext
			case "uri":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Uri = v
				r.UriExt = ext
			case "name":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Name = v
				r.NameExt = ext
			case "comment":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Comment = v
				r.CommentExt = ext
			default:
				if err := d.Skip(); err != nil {
					return err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// StructureDefinitionSnapshot represents the StructureDefinition.snapshot backbone element.
// Snapshot view of the structure
type StructureDefinitionSnapshot struct {
	// Unique id for inter-element referencing
	Id *string `json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Definition of elements in the resource (if no StructureDefinition)
	Element []ElementDefinition `json:"element,omitempty"`
}

// MarshalXML serializes StructureDefinitionSnapshot to FHIR-conformant XML.
func (b StructureDefinitionSnapshot) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if start.Name.Local == "" {
		start.Name.Local = "StructureDefinition.snapshot"
	}
	if b.Id != nil {
		start.Attr = append(start.Attr, xml.Attr{Name: xml.Name{Local: "id"}, Value: *b.Id})
	}
	if err := e.EncodeToken(start); err != nil {
		return err
	}

	for _, item := range b.Extension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "extension"}}); err != nil {
			return err
		}
	}
	for _, item := range b.ModifierExtension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "modifierExtension"}}); err != nil {
			return err
		}
	}
	for _, item := range b.Element {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "element"}}); err != nil {
			return err
		}
	}

	return e.EncodeToken(start.End())
}

// UnmarshalXML deserializes StructureDefinitionSnapshot from FHIR-conformant XML.
func (r *StructureDefinitionSnapshot) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	for _, attr := range start.Attr {
		if attr.Name.Local == "id" {
			v := attr.Value
			r.Id = &v
		}
	}

	for {
		tok, err := d.Token()
		if err != nil {
			return err
		}
		switch t := tok.(type) {
		case xml.StartElement:
			switch t.Name.Local {
			case "extension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Extension = append(r.Extension, v)
			case "modifierExtension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.ModifierExtension = append(r.ModifierExtension, v)
			case "element":
				var v ElementDefinition
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Element = append(r.Element, v)
			default:
				if err := d.Skip(); err != nil {
					return err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// =============================================================================
// StructureDefinition - Fluent Builder
// =============================================================================

// StructureDefinitionBuilder provides a fluent API for constructing StructureDefinition resources.
type StructureDefinitionBuilder struct {
	structureDefinition *StructureDefinition
}

// NewStructureDefinitionBuilder creates a new StructureDefinitionBuilder.
func NewStructureDefinitionBuilder() *StructureDefinitionBuilder {
	return &StructureDefinitionBuilder{
		// Nothing to set: the type marker carries the resource type, so the zero
		// value is already correct both in memory and on the wire.
		structureDefinition: &StructureDefinition{},
	}
}

// Build returns the constructed StructureDefinition resource.
func (b *StructureDefinitionBuilder) Build() *StructureDefinition {
	return b.structureDefinition
}

// SetId sets the Id field.
func (b *StructureDefinitionBuilder) SetId(v string) *StructureDefinitionBuilder {
	b.structureDefinition.Id = &v
	return b
}

// SetMeta sets the Meta field.
func (b *StructureDefinitionBuilder) SetMeta(v Meta) *StructureDefinitionBuilder {
	b.structureDefinition.Meta = &v
	return b
}

// SetImplicitRules sets the ImplicitRules field.
func (b *StructureDefinitionBuilder) SetImplicitRules(v string) *StructureDefinitionBuilder {
	b.structureDefinition.ImplicitRules = &v
	return b
}

// SetLanguage sets the Language field.
func (b *StructureDefinitionBuilder) SetLanguage(v string) *StructureDefinitionBuilder {
	b.structureDefinition.Language = &v
	return b
}

// SetText sets the Text field.
func (b *StructureDefinitionBuilder) SetText(v Narrative) *StructureDefinitionBuilder {
	b.structureDefinition.Text = &v
	return b
}

// AddContained adds a Contained element.
func (b *StructureDefinitionBuilder) AddContained(v Resource) *StructureDefinitionBuilder {
	b.structureDefinition.Contained = append(b.structureDefinition.Contained, v)
	return b
}

// AddExtension adds a Extension element.
func (b *StructureDefinitionBuilder) AddExtension(v Extension) *StructureDefinitionBuilder {
	b.structureDefinition.Extension = append(b.structureDefinition.Extension, v)
	return b
}

// AddModifierExtension adds a ModifierExtension element.
func (b *StructureDefinitionBuilder) AddModifierExtension(v Extension) *StructureDefinitionBuilder {
	b.structureDefinition.ModifierExtension = append(b.structureDefinition.ModifierExtension, v)
	return b
}

// SetUrl sets the Url field.
func (b *StructureDefinitionBuilder) SetUrl(v string) *StructureDefinitionBuilder {
	b.structureDefinition.Url = &v
	return b
}

// AddIdentifier adds a Identifier element.
func (b *StructureDefinitionBuilder) AddIdentifier(v Identifier) *StructureDefinitionBuilder {
	b.structureDefinition.Identifier = append(b.structureDefinition.Identifier, v)
	return b
}

// SetVersion sets the Version field.
func (b *StructureDefinitionBuilder) SetVersion(v string) *StructureDefinitionBuilder {
	b.structureDefinition.Version = &v
	return b
}

// SetName sets the Name field.
func (b *StructureDefinitionBuilder) SetName(v string) *StructureDefinitionBuilder {
	b.structureDefinition.Name = &v
	return b
}

// SetTitle sets the Title field.
func (b *StructureDefinitionBuilder) SetTitle(v string) *StructureDefinitionBuilder {
	b.structureDefinition.Title = &v
	return b
}

// SetStatus sets the Status field.
func (b *StructureDefinitionBuilder) SetStatus(v PublicationStatus) *StructureDefinitionBuilder {
	b.structureDefinition.Status = &v
	return b
}

// SetExperimental sets the Experimental field.
func (b *StructureDefinitionBuilder) SetExperimental(v bool) *StructureDefinitionBuilder {
	b.structureDefinition.Experimental = &v
	return b
}

// SetDate sets the Date field.
func (b *StructureDefinitionBuilder) SetDate(v string) *StructureDefinitionBuilder {
	b.structureDefinition.Date = &v
	return b
}

// SetPublisher sets the Publisher field.
func (b *StructureDefinitionBuilder) SetPublisher(v string) *StructureDefinitionBuilder {
	b.structureDefinition.Publisher = &v
	return b
}

// AddContact adds a Contact element.
func (b *StructureDefinitionBuilder) AddContact(v ContactDetail) *StructureDefinitionBuilder {
	b.structureDefinition.Contact = append(b.structureDefinition.Contact, v)
	return b
}

// SetDescription sets the Description field.
func (b *StructureDefinitionBuilder) SetDescription(v string) *StructureDefinitionBuilder {
	b.structureDefinition.Description = &v
	return b
}

// AddUseContext adds a UseContext element.
func (b *StructureDefinitionBuilder) AddUseContext(v UsageContext) *StructureDefinitionBuilder {
	b.structureDefinition.UseContext = append(b.structureDefinition.UseContext, v)
	return b
}

// AddJurisdiction adds a Jurisdiction element.
func (b *StructureDefinitionBuilder) AddJurisdiction(v CodeableConcept) *StructureDefinitionBuilder {
	b.structureDefinition.Jurisdiction = append(b.structureDefinition.Jurisdiction, v)
	return b
}

// SetPurpose sets the Purpose field.
func (b *StructureDefinitionBuilder) SetPurpose(v string) *StructureDefinitionBuilder {
	b.structureDefinition.Purpose = &v
	return b
}

// SetCopyright sets the Copyright field.
func (b *StructureDefinitionBuilder) SetCopyright(v string) *StructureDefinitionBuilder {
	b.structureDefinition.Copyright = &v
	return b
}

// AddKeyword adds a Keyword element.
func (b *StructureDefinitionBuilder) AddKeyword(v Coding) *StructureDefinitionBuilder {
	b.structureDefinition.Keyword = append(b.structureDefinition.Keyword, v)
	return b
}

// SetFhirVersion sets the FhirVersion field.
func (b *StructureDefinitionBuilder) SetFhirVersion(v FHIRVersion) *StructureDefinitionBuilder {
	b.structureDefinition.FhirVersion = &v
	return b
}

// AddMapping adds a Mapping element.
func (b *StructureDefinitionBuilder) AddMapping(v StructureDefinitionMapping) *StructureDefinitionBuilder {
	b.structureDefinition.Mapping = append(b.structureDefinition.Mapping, v)
	return b
}

// SetKind sets the Kind field.
func (b *StructureDefinitionBuilder) SetKind(v StructureDefinitionKind) *StructureDefinitionBuilder {
	b.structureDefinition.Kind = &v
	return b
}

// SetAbstract sets the Abstract field.
func (b *StructureDefinitionBuilder) SetAbstract(v bool) *StructureDefinitionBuilder {
	b.structureDefinition.Abstract = &v
	return b
}

// AddContext adds a Context element.
func (b *StructureDefinitionBuilder) AddContext(v StructureDefinitionContext) *StructureDefinitionBuilder {
	b.structureDefinition.Context = append(b.structureDefinition.Context, v)
	return b
}

// AddContextInvariant adds a ContextInvariant element.
//
// Takes a plain value: the field is a slice of pointers so that an absent slot
// can be expressed, but a builder call is always adding a value. For a slot that
// is deliberately absent, build the slice directly and leave that entry nil.
func (b *StructureDefinitionBuilder) AddContextInvariant(v string) *StructureDefinitionBuilder {
	b.structureDefinition.ContextInvariant = append(b.structureDefinition.ContextInvariant, &v)
	return b
}

// SetType sets the Type field.
func (b *StructureDefinitionBuilder) SetType(v string) *StructureDefinitionBuilder {
	b.structureDefinition.Type = &v
	return b
}

// SetBaseDefinition sets the BaseDefinition field.
func (b *StructureDefinitionBuilder) SetBaseDefinition(v string) *StructureDefinitionBuilder {
	b.structureDefinition.BaseDefinition = &v
	return b
}

// SetDerivation sets the Derivation field.
func (b *StructureDefinitionBuilder) SetDerivation(v TypeDerivationRule) *StructureDefinitionBuilder {
	b.structureDefinition.Derivation = &v
	return b
}

// SetSnapshot sets the Snapshot field.
func (b *StructureDefinitionBuilder) SetSnapshot(v StructureDefinitionSnapshot) *StructureDefinitionBuilder {
	b.structureDefinition.Snapshot = &v
	return b
}

// SetDifferential sets the Differential field.
func (b *StructureDefinitionBuilder) SetDifferential(v StructureDefinitionDifferential) *StructureDefinitionBuilder {
	b.structureDefinition.Differential = &v
	return b
}
