// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (consolidated resource)
// Package: r4b

package r4b

import (
	"bytes"
	"encoding/json"
	"encoding/xml"
	"fmt"
)

// =============================================================================
// Appointment Resource
// =============================================================================

// Appointment represents FHIR Appointment.
type Appointment struct {
	// FHIR resource type
	ResourceType string `json:"resourceType"`
	// Logical id of this artifact
	Id *string `json:"id,omitempty"`
	// Metadata about the resource
	Meta *Meta `json:"meta,omitempty"`
	// A set of rules under which this content was created
	ImplicitRules *string `json:"implicitRules,omitempty"`
	// Extension for ImplicitRules
	ImplicitRulesExt *Element `json:"_implicitRules,omitempty"`
	// Language of the resource content
	Language *string `json:"language,omitempty"`
	// Extension for Language
	LanguageExt *Element `json:"_language,omitempty"`
	// Text summary of the resource, for human interpretation
	Text *Narrative `json:"text,omitempty"`
	// Contained, inline Resources
	Contained []Resource `json:"contained,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// External Ids for this item
	Identifier []Identifier `json:"identifier,omitempty"`
	// proposed | pending | booked | arrived | fulfilled | cancelled | noshow | entered-in-error | checked-in | waitlist
	Status *AppointmentStatus `json:"status,omitempty"`
	// Extension for Status
	StatusExt *Element `json:"_status,omitempty"`
	// The coded reason for the appointment being cancelled
	CancelationReason *CodeableConcept `json:"cancelationReason,omitempty"`
	// A broad categorization of the service that is to be performed during this appointment
	ServiceCategory []CodeableConcept `json:"serviceCategory,omitempty"`
	// The specific service that is to be performed during this appointment
	ServiceType []CodeableConcept `json:"serviceType,omitempty"`
	// The specialty of a practitioner that would be required to perform the service requested in this appointment
	Specialty []CodeableConcept `json:"specialty,omitempty"`
	// The style of appointment or patient that has been booked in the slot (not service type)
	AppointmentType *CodeableConcept `json:"appointmentType,omitempty"`
	// Coded reason this appointment is scheduled
	ReasonCode []CodeableConcept `json:"reasonCode,omitempty"`
	// Reason the appointment is to take place (resource)
	ReasonReference []Reference `json:"reasonReference,omitempty"`
	// Used to make informed decisions if needing to re-prioritize
	Priority *uint32 `json:"priority,omitempty"`
	// Extension for Priority
	PriorityExt *Element `json:"_priority,omitempty"`
	// Shown on a subject line in a meeting request, or appointment list
	Description *string `json:"description,omitempty"`
	// Extension for Description
	DescriptionExt *Element `json:"_description,omitempty"`
	// Additional information to support the appointment
	SupportingInformation []Reference `json:"supportingInformation,omitempty"`
	// When appointment is to take place
	Start *string `json:"start,omitempty"`
	// Extension for Start
	StartExt *Element `json:"_start,omitempty"`
	// When appointment is to conclude
	End *string `json:"end,omitempty"`
	// Extension for End
	EndExt *Element `json:"_end,omitempty"`
	// Can be less than start/end (e.g. estimate)
	MinutesDuration *uint32 `json:"minutesDuration,omitempty"`
	// Extension for MinutesDuration
	MinutesDurationExt *Element `json:"_minutesDuration,omitempty"`
	// The slots that this appointment is filling
	Slot []Reference `json:"slot,omitempty"`
	// The date that this appointment was initially created
	Created *string `json:"created,omitempty"`
	// Extension for Created
	CreatedExt *Element `json:"_created,omitempty"`
	// Additional comments
	Comment *string `json:"comment,omitempty"`
	// Extension for Comment
	CommentExt *Element `json:"_comment,omitempty"`
	// Detailed information and instructions for the patient
	PatientInstruction *string `json:"patientInstruction,omitempty"`
	// Extension for PatientInstruction
	PatientInstructionExt *Element `json:"_patientInstruction,omitempty"`
	// The service request this appointment is allocated to assess
	BasedOn []Reference `json:"basedOn,omitempty"`
	// Participants involved in appointment
	Participant []AppointmentParticipant `json:"participant,omitempty"`
	// Potential date/time interval(s) requested to allocate the appointment within
	RequestedPeriod []Period `json:"requestedPeriod,omitempty"`
}

// GetResourceType returns the FHIR resource type.
func (r *Appointment) GetResourceType() string {
	return "Appointment"
}

// GetId returns the resource's logical ID.
func (r *Appointment) GetId() *string {
	return r.Id
}

// SetId sets the resource's logical ID.
func (r *Appointment) SetId(id string) {
	r.Id = &id
}

// GetMeta returns the resource's Meta element.
func (r *Appointment) GetMeta() *Meta {
	return r.Meta
}

// SetMeta sets the resource's Meta element.
func (r *Appointment) SetMeta(m *Meta) {
	r.Meta = m
}

// GetText returns the resource's narrative text.
func (r *Appointment) GetText() *Narrative {
	return r.Text
}

// SetText sets the resource's narrative text.
func (r *Appointment) SetText(t *Narrative) {
	r.Text = t
}

// GetContained returns the resource's contained resources.
func (r *Appointment) GetContained() []Resource {
	return r.Contained
}

// GetExtension returns the resource's extensions.
func (r *Appointment) GetExtension() []Extension {
	return r.Extension
}

// GetModifierExtension returns the resource's modifier extensions.
func (r *Appointment) GetModifierExtension() []Extension {
	return r.ModifierExtension
}

// MarshalJSON ensures resourceType is always included in JSON output.
// HTML escaping is disabled to preserve FHIR narrative XHTML content.
//
// Note: Use the package-level Marshal function instead of json.Marshal
// to ensure HTML in narrative text.div fields is not escaped.
func (r Appointment) MarshalJSON() ([]byte, error) {
	r.ResourceType = "Appointment"
	type Alias Appointment
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	if err := enc.Encode((Alias)(r)); err != nil {
		return nil, err
	}
	b := buf.Bytes()
	if len(b) > 0 && b[len(b)-1] == '\n' {
		b = b[:len(b)-1]
	}
	return b, nil
}

// UnmarshalJSON handles deserialization of polymorphic contained resources.
func (r *Appointment) UnmarshalJSON(data []byte) error {
	// Use an alias to avoid infinite recursion
	type Alias Appointment
	aux := &struct {
		Contained []json.RawMessage `json:"contained,omitempty"`
		*Alias
	}{
		Alias: (*Alias)(r),
	}

	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}

	// Unmarshal each contained resource using the dispatcher
	if len(aux.Contained) > 0 {
		r.Contained = make([]Resource, len(aux.Contained))
		for i, raw := range aux.Contained {
			resource, err := UnmarshalResource(raw)
			if err != nil {
				return fmt.Errorf("failed to unmarshal contained[%d]: %w", i, err)
			}
			r.Contained[i] = resource
		}
	}

	return nil
}

// MarshalXML serializes Appointment to FHIR-conformant XML.
func (r Appointment) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if start.Name.Local == "" {
		start.Name.Local = "Appointment"
		start.Name.Space = fhirNamespace
	}
	if err := e.EncodeToken(start); err != nil {
		return err
	}

	if err := xmlEncodePrimitiveString(e, "id", r.Id, nil); err != nil {
		return err
	}
	if r.Meta != nil {
		if err := r.Meta.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "meta"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveString(e, "implicitRules", r.ImplicitRules, r.ImplicitRulesExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveString(e, "language", r.Language, r.LanguageExt); err != nil {
		return err
	}
	if r.Text != nil {
		if err := r.Text.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "text"}}); err != nil {
			return err
		}
	}
	for _, c := range r.Contained {
		if c != nil {
			if err := xmlEncodeContainedResource(e, c); err != nil {
				return err
			}
		}
	}
	for _, item := range r.Extension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "extension"}}); err != nil {
			return err
		}
	}
	for _, item := range r.ModifierExtension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "modifierExtension"}}); err != nil {
			return err
		}
	}
	for _, item := range r.Identifier {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "identifier"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveCode(e, "status", r.Status, r.StatusExt); err != nil {
		return err
	}
	if r.CancelationReason != nil {
		if err := r.CancelationReason.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "cancelationReason"}}); err != nil {
			return err
		}
	}
	for _, item := range r.ServiceCategory {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "serviceCategory"}}); err != nil {
			return err
		}
	}
	for _, item := range r.ServiceType {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "serviceType"}}); err != nil {
			return err
		}
	}
	for _, item := range r.Specialty {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "specialty"}}); err != nil {
			return err
		}
	}
	if r.AppointmentType != nil {
		if err := r.AppointmentType.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "appointmentType"}}); err != nil {
			return err
		}
	}
	for _, item := range r.ReasonCode {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "reasonCode"}}); err != nil {
			return err
		}
	}
	for _, item := range r.ReasonReference {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "reasonReference"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveUint32(e, "priority", r.Priority, r.PriorityExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveString(e, "description", r.Description, r.DescriptionExt); err != nil {
		return err
	}
	for _, item := range r.SupportingInformation {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "supportingInformation"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveString(e, "start", r.Start, r.StartExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveString(e, "end", r.End, r.EndExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveUint32(e, "minutesDuration", r.MinutesDuration, r.MinutesDurationExt); err != nil {
		return err
	}
	for _, item := range r.Slot {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "slot"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveString(e, "created", r.Created, r.CreatedExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveString(e, "comment", r.Comment, r.CommentExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveString(e, "patientInstruction", r.PatientInstruction, r.PatientInstructionExt); err != nil {
		return err
	}
	for _, item := range r.BasedOn {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "basedOn"}}); err != nil {
			return err
		}
	}
	for _, item := range r.Participant {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "participant"}}); err != nil {
			return err
		}
	}
	for _, item := range r.RequestedPeriod {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "requestedPeriod"}}); err != nil {
			return err
		}
	}

	return e.EncodeToken(start.End())
}

// UnmarshalXML deserializes Appointment from FHIR-conformant XML.
func (r *Appointment) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	for {
		tok, err := d.Token()
		if err != nil {
			return err
		}
		switch t := tok.(type) {
		case xml.StartElement:
			switch t.Name.Local {
			case "id":
				v, _, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Id = v
			case "meta":
				var v Meta
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Meta = &v
			case "implicitRules":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.ImplicitRules = v
				r.ImplicitRulesExt = ext
			case "language":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Language = v
				r.LanguageExt = ext
			case "text":
				var v Narrative
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Text = &v
			case "contained":
				res, err := xmlDecodeContainedResource(d, t)
				if err != nil {
					return err
				}
				if res != nil {
					r.Contained = append(r.Contained, res)
				}
			case "extension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Extension = append(r.Extension, v)
			case "modifierExtension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.ModifierExtension = append(r.ModifierExtension, v)
			case "identifier":
				var v Identifier
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Identifier = append(r.Identifier, v)
			case "status":
				v, ext, err := xmlDecodePrimitiveCode[AppointmentStatus](d, t)
				if err != nil {
					return err
				}
				r.Status = v
				r.StatusExt = ext
			case "cancelationReason":
				var v CodeableConcept
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.CancelationReason = &v
			case "serviceCategory":
				var v CodeableConcept
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.ServiceCategory = append(r.ServiceCategory, v)
			case "serviceType":
				var v CodeableConcept
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.ServiceType = append(r.ServiceType, v)
			case "specialty":
				var v CodeableConcept
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Specialty = append(r.Specialty, v)
			case "appointmentType":
				var v CodeableConcept
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.AppointmentType = &v
			case "reasonCode":
				var v CodeableConcept
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.ReasonCode = append(r.ReasonCode, v)
			case "reasonReference":
				var v Reference
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.ReasonReference = append(r.ReasonReference, v)
			case "priority":
				v, ext, err := xmlDecodePrimitiveUint32(d, t)
				if err != nil {
					return err
				}
				r.Priority = v
				r.PriorityExt = ext
			case "description":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Description = v
				r.DescriptionExt = ext
			case "supportingInformation":
				var v Reference
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.SupportingInformation = append(r.SupportingInformation, v)
			case "start":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Start = v
				r.StartExt = ext
			case "end":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.End = v
				r.EndExt = ext
			case "minutesDuration":
				v, ext, err := xmlDecodePrimitiveUint32(d, t)
				if err != nil {
					return err
				}
				r.MinutesDuration = v
				r.MinutesDurationExt = ext
			case "slot":
				var v Reference
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Slot = append(r.Slot, v)
			case "created":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Created = v
				r.CreatedExt = ext
			case "comment":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Comment = v
				r.CommentExt = ext
			case "patientInstruction":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.PatientInstruction = v
				r.PatientInstructionExt = ext
			case "basedOn":
				var v Reference
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.BasedOn = append(r.BasedOn, v)
			case "participant":
				var v AppointmentParticipant
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Participant = append(r.Participant, v)
			case "requestedPeriod":
				var v Period
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.RequestedPeriod = append(r.RequestedPeriod, v)
			default:
				if err := d.Skip(); err != nil {
					return err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// AppointmentParticipant represents the Appointment.participant backbone element.
// Participants involved in appointment
type AppointmentParticipant struct {
	// Unique id for inter-element referencing
	Id *string `json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Role of participant in the appointment
	Type []CodeableConcept `json:"type,omitempty"`
	// Person, Location/HealthcareService or Device
	Actor *Reference `json:"actor,omitempty"`
	// required | optional | information-only
	Required *ParticipantRequired `json:"required,omitempty"`
	// accepted | declined | tentative | needs-action
	Status *ParticipationStatus `json:"status,omitempty"`
	// Participation period of the actor
	Period *Period `json:"period,omitempty"`
}

// MarshalXML serializes AppointmentParticipant to FHIR-conformant XML.
func (b AppointmentParticipant) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if start.Name.Local == "" {
		start.Name.Local = "Appointment.participant"
	}
	if b.Id != nil {
		start.Attr = append(start.Attr, xml.Attr{Name: xml.Name{Local: "id"}, Value: *b.Id})
	}
	if err := e.EncodeToken(start); err != nil {
		return err
	}

	for _, item := range b.Extension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "extension"}}); err != nil {
			return err
		}
	}
	for _, item := range b.ModifierExtension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "modifierExtension"}}); err != nil {
			return err
		}
	}
	for _, item := range b.Type {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "type"}}); err != nil {
			return err
		}
	}
	if b.Actor != nil {
		if err := b.Actor.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "actor"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveCode(e, "required", b.Required, nil); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveCode(e, "status", b.Status, nil); err != nil {
		return err
	}
	if b.Period != nil {
		if err := b.Period.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "period"}}); err != nil {
			return err
		}
	}

	return e.EncodeToken(start.End())
}

// UnmarshalXML deserializes AppointmentParticipant from FHIR-conformant XML.
func (r *AppointmentParticipant) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	for _, attr := range start.Attr {
		if attr.Name.Local == "id" {
			v := attr.Value
			r.Id = &v
		}
	}

	for {
		tok, err := d.Token()
		if err != nil {
			return err
		}
		switch t := tok.(type) {
		case xml.StartElement:
			switch t.Name.Local {
			case "extension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Extension = append(r.Extension, v)
			case "modifierExtension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.ModifierExtension = append(r.ModifierExtension, v)
			case "type":
				var v CodeableConcept
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Type = append(r.Type, v)
			case "actor":
				var v Reference
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Actor = &v
			case "required":
				v, _, err := xmlDecodePrimitiveCode[ParticipantRequired](d, t)
				if err != nil {
					return err
				}
				r.Required = v
			case "status":
				v, _, err := xmlDecodePrimitiveCode[ParticipationStatus](d, t)
				if err != nil {
					return err
				}
				r.Status = v
			case "period":
				var v Period
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Period = &v
			default:
				if err := d.Skip(); err != nil {
					return err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// =============================================================================
// Appointment - Fluent Builder
// =============================================================================

// AppointmentBuilder provides a fluent API for constructing Appointment resources.
type AppointmentBuilder struct {
	appointment *Appointment
}

// NewAppointmentBuilder creates a new AppointmentBuilder.
func NewAppointmentBuilder() *AppointmentBuilder {
	return &AppointmentBuilder{
		appointment: &Appointment{},
	}
}

// Build returns the constructed Appointment resource.
func (b *AppointmentBuilder) Build() *Appointment {
	return b.appointment
}

// SetId sets the Id field.
func (b *AppointmentBuilder) SetId(v string) *AppointmentBuilder {
	b.appointment.Id = &v
	return b
}

// SetMeta sets the Meta field.
func (b *AppointmentBuilder) SetMeta(v Meta) *AppointmentBuilder {
	b.appointment.Meta = &v
	return b
}

// SetImplicitRules sets the ImplicitRules field.
func (b *AppointmentBuilder) SetImplicitRules(v string) *AppointmentBuilder {
	b.appointment.ImplicitRules = &v
	return b
}

// SetLanguage sets the Language field.
func (b *AppointmentBuilder) SetLanguage(v string) *AppointmentBuilder {
	b.appointment.Language = &v
	return b
}

// SetText sets the Text field.
func (b *AppointmentBuilder) SetText(v Narrative) *AppointmentBuilder {
	b.appointment.Text = &v
	return b
}

// AddContained adds a Contained element.
func (b *AppointmentBuilder) AddContained(v Resource) *AppointmentBuilder {
	b.appointment.Contained = append(b.appointment.Contained, v)
	return b
}

// AddExtension adds a Extension element.
func (b *AppointmentBuilder) AddExtension(v Extension) *AppointmentBuilder {
	b.appointment.Extension = append(b.appointment.Extension, v)
	return b
}

// AddModifierExtension adds a ModifierExtension element.
func (b *AppointmentBuilder) AddModifierExtension(v Extension) *AppointmentBuilder {
	b.appointment.ModifierExtension = append(b.appointment.ModifierExtension, v)
	return b
}

// AddIdentifier adds a Identifier element.
func (b *AppointmentBuilder) AddIdentifier(v Identifier) *AppointmentBuilder {
	b.appointment.Identifier = append(b.appointment.Identifier, v)
	return b
}

// SetStatus sets the Status field.
func (b *AppointmentBuilder) SetStatus(v AppointmentStatus) *AppointmentBuilder {
	b.appointment.Status = &v
	return b
}

// SetCancelationReason sets the CancelationReason field.
func (b *AppointmentBuilder) SetCancelationReason(v CodeableConcept) *AppointmentBuilder {
	b.appointment.CancelationReason = &v
	return b
}

// AddServiceCategory adds a ServiceCategory element.
func (b *AppointmentBuilder) AddServiceCategory(v CodeableConcept) *AppointmentBuilder {
	b.appointment.ServiceCategory = append(b.appointment.ServiceCategory, v)
	return b
}

// AddServiceType adds a ServiceType element.
func (b *AppointmentBuilder) AddServiceType(v CodeableConcept) *AppointmentBuilder {
	b.appointment.ServiceType = append(b.appointment.ServiceType, v)
	return b
}

// AddSpecialty adds a Specialty element.
func (b *AppointmentBuilder) AddSpecialty(v CodeableConcept) *AppointmentBuilder {
	b.appointment.Specialty = append(b.appointment.Specialty, v)
	return b
}

// SetAppointmentType sets the AppointmentType field.
func (b *AppointmentBuilder) SetAppointmentType(v CodeableConcept) *AppointmentBuilder {
	b.appointment.AppointmentType = &v
	return b
}

// AddReasonCode adds a ReasonCode element.
func (b *AppointmentBuilder) AddReasonCode(v CodeableConcept) *AppointmentBuilder {
	b.appointment.ReasonCode = append(b.appointment.ReasonCode, v)
	return b
}

// AddReasonReference adds a ReasonReference element.
func (b *AppointmentBuilder) AddReasonReference(v Reference) *AppointmentBuilder {
	b.appointment.ReasonReference = append(b.appointment.ReasonReference, v)
	return b
}

// SetPriority sets the Priority field.
func (b *AppointmentBuilder) SetPriority(v uint32) *AppointmentBuilder {
	b.appointment.Priority = &v
	return b
}

// SetDescription sets the Description field.
func (b *AppointmentBuilder) SetDescription(v string) *AppointmentBuilder {
	b.appointment.Description = &v
	return b
}

// AddSupportingInformation adds a SupportingInformation element.
func (b *AppointmentBuilder) AddSupportingInformation(v Reference) *AppointmentBuilder {
	b.appointment.SupportingInformation = append(b.appointment.SupportingInformation, v)
	return b
}

// SetStart sets the Start field.
func (b *AppointmentBuilder) SetStart(v string) *AppointmentBuilder {
	b.appointment.Start = &v
	return b
}

// SetEnd sets the End field.
func (b *AppointmentBuilder) SetEnd(v string) *AppointmentBuilder {
	b.appointment.End = &v
	return b
}

// SetMinutesDuration sets the MinutesDuration field.
func (b *AppointmentBuilder) SetMinutesDuration(v uint32) *AppointmentBuilder {
	b.appointment.MinutesDuration = &v
	return b
}

// AddSlot adds a Slot element.
func (b *AppointmentBuilder) AddSlot(v Reference) *AppointmentBuilder {
	b.appointment.Slot = append(b.appointment.Slot, v)
	return b
}

// SetCreated sets the Created field.
func (b *AppointmentBuilder) SetCreated(v string) *AppointmentBuilder {
	b.appointment.Created = &v
	return b
}

// SetComment sets the Comment field.
func (b *AppointmentBuilder) SetComment(v string) *AppointmentBuilder {
	b.appointment.Comment = &v
	return b
}

// SetPatientInstruction sets the PatientInstruction field.
func (b *AppointmentBuilder) SetPatientInstruction(v string) *AppointmentBuilder {
	b.appointment.PatientInstruction = &v
	return b
}

// AddBasedOn adds a BasedOn element.
func (b *AppointmentBuilder) AddBasedOn(v Reference) *AppointmentBuilder {
	b.appointment.BasedOn = append(b.appointment.BasedOn, v)
	return b
}

// AddParticipant adds a Participant element.
func (b *AppointmentBuilder) AddParticipant(v AppointmentParticipant) *AppointmentBuilder {
	b.appointment.Participant = append(b.appointment.Participant, v)
	return b
}

// AddRequestedPeriod adds a RequestedPeriod element.
func (b *AppointmentBuilder) AddRequestedPeriod(v Period) *AppointmentBuilder {
	b.appointment.RequestedPeriod = append(b.appointment.RequestedPeriod, v)
	return b
}

// =============================================================================
// Appointment - Functional Options
// =============================================================================

// AppointmentOption is a functional option for configuring a Appointment.
type AppointmentOption func(*Appointment)

// NewAppointment creates a new Appointment with the given options.
func NewAppointment(opts ...AppointmentOption) *Appointment {
	r := &Appointment{}
	for _, opt := range opts {
		opt(r)
	}
	return r
}

// WithAppointmentId sets the Id field.
func WithAppointmentId(v string) AppointmentOption {
	return func(r *Appointment) {
		r.Id = &v
	}
}

// WithAppointmentMeta sets the Meta field.
func WithAppointmentMeta(v Meta) AppointmentOption {
	return func(r *Appointment) {
		r.Meta = &v
	}
}

// WithAppointmentImplicitRules sets the ImplicitRules field.
func WithAppointmentImplicitRules(v string) AppointmentOption {
	return func(r *Appointment) {
		r.ImplicitRules = &v
	}
}

// WithAppointmentLanguage sets the Language field.
func WithAppointmentLanguage(v string) AppointmentOption {
	return func(r *Appointment) {
		r.Language = &v
	}
}

// WithAppointmentText sets the Text field.
func WithAppointmentText(v Narrative) AppointmentOption {
	return func(r *Appointment) {
		r.Text = &v
	}
}

// WithAppointmentContained adds a Contained to the Appointment.
func WithAppointmentContained(v Resource) AppointmentOption {
	return func(r *Appointment) {
		r.Contained = append(r.Contained, v)
	}
}

// WithAppointmentExtension adds a Extension to the Appointment.
func WithAppointmentExtension(v Extension) AppointmentOption {
	return func(r *Appointment) {
		r.Extension = append(r.Extension, v)
	}
}

// WithAppointmentModifierExtension adds a ModifierExtension to the Appointment.
func WithAppointmentModifierExtension(v Extension) AppointmentOption {
	return func(r *Appointment) {
		r.ModifierExtension = append(r.ModifierExtension, v)
	}
}

// WithAppointmentIdentifier adds a Identifier to the Appointment.
func WithAppointmentIdentifier(v Identifier) AppointmentOption {
	return func(r *Appointment) {
		r.Identifier = append(r.Identifier, v)
	}
}

// WithAppointmentStatus sets the Status field.
func WithAppointmentStatus(v AppointmentStatus) AppointmentOption {
	return func(r *Appointment) {
		r.Status = &v
	}
}

// WithAppointmentCancelationReason sets the CancelationReason field.
func WithAppointmentCancelationReason(v CodeableConcept) AppointmentOption {
	return func(r *Appointment) {
		r.CancelationReason = &v
	}
}

// WithAppointmentServiceCategory adds a ServiceCategory to the Appointment.
func WithAppointmentServiceCategory(v CodeableConcept) AppointmentOption {
	return func(r *Appointment) {
		r.ServiceCategory = append(r.ServiceCategory, v)
	}
}

// WithAppointmentServiceType adds a ServiceType to the Appointment.
func WithAppointmentServiceType(v CodeableConcept) AppointmentOption {
	return func(r *Appointment) {
		r.ServiceType = append(r.ServiceType, v)
	}
}

// WithAppointmentSpecialty adds a Specialty to the Appointment.
func WithAppointmentSpecialty(v CodeableConcept) AppointmentOption {
	return func(r *Appointment) {
		r.Specialty = append(r.Specialty, v)
	}
}

// WithAppointmentAppointmentType sets the AppointmentType field.
func WithAppointmentAppointmentType(v CodeableConcept) AppointmentOption {
	return func(r *Appointment) {
		r.AppointmentType = &v
	}
}

// WithAppointmentReasonCode adds a ReasonCode to the Appointment.
func WithAppointmentReasonCode(v CodeableConcept) AppointmentOption {
	return func(r *Appointment) {
		r.ReasonCode = append(r.ReasonCode, v)
	}
}

// WithAppointmentReasonReference adds a ReasonReference to the Appointment.
func WithAppointmentReasonReference(v Reference) AppointmentOption {
	return func(r *Appointment) {
		r.ReasonReference = append(r.ReasonReference, v)
	}
}

// WithAppointmentPriority sets the Priority field.
func WithAppointmentPriority(v uint32) AppointmentOption {
	return func(r *Appointment) {
		r.Priority = &v
	}
}

// WithAppointmentDescription sets the Description field.
func WithAppointmentDescription(v string) AppointmentOption {
	return func(r *Appointment) {
		r.Description = &v
	}
}

// WithAppointmentSupportingInformation adds a SupportingInformation to the Appointment.
func WithAppointmentSupportingInformation(v Reference) AppointmentOption {
	return func(r *Appointment) {
		r.SupportingInformation = append(r.SupportingInformation, v)
	}
}

// WithAppointmentStart sets the Start field.
func WithAppointmentStart(v string) AppointmentOption {
	return func(r *Appointment) {
		r.Start = &v
	}
}

// WithAppointmentEnd sets the End field.
func WithAppointmentEnd(v string) AppointmentOption {
	return func(r *Appointment) {
		r.End = &v
	}
}

// WithAppointmentMinutesDuration sets the MinutesDuration field.
func WithAppointmentMinutesDuration(v uint32) AppointmentOption {
	return func(r *Appointment) {
		r.MinutesDuration = &v
	}
}

// WithAppointmentSlot adds a Slot to the Appointment.
func WithAppointmentSlot(v Reference) AppointmentOption {
	return func(r *Appointment) {
		r.Slot = append(r.Slot, v)
	}
}

// WithAppointmentCreated sets the Created field.
func WithAppointmentCreated(v string) AppointmentOption {
	return func(r *Appointment) {
		r.Created = &v
	}
}

// WithAppointmentComment sets the Comment field.
func WithAppointmentComment(v string) AppointmentOption {
	return func(r *Appointment) {
		r.Comment = &v
	}
}

// WithAppointmentPatientInstruction sets the PatientInstruction field.
func WithAppointmentPatientInstruction(v string) AppointmentOption {
	return func(r *Appointment) {
		r.PatientInstruction = &v
	}
}

// WithAppointmentBasedOn adds a BasedOn to the Appointment.
func WithAppointmentBasedOn(v Reference) AppointmentOption {
	return func(r *Appointment) {
		r.BasedOn = append(r.BasedOn, v)
	}
}

// WithAppointmentParticipant adds a Participant to the Appointment.
func WithAppointmentParticipant(v AppointmentParticipant) AppointmentOption {
	return func(r *Appointment) {
		r.Participant = append(r.Participant, v)
	}
}

// WithAppointmentRequestedPeriod adds a RequestedPeriod to the Appointment.
func WithAppointmentRequestedPeriod(v Period) AppointmentOption {
	return func(r *Appointment) {
		r.RequestedPeriod = append(r.RequestedPeriod, v)
	}
}
