// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (consolidated resource)
// Package: r4

package r4

import (
	"bytes"
	"encoding/json"
	"encoding/xml"
	"fmt"
)

// =============================================================================
// MedicinalProductAuthorization Resource
// =============================================================================

// MedicinalProductAuthorization represents FHIR MedicinalProductAuthorization.
type MedicinalProductAuthorization struct {
	// FHIR resource type
	ResourceType string `json:"resourceType"`
	// Logical id of this artifact
	Id *string `json:"id,omitempty"`
	// Metadata about the resource
	Meta *Meta `json:"meta,omitempty"`
	// A set of rules under which this content was created
	ImplicitRules *string `json:"implicitRules,omitempty"`
	// Extension for ImplicitRules
	ImplicitRulesExt *Element `json:"_implicitRules,omitempty"`
	// Language of the resource content
	Language *string `json:"language,omitempty"`
	// Extension for Language
	LanguageExt *Element `json:"_language,omitempty"`
	// Text summary of the resource, for human interpretation
	Text *Narrative `json:"text,omitempty"`
	// Contained, inline Resources
	Contained []Resource `json:"contained,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Business identifier for the marketing authorization, as assigned by a regulator
	Identifier []Identifier `json:"identifier,omitempty"`
	// The medicinal product that is being authorized
	Subject *Reference `json:"subject,omitempty"`
	// The country in which the marketing authorization has been granted
	Country []CodeableConcept `json:"country,omitempty"`
	// Jurisdiction within a country
	Jurisdiction []CodeableConcept `json:"jurisdiction,omitempty"`
	// The status of the marketing authorization
	Status *CodeableConcept `json:"status,omitempty"`
	// The date at which the given status has become applicable
	StatusDate *string `json:"statusDate,omitempty"`
	// Extension for StatusDate
	StatusDateExt *Element `json:"_statusDate,omitempty"`
	// The date when a suspended the marketing or the marketing authorization of the product is anticipated to be restored
	RestoreDate *string `json:"restoreDate,omitempty"`
	// Extension for RestoreDate
	RestoreDateExt *Element `json:"_restoreDate,omitempty"`
	// The beginning of the time period in which the marketing authorization is in the specific status shall be specified A complete date consisting of day, month and year shall be specified using the ISO 8601 date format
	ValidityPeriod *Period `json:"validityPeriod,omitempty"`
	// A period of time after authorization before generic product applicatiosn can be submitted
	DataExclusivityPeriod *Period `json:"dataExclusivityPeriod,omitempty"`
	// The date when the first authorization was granted by a Medicines Regulatory Agency
	DateOfFirstAuthorization *string `json:"dateOfFirstAuthorization,omitempty"`
	// Extension for DateOfFirstAuthorization
	DateOfFirstAuthorizationExt *Element `json:"_dateOfFirstAuthorization,omitempty"`
	// Date of first marketing authorization for a company's new medicinal product in any country in the World
	InternationalBirthDate *string `json:"internationalBirthDate,omitempty"`
	// Extension for InternationalBirthDate
	InternationalBirthDateExt *Element `json:"_internationalBirthDate,omitempty"`
	// The legal framework against which this authorization is granted
	LegalBasis *CodeableConcept `json:"legalBasis,omitempty"`
	// Authorization in areas within a country
	JurisdictionalAuthorization []MedicinalProductAuthorizationJurisdictionalAuthorization `json:"jurisdictionalAuthorization,omitempty"`
	// Marketing Authorization Holder
	Holder *Reference `json:"holder,omitempty"`
	// Medicines Regulatory Agency
	Regulator *Reference `json:"regulator,omitempty"`
	// The regulatory procedure for granting or amending a marketing authorization
	Procedure *MedicinalProductAuthorizationProcedure `json:"procedure,omitempty"`
}

// GetResourceType returns the FHIR resource type.
func (r *MedicinalProductAuthorization) GetResourceType() string {
	return "MedicinalProductAuthorization"
}

// GetId returns the resource's logical ID.
func (r *MedicinalProductAuthorization) GetId() *string {
	return r.Id
}

// SetId sets the resource's logical ID.
func (r *MedicinalProductAuthorization) SetId(id string) {
	r.Id = &id
}

// GetMeta returns the resource's Meta element.
func (r *MedicinalProductAuthorization) GetMeta() *Meta {
	return r.Meta
}

// SetMeta sets the resource's Meta element.
func (r *MedicinalProductAuthorization) SetMeta(m *Meta) {
	r.Meta = m
}

// GetText returns the resource's narrative text.
func (r *MedicinalProductAuthorization) GetText() *Narrative {
	return r.Text
}

// SetText sets the resource's narrative text.
func (r *MedicinalProductAuthorization) SetText(t *Narrative) {
	r.Text = t
}

// GetContained returns the resource's contained resources.
func (r *MedicinalProductAuthorization) GetContained() []Resource {
	return r.Contained
}

// GetExtension returns the resource's extensions.
func (r *MedicinalProductAuthorization) GetExtension() []Extension {
	return r.Extension
}

// GetModifierExtension returns the resource's modifier extensions.
func (r *MedicinalProductAuthorization) GetModifierExtension() []Extension {
	return r.ModifierExtension
}

// MarshalJSON ensures resourceType is always included in JSON output.
// HTML escaping is disabled to preserve FHIR narrative XHTML content.
//
// Note: Use the package-level Marshal function instead of json.Marshal
// to ensure HTML in narrative text.div fields is not escaped.
func (r MedicinalProductAuthorization) MarshalJSON() ([]byte, error) {
	r.ResourceType = "MedicinalProductAuthorization"
	type Alias MedicinalProductAuthorization
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	if err := enc.Encode((Alias)(r)); err != nil {
		return nil, err
	}
	b := buf.Bytes()
	if len(b) > 0 && b[len(b)-1] == '\n' {
		b = b[:len(b)-1]
	}
	return b, nil
}

// UnmarshalJSON handles deserialization of polymorphic contained resources.
func (r *MedicinalProductAuthorization) UnmarshalJSON(data []byte) error {
	// Use an alias to avoid infinite recursion
	type Alias MedicinalProductAuthorization
	aux := &struct {
		Contained []json.RawMessage `json:"contained,omitempty"`
		*Alias
	}{
		Alias: (*Alias)(r),
	}

	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}

	// Unmarshal each contained resource using the dispatcher
	if len(aux.Contained) > 0 {
		r.Contained = make([]Resource, len(aux.Contained))
		for i, raw := range aux.Contained {
			resource, err := UnmarshalResource(raw)
			if err != nil {
				return fmt.Errorf("failed to unmarshal contained[%d]: %w", i, err)
			}
			r.Contained[i] = resource
		}
	}

	return nil
}

// MarshalXML serializes MedicinalProductAuthorization to FHIR-conformant XML.
func (r MedicinalProductAuthorization) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if start.Name.Local == "" {
		start.Name.Local = "MedicinalProductAuthorization"
		start.Name.Space = fhirNamespace
	}
	if err := e.EncodeToken(start); err != nil {
		return err
	}

	if err := xmlEncodePrimitiveString(e, "id", r.Id, nil); err != nil {
		return err
	}
	if r.Meta != nil {
		if err := r.Meta.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "meta"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveString(e, "implicitRules", r.ImplicitRules, r.ImplicitRulesExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveString(e, "language", r.Language, r.LanguageExt); err != nil {
		return err
	}
	if r.Text != nil {
		if err := r.Text.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "text"}}); err != nil {
			return err
		}
	}
	for _, c := range r.Contained {
		if c != nil {
			if err := xmlEncodeContainedResource(e, c); err != nil {
				return err
			}
		}
	}
	for _, item := range r.Extension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "extension"}}); err != nil {
			return err
		}
	}
	for _, item := range r.ModifierExtension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "modifierExtension"}}); err != nil {
			return err
		}
	}
	for _, item := range r.Identifier {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "identifier"}}); err != nil {
			return err
		}
	}
	if r.Subject != nil {
		if err := r.Subject.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "subject"}}); err != nil {
			return err
		}
	}
	for _, item := range r.Country {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "country"}}); err != nil {
			return err
		}
	}
	for _, item := range r.Jurisdiction {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "jurisdiction"}}); err != nil {
			return err
		}
	}
	if r.Status != nil {
		if err := r.Status.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "status"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveString(e, "statusDate", r.StatusDate, r.StatusDateExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveString(e, "restoreDate", r.RestoreDate, r.RestoreDateExt); err != nil {
		return err
	}
	if r.ValidityPeriod != nil {
		if err := r.ValidityPeriod.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "validityPeriod"}}); err != nil {
			return err
		}
	}
	if r.DataExclusivityPeriod != nil {
		if err := r.DataExclusivityPeriod.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "dataExclusivityPeriod"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveString(e, "dateOfFirstAuthorization", r.DateOfFirstAuthorization, r.DateOfFirstAuthorizationExt); err != nil {
		return err
	}
	if err := xmlEncodePrimitiveString(e, "internationalBirthDate", r.InternationalBirthDate, r.InternationalBirthDateExt); err != nil {
		return err
	}
	if r.LegalBasis != nil {
		if err := r.LegalBasis.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "legalBasis"}}); err != nil {
			return err
		}
	}
	for _, item := range r.JurisdictionalAuthorization {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "jurisdictionalAuthorization"}}); err != nil {
			return err
		}
	}
	if r.Holder != nil {
		if err := r.Holder.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "holder"}}); err != nil {
			return err
		}
	}
	if r.Regulator != nil {
		if err := r.Regulator.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "regulator"}}); err != nil {
			return err
		}
	}
	if r.Procedure != nil {
		if err := r.Procedure.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "procedure"}}); err != nil {
			return err
		}
	}

	return e.EncodeToken(start.End())
}

// UnmarshalXML deserializes MedicinalProductAuthorization from FHIR-conformant XML.
func (r *MedicinalProductAuthorization) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	for {
		tok, err := d.Token()
		if err != nil {
			return err
		}
		switch t := tok.(type) {
		case xml.StartElement:
			switch t.Name.Local {
			case "id":
				v, _, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Id = v
			case "meta":
				var v Meta
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Meta = &v
			case "implicitRules":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.ImplicitRules = v
				r.ImplicitRulesExt = ext
			case "language":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.Language = v
				r.LanguageExt = ext
			case "text":
				var v Narrative
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Text = &v
			case "contained":
				res, err := xmlDecodeContainedResource(d, t)
				if err != nil {
					return err
				}
				if res != nil {
					r.Contained = append(r.Contained, res)
				}
			case "extension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Extension = append(r.Extension, v)
			case "modifierExtension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.ModifierExtension = append(r.ModifierExtension, v)
			case "identifier":
				var v Identifier
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Identifier = append(r.Identifier, v)
			case "subject":
				var v Reference
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Subject = &v
			case "country":
				var v CodeableConcept
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Country = append(r.Country, v)
			case "jurisdiction":
				var v CodeableConcept
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Jurisdiction = append(r.Jurisdiction, v)
			case "status":
				var v CodeableConcept
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Status = &v
			case "statusDate":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.StatusDate = v
				r.StatusDateExt = ext
			case "restoreDate":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.RestoreDate = v
				r.RestoreDateExt = ext
			case "validityPeriod":
				var v Period
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.ValidityPeriod = &v
			case "dataExclusivityPeriod":
				var v Period
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.DataExclusivityPeriod = &v
			case "dateOfFirstAuthorization":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.DateOfFirstAuthorization = v
				r.DateOfFirstAuthorizationExt = ext
			case "internationalBirthDate":
				v, ext, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.InternationalBirthDate = v
				r.InternationalBirthDateExt = ext
			case "legalBasis":
				var v CodeableConcept
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.LegalBasis = &v
			case "jurisdictionalAuthorization":
				var v MedicinalProductAuthorizationJurisdictionalAuthorization
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.JurisdictionalAuthorization = append(r.JurisdictionalAuthorization, v)
			case "holder":
				var v Reference
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Holder = &v
			case "regulator":
				var v Reference
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Regulator = &v
			case "procedure":
				var v MedicinalProductAuthorizationProcedure
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Procedure = &v
			default:
				if err := d.Skip(); err != nil {
					return err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// MedicinalProductAuthorizationJurisdictionalAuthorization represents the MedicinalProductAuthorization.jurisdictionalAuthorization backbone element.
// Authorization in areas within a country
type MedicinalProductAuthorizationJurisdictionalAuthorization struct {
	// Unique id for inter-element referencing
	Id *string `json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// The assigned number for the marketing authorization
	Identifier []Identifier `json:"identifier,omitempty"`
	// Country of authorization
	Country *CodeableConcept `json:"country,omitempty"`
	// Jurisdiction within a country
	Jurisdiction []CodeableConcept `json:"jurisdiction,omitempty"`
	// The legal status of supply in a jurisdiction or region
	LegalStatusOfSupply *CodeableConcept `json:"legalStatusOfSupply,omitempty"`
	// The start and expected end date of the authorization
	ValidityPeriod *Period `json:"validityPeriod,omitempty"`
}

// MarshalXML serializes MedicinalProductAuthorizationJurisdictionalAuthorization to FHIR-conformant XML.
func (b MedicinalProductAuthorizationJurisdictionalAuthorization) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if start.Name.Local == "" {
		start.Name.Local = "MedicinalProductAuthorization.jurisdictionalAuthorization"
	}
	if b.Id != nil {
		start.Attr = append(start.Attr, xml.Attr{Name: xml.Name{Local: "id"}, Value: *b.Id})
	}
	if err := e.EncodeToken(start); err != nil {
		return err
	}

	for _, item := range b.Extension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "extension"}}); err != nil {
			return err
		}
	}
	for _, item := range b.ModifierExtension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "modifierExtension"}}); err != nil {
			return err
		}
	}
	for _, item := range b.Identifier {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "identifier"}}); err != nil {
			return err
		}
	}
	if b.Country != nil {
		if err := b.Country.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "country"}}); err != nil {
			return err
		}
	}
	for _, item := range b.Jurisdiction {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "jurisdiction"}}); err != nil {
			return err
		}
	}
	if b.LegalStatusOfSupply != nil {
		if err := b.LegalStatusOfSupply.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "legalStatusOfSupply"}}); err != nil {
			return err
		}
	}
	if b.ValidityPeriod != nil {
		if err := b.ValidityPeriod.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "validityPeriod"}}); err != nil {
			return err
		}
	}

	return e.EncodeToken(start.End())
}

// UnmarshalXML deserializes MedicinalProductAuthorizationJurisdictionalAuthorization from FHIR-conformant XML.
func (r *MedicinalProductAuthorizationJurisdictionalAuthorization) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	for _, attr := range start.Attr {
		if attr.Name.Local == "id" {
			v := attr.Value
			r.Id = &v
		}
	}

	for {
		tok, err := d.Token()
		if err != nil {
			return err
		}
		switch t := tok.(type) {
		case xml.StartElement:
			switch t.Name.Local {
			case "extension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Extension = append(r.Extension, v)
			case "modifierExtension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.ModifierExtension = append(r.ModifierExtension, v)
			case "identifier":
				var v Identifier
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Identifier = append(r.Identifier, v)
			case "country":
				var v CodeableConcept
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Country = &v
			case "jurisdiction":
				var v CodeableConcept
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Jurisdiction = append(r.Jurisdiction, v)
			case "legalStatusOfSupply":
				var v CodeableConcept
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.LegalStatusOfSupply = &v
			case "validityPeriod":
				var v Period
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.ValidityPeriod = &v
			default:
				if err := d.Skip(); err != nil {
					return err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// MedicinalProductAuthorizationProcedure represents the MedicinalProductAuthorization.procedure backbone element.
// The regulatory procedure for granting or amending a marketing authorization
type MedicinalProductAuthorizationProcedure struct {
	// Unique id for inter-element referencing
	Id *string `json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Identifier for this procedure
	Identifier *Identifier `json:"identifier,omitempty"`
	// Type of procedure
	Type CodeableConcept `json:"type,omitempty"`
	// Date of procedure
	DatePeriod *Period `json:"datePeriod,omitempty"`
	// Date of procedure
	DateDateTime *string `json:"dateDateTime,omitempty"`
	// Extension for DateDateTime
	DateDateTimeExt *Element `json:"_dateDateTime,omitempty"`
	// Applcations submitted to obtain a marketing authorization
	Application []MedicinalProductAuthorizationProcedure `json:"application,omitempty"`
}

// MarshalXML serializes MedicinalProductAuthorizationProcedure to FHIR-conformant XML.
func (b MedicinalProductAuthorizationProcedure) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if start.Name.Local == "" {
		start.Name.Local = "MedicinalProductAuthorization.procedure"
	}
	if b.Id != nil {
		start.Attr = append(start.Attr, xml.Attr{Name: xml.Name{Local: "id"}, Value: *b.Id})
	}
	if err := e.EncodeToken(start); err != nil {
		return err
	}

	for _, item := range b.Extension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "extension"}}); err != nil {
			return err
		}
	}
	for _, item := range b.ModifierExtension {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "modifierExtension"}}); err != nil {
			return err
		}
	}
	if b.Identifier != nil {
		if err := b.Identifier.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "identifier"}}); err != nil {
			return err
		}
	}
	if err := b.Type.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "type"}}); err != nil {
		return err
	}
	if b.DatePeriod != nil {
		if err := b.DatePeriod.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "datePeriod"}}); err != nil {
			return err
		}
	}
	if err := xmlEncodePrimitiveString(e, "dateDateTime", b.DateDateTime, nil); err != nil {
		return err
	}
	for _, item := range b.Application {
		if err := item.MarshalXML(e, xml.StartElement{Name: xml.Name{Local: "application"}}); err != nil {
			return err
		}
	}

	return e.EncodeToken(start.End())
}

// UnmarshalXML deserializes MedicinalProductAuthorizationProcedure from FHIR-conformant XML.
func (r *MedicinalProductAuthorizationProcedure) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	for _, attr := range start.Attr {
		if attr.Name.Local == "id" {
			v := attr.Value
			r.Id = &v
		}
	}

	for {
		tok, err := d.Token()
		if err != nil {
			return err
		}
		switch t := tok.(type) {
		case xml.StartElement:
			switch t.Name.Local {
			case "extension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Extension = append(r.Extension, v)
			case "modifierExtension":
				var v Extension
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.ModifierExtension = append(r.ModifierExtension, v)
			case "identifier":
				var v Identifier
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Identifier = &v
			case "type":
				if err := r.Type.UnmarshalXML(d, t); err != nil {
					return err
				}
			case "datePeriod":
				var v Period
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.DatePeriod = &v
			case "dateDateTime":
				v, _, err := xmlDecodePrimitiveString(d, t)
				if err != nil {
					return err
				}
				r.DateDateTime = v
			case "application":
				var v MedicinalProductAuthorizationProcedure
				if err := v.UnmarshalXML(d, t); err != nil {
					return err
				}
				r.Application = append(r.Application, v)
			default:
				if err := d.Skip(); err != nil {
					return err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// =============================================================================
// MedicinalProductAuthorization - Fluent Builder
// =============================================================================

// MedicinalProductAuthorizationBuilder provides a fluent API for constructing MedicinalProductAuthorization resources.
type MedicinalProductAuthorizationBuilder struct {
	medicinalProductAuthorization *MedicinalProductAuthorization
}

// NewMedicinalProductAuthorizationBuilder creates a new MedicinalProductAuthorizationBuilder.
func NewMedicinalProductAuthorizationBuilder() *MedicinalProductAuthorizationBuilder {
	return &MedicinalProductAuthorizationBuilder{
		medicinalProductAuthorization: &MedicinalProductAuthorization{},
	}
}

// Build returns the constructed MedicinalProductAuthorization resource.
func (b *MedicinalProductAuthorizationBuilder) Build() *MedicinalProductAuthorization {
	return b.medicinalProductAuthorization
}

// SetId sets the Id field.
func (b *MedicinalProductAuthorizationBuilder) SetId(v string) *MedicinalProductAuthorizationBuilder {
	b.medicinalProductAuthorization.Id = &v
	return b
}

// SetMeta sets the Meta field.
func (b *MedicinalProductAuthorizationBuilder) SetMeta(v Meta) *MedicinalProductAuthorizationBuilder {
	b.medicinalProductAuthorization.Meta = &v
	return b
}

// SetImplicitRules sets the ImplicitRules field.
func (b *MedicinalProductAuthorizationBuilder) SetImplicitRules(v string) *MedicinalProductAuthorizationBuilder {
	b.medicinalProductAuthorization.ImplicitRules = &v
	return b
}

// SetLanguage sets the Language field.
func (b *MedicinalProductAuthorizationBuilder) SetLanguage(v string) *MedicinalProductAuthorizationBuilder {
	b.medicinalProductAuthorization.Language = &v
	return b
}

// SetText sets the Text field.
func (b *MedicinalProductAuthorizationBuilder) SetText(v Narrative) *MedicinalProductAuthorizationBuilder {
	b.medicinalProductAuthorization.Text = &v
	return b
}

// AddContained adds a Contained element.
func (b *MedicinalProductAuthorizationBuilder) AddContained(v Resource) *MedicinalProductAuthorizationBuilder {
	b.medicinalProductAuthorization.Contained = append(b.medicinalProductAuthorization.Contained, v)
	return b
}

// AddExtension adds a Extension element.
func (b *MedicinalProductAuthorizationBuilder) AddExtension(v Extension) *MedicinalProductAuthorizationBuilder {
	b.medicinalProductAuthorization.Extension = append(b.medicinalProductAuthorization.Extension, v)
	return b
}

// AddModifierExtension adds a ModifierExtension element.
func (b *MedicinalProductAuthorizationBuilder) AddModifierExtension(v Extension) *MedicinalProductAuthorizationBuilder {
	b.medicinalProductAuthorization.ModifierExtension = append(b.medicinalProductAuthorization.ModifierExtension, v)
	return b
}

// AddIdentifier adds a Identifier element.
func (b *MedicinalProductAuthorizationBuilder) AddIdentifier(v Identifier) *MedicinalProductAuthorizationBuilder {
	b.medicinalProductAuthorization.Identifier = append(b.medicinalProductAuthorization.Identifier, v)
	return b
}

// SetSubject sets the Subject field.
func (b *MedicinalProductAuthorizationBuilder) SetSubject(v Reference) *MedicinalProductAuthorizationBuilder {
	b.medicinalProductAuthorization.Subject = &v
	return b
}

// AddCountry adds a Country element.
func (b *MedicinalProductAuthorizationBuilder) AddCountry(v CodeableConcept) *MedicinalProductAuthorizationBuilder {
	b.medicinalProductAuthorization.Country = append(b.medicinalProductAuthorization.Country, v)
	return b
}

// AddJurisdiction adds a Jurisdiction element.
func (b *MedicinalProductAuthorizationBuilder) AddJurisdiction(v CodeableConcept) *MedicinalProductAuthorizationBuilder {
	b.medicinalProductAuthorization.Jurisdiction = append(b.medicinalProductAuthorization.Jurisdiction, v)
	return b
}

// SetStatus sets the Status field.
func (b *MedicinalProductAuthorizationBuilder) SetStatus(v CodeableConcept) *MedicinalProductAuthorizationBuilder {
	b.medicinalProductAuthorization.Status = &v
	return b
}

// SetStatusDate sets the StatusDate field.
func (b *MedicinalProductAuthorizationBuilder) SetStatusDate(v string) *MedicinalProductAuthorizationBuilder {
	b.medicinalProductAuthorization.StatusDate = &v
	return b
}

// SetRestoreDate sets the RestoreDate field.
func (b *MedicinalProductAuthorizationBuilder) SetRestoreDate(v string) *MedicinalProductAuthorizationBuilder {
	b.medicinalProductAuthorization.RestoreDate = &v
	return b
}

// SetValidityPeriod sets the ValidityPeriod field.
func (b *MedicinalProductAuthorizationBuilder) SetValidityPeriod(v Period) *MedicinalProductAuthorizationBuilder {
	b.medicinalProductAuthorization.ValidityPeriod = &v
	return b
}

// SetDataExclusivityPeriod sets the DataExclusivityPeriod field.
func (b *MedicinalProductAuthorizationBuilder) SetDataExclusivityPeriod(v Period) *MedicinalProductAuthorizationBuilder {
	b.medicinalProductAuthorization.DataExclusivityPeriod = &v
	return b
}

// SetDateOfFirstAuthorization sets the DateOfFirstAuthorization field.
func (b *MedicinalProductAuthorizationBuilder) SetDateOfFirstAuthorization(v string) *MedicinalProductAuthorizationBuilder {
	b.medicinalProductAuthorization.DateOfFirstAuthorization = &v
	return b
}

// SetInternationalBirthDate sets the InternationalBirthDate field.
func (b *MedicinalProductAuthorizationBuilder) SetInternationalBirthDate(v string) *MedicinalProductAuthorizationBuilder {
	b.medicinalProductAuthorization.InternationalBirthDate = &v
	return b
}

// SetLegalBasis sets the LegalBasis field.
func (b *MedicinalProductAuthorizationBuilder) SetLegalBasis(v CodeableConcept) *MedicinalProductAuthorizationBuilder {
	b.medicinalProductAuthorization.LegalBasis = &v
	return b
}

// AddJurisdictionalAuthorization adds a JurisdictionalAuthorization element.
func (b *MedicinalProductAuthorizationBuilder) AddJurisdictionalAuthorization(v MedicinalProductAuthorizationJurisdictionalAuthorization) *MedicinalProductAuthorizationBuilder {
	b.medicinalProductAuthorization.JurisdictionalAuthorization = append(b.medicinalProductAuthorization.JurisdictionalAuthorization, v)
	return b
}

// SetHolder sets the Holder field.
func (b *MedicinalProductAuthorizationBuilder) SetHolder(v Reference) *MedicinalProductAuthorizationBuilder {
	b.medicinalProductAuthorization.Holder = &v
	return b
}

// SetRegulator sets the Regulator field.
func (b *MedicinalProductAuthorizationBuilder) SetRegulator(v Reference) *MedicinalProductAuthorizationBuilder {
	b.medicinalProductAuthorization.Regulator = &v
	return b
}

// SetProcedure sets the Procedure field.
func (b *MedicinalProductAuthorizationBuilder) SetProcedure(v MedicinalProductAuthorizationProcedure) *MedicinalProductAuthorizationBuilder {
	b.medicinalProductAuthorization.Procedure = &v
	return b
}

// =============================================================================
// MedicinalProductAuthorization - Functional Options
// =============================================================================

// MedicinalProductAuthorizationOption is a functional option for configuring a MedicinalProductAuthorization.
type MedicinalProductAuthorizationOption func(*MedicinalProductAuthorization)

// NewMedicinalProductAuthorization creates a new MedicinalProductAuthorization with the given options.
func NewMedicinalProductAuthorization(opts ...MedicinalProductAuthorizationOption) *MedicinalProductAuthorization {
	r := &MedicinalProductAuthorization{}
	for _, opt := range opts {
		opt(r)
	}
	return r
}

// WithMedicinalProductAuthorizationId sets the Id field.
func WithMedicinalProductAuthorizationId(v string) MedicinalProductAuthorizationOption {
	return func(r *MedicinalProductAuthorization) {
		r.Id = &v
	}
}

// WithMedicinalProductAuthorizationMeta sets the Meta field.
func WithMedicinalProductAuthorizationMeta(v Meta) MedicinalProductAuthorizationOption {
	return func(r *MedicinalProductAuthorization) {
		r.Meta = &v
	}
}

// WithMedicinalProductAuthorizationImplicitRules sets the ImplicitRules field.
func WithMedicinalProductAuthorizationImplicitRules(v string) MedicinalProductAuthorizationOption {
	return func(r *MedicinalProductAuthorization) {
		r.ImplicitRules = &v
	}
}

// WithMedicinalProductAuthorizationLanguage sets the Language field.
func WithMedicinalProductAuthorizationLanguage(v string) MedicinalProductAuthorizationOption {
	return func(r *MedicinalProductAuthorization) {
		r.Language = &v
	}
}

// WithMedicinalProductAuthorizationText sets the Text field.
func WithMedicinalProductAuthorizationText(v Narrative) MedicinalProductAuthorizationOption {
	return func(r *MedicinalProductAuthorization) {
		r.Text = &v
	}
}

// WithMedicinalProductAuthorizationContained adds a Contained to the MedicinalProductAuthorization.
func WithMedicinalProductAuthorizationContained(v Resource) MedicinalProductAuthorizationOption {
	return func(r *MedicinalProductAuthorization) {
		r.Contained = append(r.Contained, v)
	}
}

// WithMedicinalProductAuthorizationExtension adds a Extension to the MedicinalProductAuthorization.
func WithMedicinalProductAuthorizationExtension(v Extension) MedicinalProductAuthorizationOption {
	return func(r *MedicinalProductAuthorization) {
		r.Extension = append(r.Extension, v)
	}
}

// WithMedicinalProductAuthorizationModifierExtension adds a ModifierExtension to the MedicinalProductAuthorization.
func WithMedicinalProductAuthorizationModifierExtension(v Extension) MedicinalProductAuthorizationOption {
	return func(r *MedicinalProductAuthorization) {
		r.ModifierExtension = append(r.ModifierExtension, v)
	}
}

// WithMedicinalProductAuthorizationIdentifier adds a Identifier to the MedicinalProductAuthorization.
func WithMedicinalProductAuthorizationIdentifier(v Identifier) MedicinalProductAuthorizationOption {
	return func(r *MedicinalProductAuthorization) {
		r.Identifier = append(r.Identifier, v)
	}
}

// WithMedicinalProductAuthorizationSubject sets the Subject field.
func WithMedicinalProductAuthorizationSubject(v Reference) MedicinalProductAuthorizationOption {
	return func(r *MedicinalProductAuthorization) {
		r.Subject = &v
	}
}

// WithMedicinalProductAuthorizationCountry adds a Country to the MedicinalProductAuthorization.
func WithMedicinalProductAuthorizationCountry(v CodeableConcept) MedicinalProductAuthorizationOption {
	return func(r *MedicinalProductAuthorization) {
		r.Country = append(r.Country, v)
	}
}

// WithMedicinalProductAuthorizationJurisdiction adds a Jurisdiction to the MedicinalProductAuthorization.
func WithMedicinalProductAuthorizationJurisdiction(v CodeableConcept) MedicinalProductAuthorizationOption {
	return func(r *MedicinalProductAuthorization) {
		r.Jurisdiction = append(r.Jurisdiction, v)
	}
}

// WithMedicinalProductAuthorizationStatus sets the Status field.
func WithMedicinalProductAuthorizationStatus(v CodeableConcept) MedicinalProductAuthorizationOption {
	return func(r *MedicinalProductAuthorization) {
		r.Status = &v
	}
}

// WithMedicinalProductAuthorizationStatusDate sets the StatusDate field.
func WithMedicinalProductAuthorizationStatusDate(v string) MedicinalProductAuthorizationOption {
	return func(r *MedicinalProductAuthorization) {
		r.StatusDate = &v
	}
}

// WithMedicinalProductAuthorizationRestoreDate sets the RestoreDate field.
func WithMedicinalProductAuthorizationRestoreDate(v string) MedicinalProductAuthorizationOption {
	return func(r *MedicinalProductAuthorization) {
		r.RestoreDate = &v
	}
}

// WithMedicinalProductAuthorizationValidityPeriod sets the ValidityPeriod field.
func WithMedicinalProductAuthorizationValidityPeriod(v Period) MedicinalProductAuthorizationOption {
	return func(r *MedicinalProductAuthorization) {
		r.ValidityPeriod = &v
	}
}

// WithMedicinalProductAuthorizationDataExclusivityPeriod sets the DataExclusivityPeriod field.
func WithMedicinalProductAuthorizationDataExclusivityPeriod(v Period) MedicinalProductAuthorizationOption {
	return func(r *MedicinalProductAuthorization) {
		r.DataExclusivityPeriod = &v
	}
}

// WithMedicinalProductAuthorizationDateOfFirstAuthorization sets the DateOfFirstAuthorization field.
func WithMedicinalProductAuthorizationDateOfFirstAuthorization(v string) MedicinalProductAuthorizationOption {
	return func(r *MedicinalProductAuthorization) {
		r.DateOfFirstAuthorization = &v
	}
}

// WithMedicinalProductAuthorizationInternationalBirthDate sets the InternationalBirthDate field.
func WithMedicinalProductAuthorizationInternationalBirthDate(v string) MedicinalProductAuthorizationOption {
	return func(r *MedicinalProductAuthorization) {
		r.InternationalBirthDate = &v
	}
}

// WithMedicinalProductAuthorizationLegalBasis sets the LegalBasis field.
func WithMedicinalProductAuthorizationLegalBasis(v CodeableConcept) MedicinalProductAuthorizationOption {
	return func(r *MedicinalProductAuthorization) {
		r.LegalBasis = &v
	}
}

// WithMedicinalProductAuthorizationJurisdictionalAuthorization adds a JurisdictionalAuthorization to the MedicinalProductAuthorization.
func WithMedicinalProductAuthorizationJurisdictionalAuthorization(v MedicinalProductAuthorizationJurisdictionalAuthorization) MedicinalProductAuthorizationOption {
	return func(r *MedicinalProductAuthorization) {
		r.JurisdictionalAuthorization = append(r.JurisdictionalAuthorization, v)
	}
}

// WithMedicinalProductAuthorizationHolder sets the Holder field.
func WithMedicinalProductAuthorizationHolder(v Reference) MedicinalProductAuthorizationOption {
	return func(r *MedicinalProductAuthorization) {
		r.Holder = &v
	}
}

// WithMedicinalProductAuthorizationRegulator sets the Regulator field.
func WithMedicinalProductAuthorizationRegulator(v Reference) MedicinalProductAuthorizationOption {
	return func(r *MedicinalProductAuthorization) {
		r.Regulator = &v
	}
}

// WithMedicinalProductAuthorizationProcedure sets the Procedure field.
func WithMedicinalProductAuthorizationProcedure(v MedicinalProductAuthorizationProcedure) MedicinalProductAuthorizationOption {
	return func(r *MedicinalProductAuthorization) {
		r.Procedure = &v
	}
}
